// Snapshots and restores.
//
// Backups are commands rather than part of the NodeSpec, which is the opposite of how
// cron works, and the difference is deliberate: cron is the customer's schedule and has
// to keep firing while the panel is down, while a backup is the platform's and needs
// the things only the panel has - the retention policy across every node, the
// destination credentials, and the restore-point record that makes the result findable.
// db-scheduler enqueues the job, the panel hands it to a node, the node does the work
// (design section 8.3).
//
// A backup that has never been restored is not a backup, so `verify` is a field here
// and restoring is a first-class command rather than a runbook.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wisper/v1/backup.proto

package wisperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What is being copied. The two need completely different techniques - a filesystem
// snapshot with a brief write pause against a logical dump - and nothing about either
// generalises to the other, so the kind is explicit rather than inferred from the id.
type BackupTargetKind int32

const (
	BackupTargetKind_BACKUP_TARGET_KIND_UNSPECIFIED BackupTargetKind = 0
	BackupTargetKind_BACKUP_TARGET_KIND_VOLUME      BackupTargetKind = 1
	BackupTargetKind_BACKUP_TARGET_KIND_DATABASE    BackupTargetKind = 2
)

// Enum value maps for BackupTargetKind.
var (
	BackupTargetKind_name = map[int32]string{
		0: "BACKUP_TARGET_KIND_UNSPECIFIED",
		1: "BACKUP_TARGET_KIND_VOLUME",
		2: "BACKUP_TARGET_KIND_DATABASE",
	}
	BackupTargetKind_value = map[string]int32{
		"BACKUP_TARGET_KIND_UNSPECIFIED": 0,
		"BACKUP_TARGET_KIND_VOLUME":      1,
		"BACKUP_TARGET_KIND_DATABASE":    2,
	}
)

func (x BackupTargetKind) Enum() *BackupTargetKind {
	p := new(BackupTargetKind)
	*p = x
	return p
}

func (x BackupTargetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupTargetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_backup_proto_enumTypes[0].Descriptor()
}

func (BackupTargetKind) Type() protoreflect.EnumType {
	return &file_wisper_v1_backup_proto_enumTypes[0]
}

func (x BackupTargetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupTargetKind.Descriptor instead.
func (BackupTargetKind) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{0}
}

type DestinationKind int32

const (
	DestinationKind_DESTINATION_KIND_UNSPECIFIED DestinationKind = 0
	// Any S3-compatible object store. The normal case: offsite, and not on the node whose
	// disk is the thing most likely to fail.
	DestinationKind_DESTINATION_KIND_S3 DestinationKind = 1
	// A directory on the node itself. Fast to make and fast to restore, and worth nothing
	// when the machine is gone - offered for the customer who wants a quick rollback
	// point before a risky deployment.
	DestinationKind_DESTINATION_KIND_LOCAL DestinationKind = 2
)

// Enum value maps for DestinationKind.
var (
	DestinationKind_name = map[int32]string{
		0: "DESTINATION_KIND_UNSPECIFIED",
		1: "DESTINATION_KIND_S3",
		2: "DESTINATION_KIND_LOCAL",
	}
	DestinationKind_value = map[string]int32{
		"DESTINATION_KIND_UNSPECIFIED": 0,
		"DESTINATION_KIND_S3":          1,
		"DESTINATION_KIND_LOCAL":       2,
	}
)

func (x DestinationKind) Enum() *DestinationKind {
	p := new(DestinationKind)
	*p = x
	return p
}

func (x DestinationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestinationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_backup_proto_enumTypes[1].Descriptor()
}

func (DestinationKind) Type() protoreflect.EnumType {
	return &file_wisper_v1_backup_proto_enumTypes[1]
}

func (x DestinationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestinationKind.Descriptor instead.
func (DestinationKind) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{1}
}

type BackupStage int32

const (
	BackupStage_BACKUP_STAGE_UNSPECIFIED BackupStage = 0
	BackupStage_BACKUP_STAGE_QUIESCE     BackupStage = 1
	BackupStage_BACKUP_STAGE_SNAPSHOT    BackupStage = 2
	BackupStage_BACKUP_STAGE_UPLOAD      BackupStage = 3
	BackupStage_BACKUP_STAGE_VERIFY      BackupStage = 4
	BackupStage_BACKUP_STAGE_PRUNE       BackupStage = 5
)

// Enum value maps for BackupStage.
var (
	BackupStage_name = map[int32]string{
		0: "BACKUP_STAGE_UNSPECIFIED",
		1: "BACKUP_STAGE_QUIESCE",
		2: "BACKUP_STAGE_SNAPSHOT",
		3: "BACKUP_STAGE_UPLOAD",
		4: "BACKUP_STAGE_VERIFY",
		5: "BACKUP_STAGE_PRUNE",
	}
	BackupStage_value = map[string]int32{
		"BACKUP_STAGE_UNSPECIFIED": 0,
		"BACKUP_STAGE_QUIESCE":     1,
		"BACKUP_STAGE_SNAPSHOT":    2,
		"BACKUP_STAGE_UPLOAD":      3,
		"BACKUP_STAGE_VERIFY":      4,
		"BACKUP_STAGE_PRUNE":       5,
	}
)

func (x BackupStage) Enum() *BackupStage {
	p := new(BackupStage)
	*p = x
	return p
}

func (x BackupStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupStage) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_backup_proto_enumTypes[2].Descriptor()
}

func (BackupStage) Type() protoreflect.EnumType {
	return &file_wisper_v1_backup_proto_enumTypes[2]
}

func (x BackupStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupStage.Descriptor instead.
func (BackupStage) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{2}
}

// Where the archive goes.
type BackupDestination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  DestinationKind        `protobuf:"varint,1,opt,name=kind,proto3,enum=wisper.v1.DestinationKind" json:"kind,omitempty"`
	S3    *S3Destination         `protobuf:"bytes,2,opt,name=s3,proto3" json:"s3,omitempty"`
	// DESTINATION_KIND_LOCAL: a path relative to the node's backup directory, never an
	// absolute path, for the same reason no other path in this contract is absolute.
	LocalPrefix   string `protobuf:"bytes,3,opt,name=local_prefix,json=localPrefix,proto3" json:"local_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupDestination) Reset() {
	*x = BackupDestination{}
	mi := &file_wisper_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDestination) ProtoMessage() {}

func (x *BackupDestination) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDestination.ProtoReflect.Descriptor instead.
func (*BackupDestination) Descriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupDestination) GetKind() DestinationKind {
	if x != nil {
		return x.Kind
	}
	return DestinationKind_DESTINATION_KIND_UNSPECIFIED
}

func (x *BackupDestination) GetS3() *S3Destination {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *BackupDestination) GetLocalPrefix() string {
	if x != nil {
		return x.LocalPrefix
	}
	return ""
}

type S3Destination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full URL including scheme. Explicit rather than derived from a region so MinIO,
	// Backblaze and Wasabi all work without a special case each.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region   string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Bucket   string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Key prefix. The node appends its own object name; the panel keeps the resulting key
	// in the restore point.
	Prefix string `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Held encrypted by the panel and sent over the control stream when a backup runs,
	// because the node is the side with the bytes and the bandwidth. It is never written
	// to the node's SQLite state.
	AccessKeyId     string `protobuf:"bytes,5,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string `protobuf:"bytes,6,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	// Bucket in the path rather than the hostname. Required by most self-hosted stores
	// and refused by some hosted ones, so it cannot be guessed.
	PathStyle bool `protobuf:"varint,7,opt,name=path_style,json=pathStyle,proto3" json:"path_style,omitempty"`
	// Server-side encryption algorithm to request, "AES256" or empty for none.
	ServerSideEncryption string `protobuf:"bytes,8,opt,name=server_side_encryption,json=serverSideEncryption,proto3" json:"server_side_encryption,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *S3Destination) Reset() {
	*x = S3Destination{}
	mi := &file_wisper_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Destination) ProtoMessage() {}

func (x *S3Destination) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Destination.ProtoReflect.Descriptor instead.
func (*S3Destination) Descriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{1}
}

func (x *S3Destination) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Destination) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3Destination) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Destination) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *S3Destination) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *S3Destination) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *S3Destination) GetPathStyle() bool {
	if x != nil {
		return x.PathStyle
	}
	return false
}

func (x *S3Destination) GetServerSideEncryption() string {
	if x != nil {
		return x.ServerSideEncryption
	}
	return ""
}

// How many copies to keep. Applied by the node at the end of a successful backup rather
// than by a separate prune command, because a prune that is scheduled separately is a
// prune somebody forgets to schedule - and because deletion has to happen where the
// destination credentials are.
type RetentionRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keep at least this many of the most recent, whatever the age rules say. Stops a
	// dormant project's only backup from ageing out.
	KeepLast    int32 `protobuf:"varint,1,opt,name=keep_last,json=keepLast,proto3" json:"keep_last,omitempty"`
	KeepDaily   int32 `protobuf:"varint,2,opt,name=keep_daily,json=keepDaily,proto3" json:"keep_daily,omitempty"`
	KeepWeekly  int32 `protobuf:"varint,3,opt,name=keep_weekly,json=keepWeekly,proto3" json:"keep_weekly,omitempty"`
	KeepMonthly int32 `protobuf:"varint,4,opt,name=keep_monthly,json=keepMonthly,proto3" json:"keep_monthly,omitempty"`
	// Hard ceiling on the space this subject's backups occupy at the destination. The
	// oldest go first. Zero means no ceiling.
	MaxTotalBytes int64 `protobuf:"varint,5,opt,name=max_total_bytes,json=maxTotalBytes,proto3" json:"max_total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionRule) Reset() {
	*x = RetentionRule{}
	mi := &file_wisper_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionRule) ProtoMessage() {}

func (x *RetentionRule) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionRule.ProtoReflect.Descriptor instead.
func (*RetentionRule) Descriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *RetentionRule) GetKeepLast() int32 {
	if x != nil {
		return x.KeepLast
	}
	return 0
}

func (x *RetentionRule) GetKeepDaily() int32 {
	if x != nil {
		return x.KeepDaily
	}
	return 0
}

func (x *RetentionRule) GetKeepWeekly() int32 {
	if x != nil {
		return x.KeepWeekly
	}
	return 0
}

func (x *RetentionRule) GetKeepMonthly() int32 {
	if x != nil {
		return x.KeepMonthly
	}
	return 0
}

func (x *RetentionRule) GetMaxTotalBytes() int64 {
	if x != nil {
		return x.MaxTotalBytes
	}
	return 0
}

// Take a backup now.
type RunBackup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The panel's id for this run. The restore point is recorded against it, and a
	// repeated command with the same id is the same backup, not a second one.
	BackupId string           `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	Kind     BackupTargetKind `protobuf:"varint,2,opt,name=kind,proto3,enum=wisper.v1.BackupTargetKind" json:"kind,omitempty"`
	// Volume id or database grant id, depending on the kind.
	SubjectId string `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// The workload that owns the volume. Needed to pause writes for the moment the
	// snapshot is taken; a copy of a running application's data directory is not a
	// backup, it is a directory that happens to have been open.
	WorkloadId string `protobuf:"bytes,4,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	// Set for BACKUP_TARGET_KIND_DATABASE: which engine to dump with, and the grant to
	// dump. The dump tool and the connection both depend on it.
	Engine       DatabaseEngine     `protobuf:"varint,5,opt,name=engine,proto3,enum=wisper.v1.DatabaseEngine" json:"engine,omitempty"`
	DatabaseName string             `protobuf:"bytes,6,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Destination  *BackupDestination `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	Retention    *RetentionRule     `protobuf:"bytes,8,opt,name=retention,proto3" json:"retention,omitempty"`
	// Read the archive back from the destination and check its checksum before reporting
	// success. Costs the download; buys knowing the backup exists somewhere other than in
	// a log line that says it was uploaded.
	Verify bool `protobuf:"varint,9,opt,name=verify,proto3" json:"verify,omitempty"`
	// Give up after this long. A backup that runs into the next scheduled one is how a
	// node ends up doing nothing but backups.
	TimeoutSeconds int64 `protobuf:"varint,10,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunBackup) Reset() {
	*x = RunBackup{}
	mi := &file_wisper_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBackup) ProtoMessage() {}

func (x *RunBackup) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBackup.ProtoReflect.Descriptor instead.
func (*RunBackup) Descriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *RunBackup) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *RunBackup) GetKind() BackupTargetKind {
	if x != nil {
		return x.Kind
	}
	return BackupTargetKind_BACKUP_TARGET_KIND_UNSPECIFIED
}

func (x *RunBackup) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *RunBackup) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *RunBackup) GetEngine() DatabaseEngine {
	if x != nil {
		return x.Engine
	}
	return DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED
}

func (x *RunBackup) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *RunBackup) GetDestination() *BackupDestination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *RunBackup) GetRetention() *RetentionRule {
	if x != nil {
		return x.Retention
	}
	return nil
}

func (x *RunBackup) GetVerify() bool {
	if x != nil {
		return x.Verify
	}
	return false
}

func (x *RunBackup) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// The result, returned as the outcome of the command that asked for it.
type BackupCompleted struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BackupId string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	Success  bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// The handle a restore is asked for by. Minted by the node because the node is what
	// knows the final object name, and stored by the panel as the restore point.
	RestorePointId string `protobuf:"bytes,3,opt,name=restore_point_id,json=restorePointId,proto3" json:"restore_point_id,omitempty"`
	// Where it landed: the S3 key or the local relative path. Enough to find it by hand
	// when the panel's row is the thing that was lost.
	Location  string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	SizeBytes int64  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256    string `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// How long the application was paused, as distinct from how long the whole backup
	// took. This is the number a customer is actually affected by, so it is measured
	// rather than assumed to be small.
	QuiesceMillis int64                  `protobuf:"varint,7,opt,name=quiesce_millis,json=quiesceMillis,proto3" json:"quiesce_millis,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// True only when `verify` was asked for and passed, so "verified" never means "not
	// checked".
	Verified bool `protobuf:"varint,10,opt,name=verified,proto3" json:"verified,omitempty"`
	// How many old backups the retention rule removed in the same pass.
	Pruned int32 `protobuf:"varint,11,opt,name=pruned,proto3" json:"pruned,omitempty"`
	// Which stage failed, and why. A failure at UPLOAD is the customer's object store; a
	// failure at QUIESCE is their application.
	FailedStage   BackupStage `protobuf:"varint,12,opt,name=failed_stage,json=failedStage,proto3,enum=wisper.v1.BackupStage" json:"failed_stage,omitempty"`
	Detail        string      `protobuf:"bytes,13,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCompleted) Reset() {
	*x = BackupCompleted{}
	mi := &file_wisper_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCompleted) ProtoMessage() {}

func (x *BackupCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCompleted.ProtoReflect.Descriptor instead.
func (*BackupCompleted) Descriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{4}
}

func (x *BackupCompleted) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *BackupCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BackupCompleted) GetRestorePointId() string {
	if x != nil {
		return x.RestorePointId
	}
	return ""
}

func (x *BackupCompleted) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BackupCompleted) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BackupCompleted) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BackupCompleted) GetQuiesceMillis() int64 {
	if x != nil {
		return x.QuiesceMillis
	}
	return 0
}

func (x *BackupCompleted) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *BackupCompleted) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *BackupCompleted) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *BackupCompleted) GetPruned() int32 {
	if x != nil {
		return x.Pruned
	}
	return 0
}

func (x *BackupCompleted) GetFailedStage() BackupStage {
	if x != nil {
		return x.FailedStage
	}
	return BackupStage_BACKUP_STAGE_UNSPECIFIED
}

func (x *BackupCompleted) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Put a restore point back. One button in the panel (design section 8.3), one command
// here, so there is no sequence of steps for an operator to get wrong at the worst
// possible moment.
type RestoreBackup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The panel's id for this restore attempt, distinct from the backup's.
	RestoreId      string `protobuf:"bytes,1,opt,name=restore_id,json=restoreId,proto3" json:"restore_id,omitempty"`
	RestorePointId string `protobuf:"bytes,2,opt,name=restore_point_id,json=restorePointId,proto3" json:"restore_point_id,omitempty"`
	// From the restore point, so a restore works even when the destination's layout has
	// been reorganised since.
	Location     string           `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Kind         BackupTargetKind `protobuf:"varint,4,opt,name=kind,proto3,enum=wisper.v1.BackupTargetKind" json:"kind,omitempty"`
	SubjectId    string           `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	WorkloadId   string           `protobuf:"bytes,6,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Engine       DatabaseEngine   `protobuf:"varint,7,opt,name=engine,proto3,enum=wisper.v1.DatabaseEngine" json:"engine,omitempty"`
	DatabaseName string           `protobuf:"bytes,8,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	// Where to read from. Sent again rather than remembered because credentials rotate,
	// and a restore is exactly when a stale one is least welcome.
	Source *BackupDestination `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	// Stop the workload before overwriting its volume, and start it again afterwards.
	// Restoring underneath a running process gives it a filesystem that changed while it
	// was not looking.
	StopWorkload bool `protobuf:"varint,10,opt,name=stop_workload,json=stopWorkload,proto3" json:"stop_workload,omitempty"`
	// Restore alongside instead of over the top: the volume is restored to a sibling
	// directory and the database to a name with a suffix, so a customer can look before
	// committing. This is what makes testing a restore safe enough that people do it.
	DryRun         bool  `protobuf:"varint,11,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	TimeoutSeconds int64 `protobuf:"varint,12,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestoreBackup) Reset() {
	*x = RestoreBackup{}
	mi := &file_wisper_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackup) ProtoMessage() {}

func (x *RestoreBackup) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackup.ProtoReflect.Descriptor instead.
func (*RestoreBackup) Descriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreBackup) GetRestoreId() string {
	if x != nil {
		return x.RestoreId
	}
	return ""
}

func (x *RestoreBackup) GetRestorePointId() string {
	if x != nil {
		return x.RestorePointId
	}
	return ""
}

func (x *RestoreBackup) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RestoreBackup) GetKind() BackupTargetKind {
	if x != nil {
		return x.Kind
	}
	return BackupTargetKind_BACKUP_TARGET_KIND_UNSPECIFIED
}

func (x *RestoreBackup) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *RestoreBackup) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *RestoreBackup) GetEngine() DatabaseEngine {
	if x != nil {
		return x.Engine
	}
	return DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED
}

func (x *RestoreBackup) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *RestoreBackup) GetSource() *BackupDestination {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RestoreBackup) GetStopWorkload() bool {
	if x != nil {
		return x.StopWorkload
	}
	return false
}

func (x *RestoreBackup) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *RestoreBackup) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RestoreCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestoreId     string                 `protobuf:"bytes,1,opt,name=restore_id,json=restoreId,proto3" json:"restore_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	BytesRestored int64                  `protobuf:"varint,3,opt,name=bytes_restored,json=bytesRestored,proto3" json:"bytes_restored,omitempty"`
	// Where the data actually went. Differs from the target for a dry run, and the
	// customer has to be told where to look.
	RestoredTo        string                 `protobuf:"bytes,4,opt,name=restored_to,json=restoredTo,proto3" json:"restored_to,omitempty"`
	WorkloadRestarted bool                   `protobuf:"varint,5,opt,name=workload_restarted,json=workloadRestarted,proto3" json:"workload_restarted,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Detail            string                 `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RestoreCompleted) Reset() {
	*x = RestoreCompleted{}
	mi := &file_wisper_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCompleted) ProtoMessage() {}

func (x *RestoreCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCompleted.ProtoReflect.Descriptor instead.
func (*RestoreCompleted) Descriptor() ([]byte, []int) {
	return file_wisper_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreCompleted) GetRestoreId() string {
	if x != nil {
		return x.RestoreId
	}
	return ""
}

func (x *RestoreCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreCompleted) GetBytesRestored() int64 {
	if x != nil {
		return x.BytesRestored
	}
	return 0
}

func (x *RestoreCompleted) GetRestoredTo() string {
	if x != nil {
		return x.RestoredTo
	}
	return ""
}

func (x *RestoreCompleted) GetWorkloadRestarted() bool {
	if x != nil {
		return x.WorkloadRestarted
	}
	return false
}

func (x *RestoreCompleted) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RestoreCompleted) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *RestoreCompleted) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_wisper_v1_backup_proto protoreflect.FileDescriptor

const file_wisper_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x16wisper/v1/backup.proto\x12\twisper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18wisper/v1/database.proto\"\x90\x01\n" +
	"\x11BackupDestination\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.wisper.v1.DestinationKindR\x04kind\x12(\n" +
	"\x02s3\x18\x02 \x01(\v2\x18.wisper.v1.S3DestinationR\x02s3\x12!\n" +
	"\flocal_prefix\x18\x03 \x01(\tR\vlocalPrefix\"\x98\x02\n" +
	"\rS3Destination\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\"\n" +
	"\raccess_key_id\x18\x05 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x06 \x01(\tR\x0fsecretAccessKey\x12\x1d\n" +
	"\n" +
	"path_style\x18\a \x01(\bR\tpathStyle\x124\n" +
	"\x16server_side_encryption\x18\b \x01(\tR\x14serverSideEncryption\"\xb7\x01\n" +
	"\rRetentionRule\x12\x1b\n" +
	"\tkeep_last\x18\x01 \x01(\x05R\bkeepLast\x12\x1d\n" +
	"\n" +
	"keep_daily\x18\x02 \x01(\x05R\tkeepDaily\x12\x1f\n" +
	"\vkeep_weekly\x18\x03 \x01(\x05R\n" +
	"keepWeekly\x12!\n" +
	"\fkeep_monthly\x18\x04 \x01(\x05R\vkeepMonthly\x12&\n" +
	"\x0fmax_total_bytes\x18\x05 \x01(\x03R\rmaxTotalBytes\"\xaa\x03\n" +
	"\tRunBackup\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.wisper.v1.BackupTargetKindR\x04kind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x1f\n" +
	"\vworkload_id\x18\x04 \x01(\tR\n" +
	"workloadId\x121\n" +
	"\x06engine\x18\x05 \x01(\x0e2\x19.wisper.v1.DatabaseEngineR\x06engine\x12#\n" +
	"\rdatabase_name\x18\x06 \x01(\tR\fdatabaseName\x12>\n" +
	"\vdestination\x18\a \x01(\v2\x1c.wisper.v1.BackupDestinationR\vdestination\x126\n" +
	"\tretention\x18\b \x01(\v2\x18.wisper.v1.RetentionRuleR\tretention\x12\x16\n" +
	"\x06verify\x18\t \x01(\bR\x06verify\x12'\n" +
	"\x0ftimeout_seconds\x18\n" +
	" \x01(\x03R\x0etimeoutSeconds\"\xeb\x03\n" +
	"\x0fBackupCompleted\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12(\n" +
	"\x10restore_point_id\x18\x03 \x01(\tR\x0erestorePointId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12%\n" +
	"\x0equiesce_millis\x18\a \x01(\x03R\rquiesceMillis\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x1a\n" +
	"\bverified\x18\n" +
	" \x01(\bR\bverified\x12\x16\n" +
	"\x06pruned\x18\v \x01(\x05R\x06pruned\x129\n" +
	"\ffailed_stage\x18\f \x01(\x0e2\x16.wisper.v1.BackupStageR\vfailedStage\x12\x16\n" +
	"\x06detail\x18\r \x01(\tR\x06detail\"\xda\x03\n" +
	"\rRestoreBackup\x12\x1d\n" +
	"\n" +
	"restore_id\x18\x01 \x01(\tR\trestoreId\x12(\n" +
	"\x10restore_point_id\x18\x02 \x01(\tR\x0erestorePointId\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12/\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1b.wisper.v1.BackupTargetKindR\x04kind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId\x12\x1f\n" +
	"\vworkload_id\x18\x06 \x01(\tR\n" +
	"workloadId\x121\n" +
	"\x06engine\x18\a \x01(\x0e2\x19.wisper.v1.DatabaseEngineR\x06engine\x12#\n" +
	"\rdatabase_name\x18\b \x01(\tR\fdatabaseName\x124\n" +
	"\x06source\x18\t \x01(\v2\x1c.wisper.v1.BackupDestinationR\x06source\x12#\n" +
	"\rstop_workload\x18\n" +
	" \x01(\bR\fstopWorkload\x12\x17\n" +
	"\adry_run\x18\v \x01(\bR\x06dryRun\x12'\n" +
	"\x0ftimeout_seconds\x18\f \x01(\x03R\x0etimeoutSeconds\"\xd2\x02\n" +
	"\x10RestoreCompleted\x12\x1d\n" +
	"\n" +
	"restore_id\x18\x01 \x01(\tR\trestoreId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12%\n" +
	"\x0ebytes_restored\x18\x03 \x01(\x03R\rbytesRestored\x12\x1f\n" +
	"\vrestored_to\x18\x04 \x01(\tR\n" +
	"restoredTo\x12-\n" +
	"\x12workload_restarted\x18\x05 \x01(\bR\x11workloadRestarted\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x16\n" +
	"\x06detail\x18\b \x01(\tR\x06detail*v\n" +
	"\x10BackupTargetKind\x12\"\n" +
	"\x1eBACKUP_TARGET_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19BACKUP_TARGET_KIND_VOLUME\x10\x01\x12\x1f\n" +
	"\x1bBACKUP_TARGET_KIND_DATABASE\x10\x02*h\n" +
	"\x0fDestinationKind\x12 \n" +
	"\x1cDESTINATION_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DESTINATION_KIND_S3\x10\x01\x12\x1a\n" +
	"\x16DESTINATION_KIND_LOCAL\x10\x02*\xaa\x01\n" +
	"\vBackupStage\x12\x1c\n" +
	"\x18BACKUP_STAGE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BACKUP_STAGE_QUIESCE\x10\x01\x12\x19\n" +
	"\x15BACKUP_STAGE_SNAPSHOT\x10\x02\x12\x17\n" +
	"\x13BACKUP_STAGE_UPLOAD\x10\x03\x12\x17\n" +
	"\x13BACKUP_STAGE_VERIFY\x10\x04\x12\x16\n" +
	"\x12BACKUP_STAGE_PRUNE\x10\x05Bl\n" +
	"\x1clhqm.furimeo.wisper.proto.v1B\vBackupProtoP\x01Z=github.com/furimeo/wisper/sasayaki/internal/wisperpb;wisperpbb\x06proto3"

var (
	file_wisper_v1_backup_proto_rawDescOnce sync.Once
	file_wisper_v1_backup_proto_rawDescData []byte
)

func file_wisper_v1_backup_proto_rawDescGZIP() []byte {
	file_wisper_v1_backup_proto_rawDescOnce.Do(func() {
		file_wisper_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wisper_v1_backup_proto_rawDesc), len(file_wisper_v1_backup_proto_rawDesc)))
	})
	return file_wisper_v1_backup_proto_rawDescData
}

var file_wisper_v1_backup_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wisper_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wisper_v1_backup_proto_goTypes = []any{
	(BackupTargetKind)(0),         // 0: wisper.v1.BackupTargetKind
	(DestinationKind)(0),          // 1: wisper.v1.DestinationKind
	(BackupStage)(0),              // 2: wisper.v1.BackupStage
	(*BackupDestination)(nil),     // 3: wisper.v1.BackupDestination
	(*S3Destination)(nil),         // 4: wisper.v1.S3Destination
	(*RetentionRule)(nil),         // 5: wisper.v1.RetentionRule
	(*RunBackup)(nil),             // 6: wisper.v1.RunBackup
	(*BackupCompleted)(nil),       // 7: wisper.v1.BackupCompleted
	(*RestoreBackup)(nil),         // 8: wisper.v1.RestoreBackup
	(*RestoreCompleted)(nil),      // 9: wisper.v1.RestoreCompleted
	(DatabaseEngine)(0),           // 10: wisper.v1.DatabaseEngine
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_wisper_v1_backup_proto_depIdxs = []int32{
	1,  // 0: wisper.v1.BackupDestination.kind:type_name -> wisper.v1.DestinationKind
	4,  // 1: wisper.v1.BackupDestination.s3:type_name -> wisper.v1.S3Destination
	0,  // 2: wisper.v1.RunBackup.kind:type_name -> wisper.v1.BackupTargetKind
	10, // 3: wisper.v1.RunBackup.engine:type_name -> wisper.v1.DatabaseEngine
	3,  // 4: wisper.v1.RunBackup.destination:type_name -> wisper.v1.BackupDestination
	5,  // 5: wisper.v1.RunBackup.retention:type_name -> wisper.v1.RetentionRule
	11, // 6: wisper.v1.BackupCompleted.started_at:type_name -> google.protobuf.Timestamp
	11, // 7: wisper.v1.BackupCompleted.finished_at:type_name -> google.protobuf.Timestamp
	2,  // 8: wisper.v1.BackupCompleted.failed_stage:type_name -> wisper.v1.BackupStage
	0,  // 9: wisper.v1.RestoreBackup.kind:type_name -> wisper.v1.BackupTargetKind
	10, // 10: wisper.v1.RestoreBackup.engine:type_name -> wisper.v1.DatabaseEngine
	3,  // 11: wisper.v1.RestoreBackup.source:type_name -> wisper.v1.BackupDestination
	11, // 12: wisper.v1.RestoreCompleted.started_at:type_name -> google.protobuf.Timestamp
	11, // 13: wisper.v1.RestoreCompleted.finished_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_wisper_v1_backup_proto_init() }
func file_wisper_v1_backup_proto_init() {
	if File_wisper_v1_backup_proto != nil {
		return
	}
	file_wisper_v1_database_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wisper_v1_backup_proto_rawDesc), len(file_wisper_v1_backup_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wisper_v1_backup_proto_goTypes,
		DependencyIndexes: file_wisper_v1_backup_proto_depIdxs,
		EnumInfos:         file_wisper_v1_backup_proto_enumTypes,
		MessageInfos:      file_wisper_v1_backup_proto_msgTypes,
	}.Build()
	File_wisper_v1_backup_proto = out.File
	file_wisper_v1_backup_proto_goTypes = nil
	file_wisper_v1_backup_proto_depIdxs = nil
}
