// Builds: turning a git repository or an uploaded archive into something the node can
// serve.
//
// v1 builds on the node that will run the result (design section 11.4). There is no
// builder pool and no registry, so nothing has to be shipped anywhere afterwards - a
// static site's output lands in a release directory next to the ones before it, and an
// app's image lands in the local Docker daemon.
//
// Publishing is not here. A finished build produces a release id, and the release goes
// live when the next NodeSpec names it in the workload. Rollback is the same move with
// an older id. One mechanism, so "what is live" has exactly one answer (design
// section 5.5).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wisper/v1/build.proto

package wisperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The build recipe. Presets are resolved by the panel into a concrete image and
// concrete commands, so two nodes cannot disagree about what "the Node preset" means
// and a customer can see and override every step.
type BuildPreset int32

const (
	BuildPreset_BUILD_PRESET_UNSPECIFIED BuildPreset = 0
	// No build step: the repository already contains the site.
	BuildPreset_BUILD_PRESET_STATIC BuildPreset = 1
	BuildPreset_BUILD_PRESET_NODE   BuildPreset = 2
	BuildPreset_BUILD_PRESET_HUGO   BuildPreset = 3
	BuildPreset_BUILD_PRESET_ASTRO  BuildPreset = 4
	// Build an image from the repository's own Dockerfile.
	BuildPreset_BUILD_PRESET_DOCKERFILE BuildPreset = 5
)

// Enum value maps for BuildPreset.
var (
	BuildPreset_name = map[int32]string{
		0: "BUILD_PRESET_UNSPECIFIED",
		1: "BUILD_PRESET_STATIC",
		2: "BUILD_PRESET_NODE",
		3: "BUILD_PRESET_HUGO",
		4: "BUILD_PRESET_ASTRO",
		5: "BUILD_PRESET_DOCKERFILE",
	}
	BuildPreset_value = map[string]int32{
		"BUILD_PRESET_UNSPECIFIED": 0,
		"BUILD_PRESET_STATIC":      1,
		"BUILD_PRESET_NODE":        2,
		"BUILD_PRESET_HUGO":        3,
		"BUILD_PRESET_ASTRO":       4,
		"BUILD_PRESET_DOCKERFILE":  5,
	}
)

func (x BuildPreset) Enum() *BuildPreset {
	p := new(BuildPreset)
	*p = x
	return p
}

func (x BuildPreset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildPreset) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_build_proto_enumTypes[0].Descriptor()
}

func (BuildPreset) Type() protoreflect.EnumType {
	return &file_wisper_v1_build_proto_enumTypes[0]
}

func (x BuildPreset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildPreset.Descriptor instead.
func (BuildPreset) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{0}
}

type BuildOutputKind int32

const (
	BuildOutputKind_BUILD_OUTPUT_KIND_UNSPECIFIED BuildOutputKind = 0
	// Files into releases/<release_id>/, ready for the symlink to point at.
	BuildOutputKind_BUILD_OUTPUT_KIND_STATIC_RELEASE BuildOutputKind = 1
	// An image in the local Docker daemon, tagged with the release id.
	BuildOutputKind_BUILD_OUTPUT_KIND_CONTAINER_IMAGE BuildOutputKind = 2
)

// Enum value maps for BuildOutputKind.
var (
	BuildOutputKind_name = map[int32]string{
		0: "BUILD_OUTPUT_KIND_UNSPECIFIED",
		1: "BUILD_OUTPUT_KIND_STATIC_RELEASE",
		2: "BUILD_OUTPUT_KIND_CONTAINER_IMAGE",
	}
	BuildOutputKind_value = map[string]int32{
		"BUILD_OUTPUT_KIND_UNSPECIFIED":     0,
		"BUILD_OUTPUT_KIND_STATIC_RELEASE":  1,
		"BUILD_OUTPUT_KIND_CONTAINER_IMAGE": 2,
	}
)

func (x BuildOutputKind) Enum() *BuildOutputKind {
	p := new(BuildOutputKind)
	*p = x
	return p
}

func (x BuildOutputKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildOutputKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_build_proto_enumTypes[1].Descriptor()
}

func (BuildOutputKind) Type() protoreflect.EnumType {
	return &file_wisper_v1_build_proto_enumTypes[1]
}

func (x BuildOutputKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildOutputKind.Descriptor instead.
func (BuildOutputKind) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{1}
}

type BuildStage int32

const (
	BuildStage_BUILD_STAGE_UNSPECIFIED BuildStage = 0
	BuildStage_BUILD_STAGE_FETCH       BuildStage = 1
	BuildStage_BUILD_STAGE_INSTALL     BuildStage = 2
	BuildStage_BUILD_STAGE_BUILD       BuildStage = 3
	// Moving the output into releases/ or tagging the image.
	BuildStage_BUILD_STAGE_PUBLISH BuildStage = 4
)

// Enum value maps for BuildStage.
var (
	BuildStage_name = map[int32]string{
		0: "BUILD_STAGE_UNSPECIFIED",
		1: "BUILD_STAGE_FETCH",
		2: "BUILD_STAGE_INSTALL",
		3: "BUILD_STAGE_BUILD",
		4: "BUILD_STAGE_PUBLISH",
	}
	BuildStage_value = map[string]int32{
		"BUILD_STAGE_UNSPECIFIED": 0,
		"BUILD_STAGE_FETCH":       1,
		"BUILD_STAGE_INSTALL":     2,
		"BUILD_STAGE_BUILD":       3,
		"BUILD_STAGE_PUBLISH":     4,
	}
)

func (x BuildStage) Enum() *BuildStage {
	p := new(BuildStage)
	*p = x
	return p
}

func (x BuildStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStage) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_build_proto_enumTypes[2].Descriptor()
}

func (BuildStage) Type() protoreflect.EnumType {
	return &file_wisper_v1_build_proto_enumTypes[2]
}

func (x BuildStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStage.Descriptor instead.
func (BuildStage) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{2}
}

// Where the source comes from.
type BuildSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*BuildSource_Git
	//	*BuildSource_Archive
	Source        isBuildSource_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSource) Reset() {
	*x = BuildSource{}
	mi := &file_wisper_v1_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSource) ProtoMessage() {}

func (x *BuildSource) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSource.ProtoReflect.Descriptor instead.
func (*BuildSource) Descriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{0}
}

func (x *BuildSource) GetSource() isBuildSource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *BuildSource) GetGit() *GitSource {
	if x != nil {
		if x, ok := x.Source.(*BuildSource_Git); ok {
			return x.Git
		}
	}
	return nil
}

func (x *BuildSource) GetArchive() *ArchiveSource {
	if x != nil {
		if x, ok := x.Source.(*BuildSource_Archive); ok {
			return x.Archive
		}
	}
	return nil
}

type isBuildSource_Source interface {
	isBuildSource_Source()
}

type BuildSource_Git struct {
	Git *GitSource `protobuf:"bytes,1,opt,name=git,proto3,oneof"`
}

type BuildSource_Archive struct {
	Archive *ArchiveSource `protobuf:"bytes,2,opt,name=archive,proto3,oneof"`
}

func (*BuildSource_Git) isBuildSource_Source() {}

func (*BuildSource_Archive) isBuildSource_Source() {}

type GitSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTPS only. An SSH remote would need a key on the node, and the node deliberately
	// holds no credential it was not handed for one job.
	RepositoryUrl string `protobuf:"bytes,1,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	// Branch or tag, for the log line and for a clone that has no commit yet.
	Ref string `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	// The exact commit to build, resolved by the panel from the webhook. Pinning it here
	// means the build is of what triggered it, not of whatever the branch moved to while
	// the job sat in the queue.
	Commit string `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	// Shallow by default. A depth of 1 turns a large repository's clone from minutes into
	// seconds, and a build does not need history.
	Depth      int32 `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	Submodules bool  `protobuf:"varint,5,opt,name=submodules,proto3" json:"submodules,omitempty"`
	// A deploy token for a private repository, held encrypted by the panel and sent for
	// this one build. Used as the HTTP basic password; the node never writes it to disk.
	AccessToken string `protobuf:"bytes,6,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Build from a directory inside the repository, for a monorepo. Empty is the root.
	Subdirectory  string `protobuf:"bytes,7,opt,name=subdirectory,proto3" json:"subdirectory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitSource) Reset() {
	*x = GitSource{}
	mi := &file_wisper_v1_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitSource) ProtoMessage() {}

func (x *GitSource) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitSource.ProtoReflect.Descriptor instead.
func (*GitSource) Descriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{1}
}

func (x *GitSource) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *GitSource) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitSource) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GitSource) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GitSource) GetSubmodules() bool {
	if x != nil {
		return x.Submodules
	}
	return false
}

func (x *GitSource) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GitSource) GetSubdirectory() string {
	if x != nil {
		return x.Subdirectory
	}
	return ""
}

// A zip the customer uploaded through the panel, for the project that is not in git
// (design section 5.5).
//
// The archive reaches the node the same way any other file does: the panel pushes it
// into the node's upload-staging FileRoot with a resumable chunked upload, then sends
// this. There is no HTTP fetch, because a node can reach the panel's gRPC endpoint and
// is not guaranteed to be able to reach anything else of the panel's.
type ArchiveSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The completed upload session in the staging root.
	UploadSessionId string `protobuf:"bytes,1,opt,name=upload_session_id,json=uploadSessionId,proto3" json:"upload_session_id,omitempty"`
	// Hex SHA-256 of the archive, re-checked before it is unpacked.
	Sha256 string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Build from a directory inside the archive. Empty is the root.
	Subdirectory  string `protobuf:"bytes,3,opt,name=subdirectory,proto3" json:"subdirectory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveSource) Reset() {
	*x = ArchiveSource{}
	mi := &file_wisper_v1_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveSource) ProtoMessage() {}

func (x *ArchiveSource) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveSource.ProtoReflect.Descriptor instead.
func (*ArchiveSource) Descriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{2}
}

func (x *ArchiveSource) GetUploadSessionId() string {
	if x != nil {
		return x.UploadSessionId
	}
	return ""
}

func (x *ArchiveSource) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArchiveSource) GetSubdirectory() string {
	if x != nil {
		return x.Subdirectory
	}
	return ""
}

type BuildPlan struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Preset BuildPreset            `protobuf:"varint,1,opt,name=preset,proto3,enum=wisper.v1.BuildPreset" json:"preset,omitempty"`
	// The image the build runs inside, resolved by the panel. Ephemeral, discarded
	// afterwards, and never the image that ends up running the customer's app.
	BuilderImage string `protobuf:"bytes,2,opt,name=builder_image,json=builderImage,proto3" json:"builder_image,omitempty"`
	// argv, run in the checkout. Never shell strings: a branch name with a backtick in it
	// must not become a command (AGENTS.md section 5).
	InstallCommand []string `protobuf:"bytes,3,rep,name=install_command,json=installCommand,proto3" json:"install_command,omitempty"`
	BuildCommand   []string `protobuf:"bytes,4,rep,name=build_command,json=buildCommand,proto3" json:"build_command,omitempty"`
	// What to publish, relative to the checkout: "dist", "public", "_site". Ignored when
	// the output is an image.
	OutputDirectory string `protobuf:"bytes,5,opt,name=output_directory,json=outputDirectory,proto3" json:"output_directory,omitempty"`
	// BUILD_PRESET_DOCKERFILE only.
	DockerfilePath string `protobuf:"bytes,6,opt,name=dockerfile_path,json=dockerfilePath,proto3" json:"dockerfile_path,omitempty"`
	BuildContext   string `protobuf:"bytes,7,opt,name=build_context,json=buildContext,proto3" json:"build_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildPlan) Reset() {
	*x = BuildPlan{}
	mi := &file_wisper_v1_build_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildPlan) ProtoMessage() {}

func (x *BuildPlan) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_build_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildPlan.ProtoReflect.Descriptor instead.
func (*BuildPlan) Descriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{3}
}

func (x *BuildPlan) GetPreset() BuildPreset {
	if x != nil {
		return x.Preset
	}
	return BuildPreset_BUILD_PRESET_UNSPECIFIED
}

func (x *BuildPlan) GetBuilderImage() string {
	if x != nil {
		return x.BuilderImage
	}
	return ""
}

func (x *BuildPlan) GetInstallCommand() []string {
	if x != nil {
		return x.InstallCommand
	}
	return nil
}

func (x *BuildPlan) GetBuildCommand() []string {
	if x != nil {
		return x.BuildCommand
	}
	return nil
}

func (x *BuildPlan) GetOutputDirectory() string {
	if x != nil {
		return x.OutputDirectory
	}
	return ""
}

func (x *BuildPlan) GetDockerfilePath() string {
	if x != nil {
		return x.DockerfilePath
	}
	return ""
}

func (x *BuildPlan) GetBuildContext() string {
	if x != nil {
		return x.BuildContext
	}
	return ""
}

// Run a build, pushed down the control stream.
type StartBuild struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The panel's deployment id. Also the release id: one deployment produces one
	// release, and two names for the same thing is one join nobody needs.
	BuildId    string          `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	WorkloadId string          `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Source     *BuildSource    `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Plan       *BuildPlan      `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Output     BuildOutputKind `protobuf:"varint,5,opt,name=output,proto3,enum=wisper.v1.BuildOutputKind" json:"output,omitempty"`
	// Variables for the build itself - API keys a static generator needs, NODE_ENV. Not
	// the workload's runtime environment: a build-time secret that leaks into a public
	// bundle is the customer's problem to avoid, and mixing the two makes it impossible.
	// Docker build args come from this list too.
	BuildEnv []*EnvVar `protobuf:"bytes,6,rep,name=build_env,json=buildEnv,proto3" json:"build_env,omitempty"`
	// The build container gets a ceiling like any other. A webpack build with no memory
	// limit takes the node down with it, and it is the neighbours who notice.
	Limits *ResourceLimits `protobuf:"bytes,7,opt,name=limits,proto3" json:"limits,omitempty"`
	// Killed and reported as failed after this. A hung build holds a slot forever.
	TimeoutSeconds int64 `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// The LogRequest stream_id build output is pushed under, so the customer's browser is
	// already watching before the first line appears.
	LogStreamId string `protobuf:"bytes,9,opt,name=log_stream_id,json=logStreamId,proto3" json:"log_stream_id,omitempty"`
	// Reuse the previous workspace: node_modules, the package manager's cache, the
	// generator's cache. Off for the build a customer starts after one that failed
	// strangely, which is what "clear cache and deploy" means.
	UseCache      bool `protobuf:"varint,10,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBuild) Reset() {
	*x = StartBuild{}
	mi := &file_wisper_v1_build_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuild) ProtoMessage() {}

func (x *StartBuild) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_build_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuild.ProtoReflect.Descriptor instead.
func (*StartBuild) Descriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{4}
}

func (x *StartBuild) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *StartBuild) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *StartBuild) GetSource() *BuildSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *StartBuild) GetPlan() *BuildPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *StartBuild) GetOutput() BuildOutputKind {
	if x != nil {
		return x.Output
	}
	return BuildOutputKind_BUILD_OUTPUT_KIND_UNSPECIFIED
}

func (x *StartBuild) GetBuildEnv() []*EnvVar {
	if x != nil {
		return x.BuildEnv
	}
	return nil
}

func (x *StartBuild) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *StartBuild) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *StartBuild) GetLogStreamId() string {
	if x != nil {
		return x.LogStreamId
	}
	return ""
}

func (x *StartBuild) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

// The result, returned as the outcome of the command that asked for it. Progress is not
// here: it goes up the log stream, where the customer is already looking.
type BuildCompleted struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BuildId string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// The directory under releases/ that now exists, ready to be named by a NodeSpec.
	// Empty when the build failed, which is what stops a broken build from being
	// published.
	ReleaseId string `protobuf:"bytes,3,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	// BUILD_OUTPUT_KIND_CONTAINER_IMAGE: the local tag and its digest. The digest goes
	// into the workload's spec so the running container is provably the built one.
	ImageRef    string `protobuf:"bytes,4,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	ImageDigest string `protobuf:"bytes,5,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// What was actually built, which for a branch build is not knowable in advance. Shown
	// next to the deployment and used to skip a rebuild of the same commit.
	Commit string `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
	// Commit subject line, so a deployment list reads like a history instead of a column
	// of hashes.
	CommitMessage string                 `protobuf:"bytes,7,opt,name=commit_message,json=commitMessage,proto3" json:"commit_message,omitempty"`
	ArtifactBytes int64                  `protobuf:"varint,8,opt,name=artifact_bytes,json=artifactBytes,proto3" json:"artifact_bytes,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// Where it stopped, and the last thing the process said. The full output is in the
	// log stream; this is what fits in a notification.
	FailedStage BuildStage `protobuf:"varint,11,opt,name=failed_stage,json=failedStage,proto3,enum=wisper.v1.BuildStage" json:"failed_stage,omitempty"`
	ExitCode    int32      `protobuf:"varint,12,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Detail      string     `protobuf:"bytes,13,opt,name=detail,proto3" json:"detail,omitempty"`
	// Releases the node deleted afterwards to honour RetentionPolicy.keep_releases, so
	// the panel can drop the rows for releases that can no longer be rolled back to.
	PrunedReleases []string `protobuf:"bytes,14,rep,name=pruned_releases,json=prunedReleases,proto3" json:"pruned_releases,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildCompleted) Reset() {
	*x = BuildCompleted{}
	mi := &file_wisper_v1_build_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCompleted) ProtoMessage() {}

func (x *BuildCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_build_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCompleted.ProtoReflect.Descriptor instead.
func (*BuildCompleted) Descriptor() ([]byte, []int) {
	return file_wisper_v1_build_proto_rawDescGZIP(), []int{5}
}

func (x *BuildCompleted) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildCompleted) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *BuildCompleted) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *BuildCompleted) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *BuildCompleted) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *BuildCompleted) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *BuildCompleted) GetArtifactBytes() int64 {
	if x != nil {
		return x.ArtifactBytes
	}
	return 0
}

func (x *BuildCompleted) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *BuildCompleted) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *BuildCompleted) GetFailedStage() BuildStage {
	if x != nil {
		return x.FailedStage
	}
	return BuildStage_BUILD_STAGE_UNSPECIFIED
}

func (x *BuildCompleted) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *BuildCompleted) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *BuildCompleted) GetPrunedReleases() []string {
	if x != nil {
		return x.PrunedReleases
	}
	return nil
}

var File_wisper_v1_build_proto protoreflect.FileDescriptor

const file_wisper_v1_build_proto_rawDesc = "" +
	"\n" +
	"\x15wisper/v1/build.proto\x12\twisper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18wisper/v1/workload.proto\"w\n" +
	"\vBuildSource\x12(\n" +
	"\x03git\x18\x01 \x01(\v2\x14.wisper.v1.GitSourceH\x00R\x03git\x124\n" +
	"\aarchive\x18\x02 \x01(\v2\x18.wisper.v1.ArchiveSourceH\x00R\aarchiveB\b\n" +
	"\x06source\"\xd9\x01\n" +
	"\tGitSource\x12%\n" +
	"\x0erepository_url\x18\x01 \x01(\tR\rrepositoryUrl\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12\x1e\n" +
	"\n" +
	"submodules\x18\x05 \x01(\bR\n" +
	"submodules\x12!\n" +
	"\faccess_token\x18\x06 \x01(\tR\vaccessToken\x12\"\n" +
	"\fsubdirectory\x18\a \x01(\tR\fsubdirectory\"w\n" +
	"\rArchiveSource\x12*\n" +
	"\x11upload_session_id\x18\x01 \x01(\tR\x0fuploadSessionId\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\"\n" +
	"\fsubdirectory\x18\x03 \x01(\tR\fsubdirectory\"\xa7\x02\n" +
	"\tBuildPlan\x12.\n" +
	"\x06preset\x18\x01 \x01(\x0e2\x16.wisper.v1.BuildPresetR\x06preset\x12#\n" +
	"\rbuilder_image\x18\x02 \x01(\tR\fbuilderImage\x12'\n" +
	"\x0finstall_command\x18\x03 \x03(\tR\x0einstallCommand\x12#\n" +
	"\rbuild_command\x18\x04 \x03(\tR\fbuildCommand\x12)\n" +
	"\x10output_directory\x18\x05 \x01(\tR\x0foutputDirectory\x12'\n" +
	"\x0fdockerfile_path\x18\x06 \x01(\tR\x0edockerfilePath\x12#\n" +
	"\rbuild_context\x18\a \x01(\tR\fbuildContext\"\xa3\x03\n" +
	"\n" +
	"StartBuild\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\x12.\n" +
	"\x06source\x18\x03 \x01(\v2\x16.wisper.v1.BuildSourceR\x06source\x12(\n" +
	"\x04plan\x18\x04 \x01(\v2\x14.wisper.v1.BuildPlanR\x04plan\x122\n" +
	"\x06output\x18\x05 \x01(\x0e2\x1a.wisper.v1.BuildOutputKindR\x06output\x12.\n" +
	"\tbuild_env\x18\x06 \x03(\v2\x11.wisper.v1.EnvVarR\bbuildEnv\x121\n" +
	"\x06limits\x18\a \x01(\v2\x19.wisper.v1.ResourceLimitsR\x06limits\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x03R\x0etimeoutSeconds\x12\"\n" +
	"\rlog_stream_id\x18\t \x01(\tR\vlogStreamId\x12\x1b\n" +
	"\tuse_cache\x18\n" +
	" \x01(\bR\buseCache\"\x9a\x04\n" +
	"\x0eBuildCompleted\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"release_id\x18\x03 \x01(\tR\treleaseId\x12\x1b\n" +
	"\timage_ref\x18\x04 \x01(\tR\bimageRef\x12!\n" +
	"\fimage_digest\x18\x05 \x01(\tR\vimageDigest\x12\x16\n" +
	"\x06commit\x18\x06 \x01(\tR\x06commit\x12%\n" +
	"\x0ecommit_message\x18\a \x01(\tR\rcommitMessage\x12%\n" +
	"\x0eartifact_bytes\x18\b \x01(\x03R\rartifactBytes\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x128\n" +
	"\ffailed_stage\x18\v \x01(\x0e2\x15.wisper.v1.BuildStageR\vfailedStage\x12\x1b\n" +
	"\texit_code\x18\f \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06detail\x18\r \x01(\tR\x06detail\x12'\n" +
	"\x0fpruned_releases\x18\x0e \x03(\tR\x0eprunedReleases*\xa7\x01\n" +
	"\vBuildPreset\x12\x1c\n" +
	"\x18BUILD_PRESET_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13BUILD_PRESET_STATIC\x10\x01\x12\x15\n" +
	"\x11BUILD_PRESET_NODE\x10\x02\x12\x15\n" +
	"\x11BUILD_PRESET_HUGO\x10\x03\x12\x16\n" +
	"\x12BUILD_PRESET_ASTRO\x10\x04\x12\x1b\n" +
	"\x17BUILD_PRESET_DOCKERFILE\x10\x05*\x81\x01\n" +
	"\x0fBuildOutputKind\x12!\n" +
	"\x1dBUILD_OUTPUT_KIND_UNSPECIFIED\x10\x00\x12$\n" +
	" BUILD_OUTPUT_KIND_STATIC_RELEASE\x10\x01\x12%\n" +
	"!BUILD_OUTPUT_KIND_CONTAINER_IMAGE\x10\x02*\x89\x01\n" +
	"\n" +
	"BuildStage\x12\x1b\n" +
	"\x17BUILD_STAGE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BUILD_STAGE_FETCH\x10\x01\x12\x17\n" +
	"\x13BUILD_STAGE_INSTALL\x10\x02\x12\x15\n" +
	"\x11BUILD_STAGE_BUILD\x10\x03\x12\x17\n" +
	"\x13BUILD_STAGE_PUBLISH\x10\x04Bk\n" +
	"\x1clhqm.furimeo.wisper.proto.v1B\n" +
	"BuildProtoP\x01Z=github.com/furimeo/wisper/sasayaki/internal/wisperpb;wisperpbb\x06proto3"

var (
	file_wisper_v1_build_proto_rawDescOnce sync.Once
	file_wisper_v1_build_proto_rawDescData []byte
)

func file_wisper_v1_build_proto_rawDescGZIP() []byte {
	file_wisper_v1_build_proto_rawDescOnce.Do(func() {
		file_wisper_v1_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wisper_v1_build_proto_rawDesc), len(file_wisper_v1_build_proto_rawDesc)))
	})
	return file_wisper_v1_build_proto_rawDescData
}

var file_wisper_v1_build_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wisper_v1_build_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wisper_v1_build_proto_goTypes = []any{
	(BuildPreset)(0),              // 0: wisper.v1.BuildPreset
	(BuildOutputKind)(0),          // 1: wisper.v1.BuildOutputKind
	(BuildStage)(0),               // 2: wisper.v1.BuildStage
	(*BuildSource)(nil),           // 3: wisper.v1.BuildSource
	(*GitSource)(nil),             // 4: wisper.v1.GitSource
	(*ArchiveSource)(nil),         // 5: wisper.v1.ArchiveSource
	(*BuildPlan)(nil),             // 6: wisper.v1.BuildPlan
	(*StartBuild)(nil),            // 7: wisper.v1.StartBuild
	(*BuildCompleted)(nil),        // 8: wisper.v1.BuildCompleted
	(*EnvVar)(nil),                // 9: wisper.v1.EnvVar
	(*ResourceLimits)(nil),        // 10: wisper.v1.ResourceLimits
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_wisper_v1_build_proto_depIdxs = []int32{
	4,  // 0: wisper.v1.BuildSource.git:type_name -> wisper.v1.GitSource
	5,  // 1: wisper.v1.BuildSource.archive:type_name -> wisper.v1.ArchiveSource
	0,  // 2: wisper.v1.BuildPlan.preset:type_name -> wisper.v1.BuildPreset
	3,  // 3: wisper.v1.StartBuild.source:type_name -> wisper.v1.BuildSource
	6,  // 4: wisper.v1.StartBuild.plan:type_name -> wisper.v1.BuildPlan
	1,  // 5: wisper.v1.StartBuild.output:type_name -> wisper.v1.BuildOutputKind
	9,  // 6: wisper.v1.StartBuild.build_env:type_name -> wisper.v1.EnvVar
	10, // 7: wisper.v1.StartBuild.limits:type_name -> wisper.v1.ResourceLimits
	11, // 8: wisper.v1.BuildCompleted.started_at:type_name -> google.protobuf.Timestamp
	11, // 9: wisper.v1.BuildCompleted.finished_at:type_name -> google.protobuf.Timestamp
	2,  // 10: wisper.v1.BuildCompleted.failed_stage:type_name -> wisper.v1.BuildStage
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wisper_v1_build_proto_init() }
func file_wisper_v1_build_proto_init() {
	if File_wisper_v1_build_proto != nil {
		return
	}
	file_wisper_v1_workload_proto_init()
	file_wisper_v1_build_proto_msgTypes[0].OneofWrappers = []any{
		(*BuildSource_Git)(nil),
		(*BuildSource_Archive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wisper_v1_build_proto_rawDesc), len(file_wisper_v1_build_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wisper_v1_build_proto_goTypes,
		DependencyIndexes: file_wisper_v1_build_proto_depIdxs,
		EnumInfos:         file_wisper_v1_build_proto_enumTypes,
		MessageInfos:      file_wisper_v1_build_proto_msgTypes,
	}.Build()
	File_wisper_v1_build_proto = out.File
	file_wisper_v1_build_proto_goTypes = nil
	file_wisper_v1_build_proto_depIdxs = nil
}
