// Managed databases: the shared engine containers a node runs, the per-customer
// database and user carved out of one, and the commands that create, re-key and drop
// them.
//
// Shared engines rather than a container per customer because an idle PostgreSQL costs
// 30-50 MB of RSS and a node hosts hundreds of customers; a few hundred private
// instances is the whole machine (design section 8.1). A customer who pays for
// isolation gets `dedicated_instance` and their own container instead of a schema in
// the shared one.
//
// This file imports nothing from wisper.v1 on purpose: workload.proto imports it so a
// NodeSpec can carry the grants, and protobuf has no import cycles.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wisper/v1/database.proto

package wisperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Which engine. The two are not interchangeable anywhere - the dump format, the SQL
// that creates a user and the connection URI scheme all differ - so every message that
// touches a database carries it rather than inferring it from a port or an image name.
type DatabaseEngine int32

const (
	DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED DatabaseEngine = 0
	DatabaseEngine_DATABASE_ENGINE_POSTGRES    DatabaseEngine = 1
	DatabaseEngine_DATABASE_ENGINE_MYSQL       DatabaseEngine = 2
)

// Enum value maps for DatabaseEngine.
var (
	DatabaseEngine_name = map[int32]string{
		0: "DATABASE_ENGINE_UNSPECIFIED",
		1: "DATABASE_ENGINE_POSTGRES",
		2: "DATABASE_ENGINE_MYSQL",
	}
	DatabaseEngine_value = map[string]int32{
		"DATABASE_ENGINE_UNSPECIFIED": 0,
		"DATABASE_ENGINE_POSTGRES":    1,
		"DATABASE_ENGINE_MYSQL":       2,
	}
)

func (x DatabaseEngine) Enum() *DatabaseEngine {
	p := new(DatabaseEngine)
	*p = x
	return p
}

func (x DatabaseEngine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseEngine) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_database_proto_enumTypes[0].Descriptor()
}

func (DatabaseEngine) Type() protoreflect.EnumType {
	return &file_wisper_v1_database_proto_enumTypes[0]
}

func (x DatabaseEngine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatabaseEngine.Descriptor instead.
func (DatabaseEngine) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_database_proto_rawDescGZIP(), []int{0}
}

// A shared engine container the node must be running, exactly one per engine per node.
//
// It is part of the NodeSpec rather than something the daemon decides for itself
// because the panel owns intent: two nodes quietly running different major versions is
// a backup that restores everywhere except the node it is needed on.
type DatabaseEngineSpec struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Engine DatabaseEngine         `protobuf:"varint,1,opt,name=engine,proto3,enum=wisper.v1.DatabaseEngine" json:"engine,omitempty"`
	// Pinned by the panel, digest or tag. The node never picks a version.
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Published on the node's private interface only. Customers reach it through the
	// connection string the panel shows them; it is never on the public address.
	ListenPort uint32 `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// The superuser the node uses to create databases and roles. The panel generates the
	// password so it can display and rotate it; a secret the node invents is a secret the
	// panel cannot show the customer or put in a backup job.
	AdminUsername string `protobuf:"bytes,4,opt,name=admin_username,json=adminUsername,proto3" json:"admin_username,omitempty"`
	AdminPassword string `protobuf:"bytes,5,opt,name=admin_password,json=adminPassword,proto3" json:"admin_password,omitempty"`
	// Where the engine's data directory lives, as a volume id the node resolves under its
	// state directory. Named so a node rebuild keeps customer data.
	DataVolumeId string `protobuf:"bytes,6,opt,name=data_volume_id,json=dataVolumeId,proto3" json:"data_volume_id,omitempty"`
	// Deliberately two integers instead of workload.ResourceLimits: workload.proto
	// imports this file, so this file cannot import workload.proto. Duplicating the two
	// fields the engine actually needs is cheaper than moving NodeSpec around to break
	// the cycle.
	NanoCpus    int64 `protobuf:"varint,7,opt,name=nano_cpus,json=nanoCpus,proto3" json:"nano_cpus,omitempty"`
	MemoryBytes int64 `protobuf:"varint,8,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// Connection ceiling for the whole shared engine. Without it one customer's leaking
	// pool locks every other customer out of the same container.
	MaxConnections int32 `protobuf:"varint,9,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DatabaseEngineSpec) Reset() {
	*x = DatabaseEngineSpec{}
	mi := &file_wisper_v1_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseEngineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseEngineSpec) ProtoMessage() {}

func (x *DatabaseEngineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseEngineSpec.ProtoReflect.Descriptor instead.
func (*DatabaseEngineSpec) Descriptor() ([]byte, []int) {
	return file_wisper_v1_database_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseEngineSpec) GetEngine() DatabaseEngine {
	if x != nil {
		return x.Engine
	}
	return DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED
}

func (x *DatabaseEngineSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DatabaseEngineSpec) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *DatabaseEngineSpec) GetAdminUsername() string {
	if x != nil {
		return x.AdminUsername
	}
	return ""
}

func (x *DatabaseEngineSpec) GetAdminPassword() string {
	if x != nil {
		return x.AdminPassword
	}
	return ""
}

func (x *DatabaseEngineSpec) GetDataVolumeId() string {
	if x != nil {
		return x.DataVolumeId
	}
	return ""
}

func (x *DatabaseEngineSpec) GetNanoCpus() int64 {
	if x != nil {
		return x.NanoCpus
	}
	return 0
}

func (x *DatabaseEngineSpec) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *DatabaseEngineSpec) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

// One customer's database and login on a shared engine. Part of the NodeSpec, so a
// daemon that lost its disk recreates the account rather than leaving an application
// unable to log in.
type DatabaseGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The panel's id for this grant, stable across renames of the database itself.
	Id           string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Engine       DatabaseEngine `protobuf:"varint,2,opt,name=engine,proto3,enum=wisper.v1.DatabaseEngine" json:"engine,omitempty"`
	DatabaseName string         `protobuf:"bytes,3,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Username     string         `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// Storage ceiling in bytes, enforced by measurement and reported back: neither engine
	// has a hard per-database quota, so the panel gets `over_quota` and decides what to do
	// rather than the node silently dropping writes.
	QuotaBytes int64 `protobuf:"varint,5,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	// The paid escape hatch from the shared engine (design section 8.1). The node runs a
	// private container for this grant instead of a role in the shared one.
	DedicatedInstance bool `protobuf:"varint,6,opt,name=dedicated_instance,json=dedicatedInstance,proto3" json:"dedicated_instance,omitempty"`
	// PostgreSQL encoding / MySQL character set. Empty means the engine default; it is
	// here because changing it after a customer has data means a dump and reload.
	Encoding      string `protobuf:"bytes,7,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseGrant) Reset() {
	*x = DatabaseGrant{}
	mi := &file_wisper_v1_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseGrant) ProtoMessage() {}

func (x *DatabaseGrant) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseGrant.ProtoReflect.Descriptor instead.
func (*DatabaseGrant) Descriptor() ([]byte, []int) {
	return file_wisper_v1_database_proto_rawDescGZIP(), []int{1}
}

func (x *DatabaseGrant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatabaseGrant) GetEngine() DatabaseEngine {
	if x != nil {
		return x.Engine
	}
	return DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED
}

func (x *DatabaseGrant) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DatabaseGrant) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DatabaseGrant) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *DatabaseGrant) GetDedicatedInstance() bool {
	if x != nil {
		return x.DedicatedInstance
	}
	return false
}

func (x *DatabaseGrant) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

// Create the database, the role and the grant, now.
//
// A command rather than pure reconciliation because the customer is waiting on a
// screen for a connection string, and because the password must reach the panel in the
// reply that answers this one request.
type ProvisionDatabase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Grant *DatabaseGrant         `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	// Generated by the panel, which stores it encrypted and shows it once. The node
	// applies it and never keeps a copy outside the engine.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionDatabase) Reset() {
	*x = ProvisionDatabase{}
	mi := &file_wisper_v1_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionDatabase) ProtoMessage() {}

func (x *ProvisionDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionDatabase.ProtoReflect.Descriptor instead.
func (*ProvisionDatabase) Descriptor() ([]byte, []int) {
	return file_wisper_v1_database_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionDatabase) GetGrant() *DatabaseGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *ProvisionDatabase) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// What the panel needs to render a connection string, and nothing else: the password
// came from the panel in the first place, so sending it back would put a secret on the
// wire twice for no gain.
type DatabaseProvisioned struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Engine DatabaseEngine         `protobuf:"varint,2,opt,name=engine,proto3,enum=wisper.v1.DatabaseEngine" json:"engine,omitempty"`
	// The address a customer's workload uses. The node fills in the address that works
	// from inside its own network, which is not necessarily the node's public one.
	Host         string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port         uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	DatabaseName string `protobuf:"bytes,5,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Username     string `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	// Reported so the panel can warn before a dump lands on an engine that cannot read
	// it. "PostgreSQL 17.2", "8.4.3".
	EngineVersion string `protobuf:"bytes,7,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseProvisioned) Reset() {
	*x = DatabaseProvisioned{}
	mi := &file_wisper_v1_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseProvisioned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseProvisioned) ProtoMessage() {}

func (x *DatabaseProvisioned) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseProvisioned.ProtoReflect.Descriptor instead.
func (*DatabaseProvisioned) Descriptor() ([]byte, []int) {
	return file_wisper_v1_database_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseProvisioned) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatabaseProvisioned) GetEngine() DatabaseEngine {
	if x != nil {
		return x.Engine
	}
	return DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED
}

func (x *DatabaseProvisioned) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseProvisioned) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DatabaseProvisioned) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DatabaseProvisioned) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DatabaseProvisioned) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

// Change one login's password. The customer pressed "rotate" (design section 8.1), or
// an operator is revoking a leaked credential.
type RotateDatabasePassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Engine        DatabaseEngine         `protobuf:"varint,3,opt,name=engine,proto3,enum=wisper.v1.DatabaseEngine" json:"engine,omitempty"`
	NewPassword   string                 `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateDatabasePassword) Reset() {
	*x = RotateDatabasePassword{}
	mi := &file_wisper_v1_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateDatabasePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateDatabasePassword) ProtoMessage() {}

func (x *RotateDatabasePassword) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateDatabasePassword.ProtoReflect.Descriptor instead.
func (*RotateDatabasePassword) Descriptor() ([]byte, []int) {
	return file_wisper_v1_database_proto_rawDescGZIP(), []int{4}
}

func (x *RotateDatabasePassword) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RotateDatabasePassword) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RotateDatabasePassword) GetEngine() DatabaseEngine {
	if x != nil {
		return x.Engine
	}
	return DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED
}

func (x *RotateDatabasePassword) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// Remove a database and its login.
//
// `drop_data` is explicit rather than implied because dropping the role and leaving the
// data is a real operation - it locks an application out while an operator investigates
// - and because a destructive default is how customer data disappears.
type DropDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Engine        DatabaseEngine         `protobuf:"varint,2,opt,name=engine,proto3,enum=wisper.v1.DatabaseEngine" json:"engine,omitempty"`
	DatabaseName  string                 `protobuf:"bytes,3,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	DropData      bool                   `protobuf:"varint,5,opt,name=drop_data,json=dropData,proto3" json:"drop_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatabase) Reset() {
	*x = DropDatabase{}
	mi := &file_wisper_v1_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatabase) ProtoMessage() {}

func (x *DropDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatabase.ProtoReflect.Descriptor instead.
func (*DropDatabase) Descriptor() ([]byte, []int) {
	return file_wisper_v1_database_proto_rawDescGZIP(), []int{5}
}

func (x *DropDatabase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DropDatabase) GetEngine() DatabaseEngine {
	if x != nil {
		return x.Engine
	}
	return DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED
}

func (x *DropDatabase) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DropDatabase) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DropDatabase) GetDropData() bool {
	if x != nil {
		return x.DropData
	}
	return false
}

// Measured fact about one grant, reported in every status batch. The panel owns the
// quota; the node owns the size.
type DatabaseStatus struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Engine DatabaseEngine         `protobuf:"varint,2,opt,name=engine,proto3,enum=wisper.v1.DatabaseEngine" json:"engine,omitempty"`
	// False after a restore that has not finished, or when the engine container is down.
	// The panel shows "unavailable" rather than "deleted": not seeing something is not
	// the same as it not existing.
	Exists     bool  `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	SizeBytes  int64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	QuotaBytes int64 `protobuf:"varint,5,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	// Computed by the node so the panel does not have to re-derive the same comparison in
	// three screens, and so the threshold can move with the engine's own accounting.
	OverQuota     bool                   `protobuf:"varint,6,opt,name=over_quota,json=overQuota,proto3" json:"over_quota,omitempty"`
	EngineVersion string                 `protobuf:"bytes,7,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	MeasuredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	// Why the last provision, rotate or size query failed. Empty when it did not.
	LastError     string `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseStatus) Reset() {
	*x = DatabaseStatus{}
	mi := &file_wisper_v1_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseStatus) ProtoMessage() {}

func (x *DatabaseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseStatus.ProtoReflect.Descriptor instead.
func (*DatabaseStatus) Descriptor() ([]byte, []int) {
	return file_wisper_v1_database_proto_rawDescGZIP(), []int{6}
}

func (x *DatabaseStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatabaseStatus) GetEngine() DatabaseEngine {
	if x != nil {
		return x.Engine
	}
	return DatabaseEngine_DATABASE_ENGINE_UNSPECIFIED
}

func (x *DatabaseStatus) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *DatabaseStatus) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DatabaseStatus) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *DatabaseStatus) GetOverQuota() bool {
	if x != nil {
		return x.OverQuota
	}
	return false
}

func (x *DatabaseStatus) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *DatabaseStatus) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *DatabaseStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_wisper_v1_database_proto protoreflect.FileDescriptor

const file_wisper_v1_database_proto_rawDesc = "" +
	"\n" +
	"\x18wisper/v1/database.proto\x12\twisper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\x12DatabaseEngineSpec\x121\n" +
	"\x06engine\x18\x01 \x01(\x0e2\x19.wisper.v1.DatabaseEngineR\x06engine\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\rR\n" +
	"listenPort\x12%\n" +
	"\x0eadmin_username\x18\x04 \x01(\tR\radminUsername\x12%\n" +
	"\x0eadmin_password\x18\x05 \x01(\tR\radminPassword\x12$\n" +
	"\x0edata_volume_id\x18\x06 \x01(\tR\fdataVolumeId\x12\x1b\n" +
	"\tnano_cpus\x18\a \x01(\x03R\bnanoCpus\x12!\n" +
	"\fmemory_bytes\x18\b \x01(\x03R\vmemoryBytes\x12'\n" +
	"\x0fmax_connections\x18\t \x01(\x05R\x0emaxConnections\"\xff\x01\n" +
	"\rDatabaseGrant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x06engine\x18\x02 \x01(\x0e2\x19.wisper.v1.DatabaseEngineR\x06engine\x12#\n" +
	"\rdatabase_name\x18\x03 \x01(\tR\fdatabaseName\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1f\n" +
	"\vquota_bytes\x18\x05 \x01(\x03R\n" +
	"quotaBytes\x12-\n" +
	"\x12dedicated_instance\x18\x06 \x01(\bR\x11dedicatedInstance\x12\x1a\n" +
	"\bencoding\x18\a \x01(\tR\bencoding\"_\n" +
	"\x11ProvisionDatabase\x12.\n" +
	"\x05grant\x18\x01 \x01(\v2\x18.wisper.v1.DatabaseGrantR\x05grant\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xe8\x01\n" +
	"\x13DatabaseProvisioned\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x06engine\x18\x02 \x01(\x0e2\x19.wisper.v1.DatabaseEngineR\x06engine\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12#\n" +
	"\rdatabase_name\x18\x05 \x01(\tR\fdatabaseName\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12%\n" +
	"\x0eengine_version\x18\a \x01(\tR\rengineVersion\"\x9a\x01\n" +
	"\x16RotateDatabasePassword\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x121\n" +
	"\x06engine\x18\x03 \x01(\x0e2\x19.wisper.v1.DatabaseEngineR\x06engine\x12!\n" +
	"\fnew_password\x18\x04 \x01(\tR\vnewPassword\"\xaf\x01\n" +
	"\fDropDatabase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x06engine\x18\x02 \x01(\x0e2\x19.wisper.v1.DatabaseEngineR\x06engine\x12#\n" +
	"\rdatabase_name\x18\x03 \x01(\tR\fdatabaseName\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1b\n" +
	"\tdrop_data\x18\x05 \x01(\bR\bdropData\"\xcd\x02\n" +
	"\x0eDatabaseStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x06engine\x18\x02 \x01(\x0e2\x19.wisper.v1.DatabaseEngineR\x06engine\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vquota_bytes\x18\x05 \x01(\x03R\n" +
	"quotaBytes\x12\x1d\n" +
	"\n" +
	"over_quota\x18\x06 \x01(\bR\toverQuota\x12%\n" +
	"\x0eengine_version\x18\a \x01(\tR\rengineVersion\x12;\n" +
	"\vmeasured_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"measuredAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError*j\n" +
	"\x0eDatabaseEngine\x12\x1f\n" +
	"\x1bDATABASE_ENGINE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DATABASE_ENGINE_POSTGRES\x10\x01\x12\x19\n" +
	"\x15DATABASE_ENGINE_MYSQL\x10\x02Bn\n" +
	"\x1clhqm.furimeo.wisper.proto.v1B\rDatabaseProtoP\x01Z=github.com/furimeo/wisper/sasayaki/internal/wisperpb;wisperpbb\x06proto3"

var (
	file_wisper_v1_database_proto_rawDescOnce sync.Once
	file_wisper_v1_database_proto_rawDescData []byte
)

func file_wisper_v1_database_proto_rawDescGZIP() []byte {
	file_wisper_v1_database_proto_rawDescOnce.Do(func() {
		file_wisper_v1_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wisper_v1_database_proto_rawDesc), len(file_wisper_v1_database_proto_rawDesc)))
	})
	return file_wisper_v1_database_proto_rawDescData
}

var file_wisper_v1_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wisper_v1_database_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wisper_v1_database_proto_goTypes = []any{
	(DatabaseEngine)(0),            // 0: wisper.v1.DatabaseEngine
	(*DatabaseEngineSpec)(nil),     // 1: wisper.v1.DatabaseEngineSpec
	(*DatabaseGrant)(nil),          // 2: wisper.v1.DatabaseGrant
	(*ProvisionDatabase)(nil),      // 3: wisper.v1.ProvisionDatabase
	(*DatabaseProvisioned)(nil),    // 4: wisper.v1.DatabaseProvisioned
	(*RotateDatabasePassword)(nil), // 5: wisper.v1.RotateDatabasePassword
	(*DropDatabase)(nil),           // 6: wisper.v1.DropDatabase
	(*DatabaseStatus)(nil),         // 7: wisper.v1.DatabaseStatus
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_wisper_v1_database_proto_depIdxs = []int32{
	0, // 0: wisper.v1.DatabaseEngineSpec.engine:type_name -> wisper.v1.DatabaseEngine
	0, // 1: wisper.v1.DatabaseGrant.engine:type_name -> wisper.v1.DatabaseEngine
	2, // 2: wisper.v1.ProvisionDatabase.grant:type_name -> wisper.v1.DatabaseGrant
	0, // 3: wisper.v1.DatabaseProvisioned.engine:type_name -> wisper.v1.DatabaseEngine
	0, // 4: wisper.v1.RotateDatabasePassword.engine:type_name -> wisper.v1.DatabaseEngine
	0, // 5: wisper.v1.DropDatabase.engine:type_name -> wisper.v1.DatabaseEngine
	0, // 6: wisper.v1.DatabaseStatus.engine:type_name -> wisper.v1.DatabaseEngine
	8, // 7: wisper.v1.DatabaseStatus.measured_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_wisper_v1_database_proto_init() }
func file_wisper_v1_database_proto_init() {
	if File_wisper_v1_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wisper_v1_database_proto_rawDesc), len(file_wisper_v1_database_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wisper_v1_database_proto_goTypes,
		DependencyIndexes: file_wisper_v1_database_proto_depIdxs,
		EnumInfos:         file_wisper_v1_database_proto_enumTypes,
		MessageInfos:      file_wisper_v1_database_proto_msgTypes,
	}.Build()
	File_wisper_v1_database_proto = out.File
	file_wisper_v1_database_proto_goTypes = nil
	file_wisper_v1_database_proto_depIdxs = nil
}
