// The web file manager: the only way a customer touches their disk.
//
// There is no SSH, no SFTP and no WebDAV in wisper, so this contract has to be good
// enough to replace all three (design section 8.2). Two properties shape everything
// below.
//
// First, paths. Every operation names a FileRoot by id and a path relative to it. The
// panel never learns and never sends an absolute path on the node; the node resolves
// the root and rejects anything that escapes it. Path traversal is the largest attack
// surface in v1, so there is exactly one place to check it and one error code for it.
//
// Second, mobile. Most customers upload from a phone on mobile data, so an upload is a
// series of acknowledged chunks against a session that survives losing signal, not one
// enormous request that has to start again. The resume query answers with the ranges
// already on disk, and the browser continues from the first gap.
//
// Direction: the node opens the FileOp stream because it is the only side that can dial.
// The panel then drives it - FileRequest travels down to the node, FileEvent comes back
// up - which is why the RPC's request type is the answer type and not the other way
// round.
//
// Over 300 lines, and one vocabulary: splitting the upload half from the browsing half
// would put the shared chunk, the shared paths and the shared error codes in a third
// file that neither of the other two owns.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wisper/v1/files.proto

package wisperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArchiveFormat int32

const (
	ArchiveFormat_ARCHIVE_FORMAT_UNSPECIFIED ArchiveFormat = 0
	ArchiveFormat_ARCHIVE_FORMAT_ZIP         ArchiveFormat = 1
	ArchiveFormat_ARCHIVE_FORMAT_TAR_GZ      ArchiveFormat = 2
)

// Enum value maps for ArchiveFormat.
var (
	ArchiveFormat_name = map[int32]string{
		0: "ARCHIVE_FORMAT_UNSPECIFIED",
		1: "ARCHIVE_FORMAT_ZIP",
		2: "ARCHIVE_FORMAT_TAR_GZ",
	}
	ArchiveFormat_value = map[string]int32{
		"ARCHIVE_FORMAT_UNSPECIFIED": 0,
		"ARCHIVE_FORMAT_ZIP":         1,
		"ARCHIVE_FORMAT_TAR_GZ":      2,
	}
)

func (x ArchiveFormat) Enum() *ArchiveFormat {
	p := new(ArchiveFormat)
	*p = x
	return p
}

func (x ArchiveFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArchiveFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_files_proto_enumTypes[0].Descriptor()
}

func (ArchiveFormat) Type() protoreflect.EnumType {
	return &file_wisper_v1_files_proto_enumTypes[0]
}

func (x ArchiveFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArchiveFormat.Descriptor instead.
func (ArchiveFormat) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{0}
}

type FileErrorCode int32

const (
	FileErrorCode_FILE_ERROR_CODE_UNSPECIFIED       FileErrorCode = 0
	FileErrorCode_FILE_ERROR_CODE_NOT_FOUND         FileErrorCode = 1
	FileErrorCode_FILE_ERROR_CODE_ALREADY_EXISTS    FileErrorCode = 2
	FileErrorCode_FILE_ERROR_CODE_PERMISSION_DENIED FileErrorCode = 3
	// The resolved path left its root, or an archive entry tried to. Its own code because
	// it is never a customer mistake worth explaining - it is an attack or a bug, and the
	// panel records it in the audit log rather than showing a friendly hint.
	FileErrorCode_FILE_ERROR_CODE_PATH_ESCAPES_ROOT   FileErrorCode = 4
	FileErrorCode_FILE_ERROR_CODE_NOT_A_DIRECTORY     FileErrorCode = 5
	FileErrorCode_FILE_ERROR_CODE_IS_A_DIRECTORY      FileErrorCode = 6
	FileErrorCode_FILE_ERROR_CODE_DIRECTORY_NOT_EMPTY FileErrorCode = 7
	FileErrorCode_FILE_ERROR_CODE_QUOTA_EXCEEDED      FileErrorCode = 8
	FileErrorCode_FILE_ERROR_CODE_TOO_LARGE           FileErrorCode = 9
	// A chunk or a completed file did not match its SHA-256.
	FileErrorCode_FILE_ERROR_CODE_CHECKSUM_MISMATCH FileErrorCode = 10
	// The session was swept, never existed, or belongs to another root.
	FileErrorCode_FILE_ERROR_CODE_UNKNOWN_SESSION     FileErrorCode = 11
	FileErrorCode_FILE_ERROR_CODE_UNSUPPORTED_ARCHIVE FileErrorCode = 12
	// The root id is not in the current NodeSpec.
	FileErrorCode_FILE_ERROR_CODE_UNKNOWN_ROOT FileErrorCode = 13
	FileErrorCode_FILE_ERROR_CODE_CANCELLED    FileErrorCode = 14
	// Anything the node could not classify, with the underlying message in `detail`.
	FileErrorCode_FILE_ERROR_CODE_IO_ERROR FileErrorCode = 15
)

// Enum value maps for FileErrorCode.
var (
	FileErrorCode_name = map[int32]string{
		0:  "FILE_ERROR_CODE_UNSPECIFIED",
		1:  "FILE_ERROR_CODE_NOT_FOUND",
		2:  "FILE_ERROR_CODE_ALREADY_EXISTS",
		3:  "FILE_ERROR_CODE_PERMISSION_DENIED",
		4:  "FILE_ERROR_CODE_PATH_ESCAPES_ROOT",
		5:  "FILE_ERROR_CODE_NOT_A_DIRECTORY",
		6:  "FILE_ERROR_CODE_IS_A_DIRECTORY",
		7:  "FILE_ERROR_CODE_DIRECTORY_NOT_EMPTY",
		8:  "FILE_ERROR_CODE_QUOTA_EXCEEDED",
		9:  "FILE_ERROR_CODE_TOO_LARGE",
		10: "FILE_ERROR_CODE_CHECKSUM_MISMATCH",
		11: "FILE_ERROR_CODE_UNKNOWN_SESSION",
		12: "FILE_ERROR_CODE_UNSUPPORTED_ARCHIVE",
		13: "FILE_ERROR_CODE_UNKNOWN_ROOT",
		14: "FILE_ERROR_CODE_CANCELLED",
		15: "FILE_ERROR_CODE_IO_ERROR",
	}
	FileErrorCode_value = map[string]int32{
		"FILE_ERROR_CODE_UNSPECIFIED":         0,
		"FILE_ERROR_CODE_NOT_FOUND":           1,
		"FILE_ERROR_CODE_ALREADY_EXISTS":      2,
		"FILE_ERROR_CODE_PERMISSION_DENIED":   3,
		"FILE_ERROR_CODE_PATH_ESCAPES_ROOT":   4,
		"FILE_ERROR_CODE_NOT_A_DIRECTORY":     5,
		"FILE_ERROR_CODE_IS_A_DIRECTORY":      6,
		"FILE_ERROR_CODE_DIRECTORY_NOT_EMPTY": 7,
		"FILE_ERROR_CODE_QUOTA_EXCEEDED":      8,
		"FILE_ERROR_CODE_TOO_LARGE":           9,
		"FILE_ERROR_CODE_CHECKSUM_MISMATCH":   10,
		"FILE_ERROR_CODE_UNKNOWN_SESSION":     11,
		"FILE_ERROR_CODE_UNSUPPORTED_ARCHIVE": 12,
		"FILE_ERROR_CODE_UNKNOWN_ROOT":        13,
		"FILE_ERROR_CODE_CANCELLED":           14,
		"FILE_ERROR_CODE_IO_ERROR":            15,
	}
)

func (x FileErrorCode) Enum() *FileErrorCode {
	p := new(FileErrorCode)
	*p = x
	return p
}

func (x FileErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_files_proto_enumTypes[1].Descriptor()
}

func (FileErrorCode) Type() protoreflect.EnumType {
	return &file_wisper_v1_files_proto_enumTypes[1]
}

func (x FileErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileErrorCode.Descriptor instead.
func (FileErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{1}
}

// One operation the panel wants performed, travelling from panel to node.
type FileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates every FileEvent that answers this operation. Unique per node stream;
	// the panel reuses nothing, so a late answer to a cancelled request is discardable
	// rather than confusing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Which FileRoot from the NodeSpec. A root the spec does not list is refused even if
	// the node could reach it.
	RootId string `protobuf:"bytes,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*FileRequest_List
	//	*FileRequest_Stat
	//	*FileRequest_Read
	//	*FileRequest_Write
	//	*FileRequest_Resume
	//	*FileRequest_Complete
	//	*FileRequest_Abort
	//	*FileRequest_CreateDirectory
	//	*FileRequest_Move
	//	*FileRequest_Delete
	//	*FileRequest_ChangeMode
	//	*FileRequest_Archive
	//	*FileRequest_Extract
	//	*FileRequest_Measure
	//	*FileRequest_Cancel
	Op            isFileRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_wisper_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileRequest) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *FileRequest) GetOp() isFileRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *FileRequest) GetList() *ListDirectory {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *FileRequest) GetStat() *StatPath {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *FileRequest) GetRead() *ReadFile {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *FileRequest) GetWrite() *WriteChunk {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *FileRequest) GetResume() *ResumeUpload {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *FileRequest) GetComplete() *CompleteUpload {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *FileRequest) GetAbort() *AbortUpload {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

func (x *FileRequest) GetCreateDirectory() *CreateDirectory {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_CreateDirectory); ok {
			return x.CreateDirectory
		}
	}
	return nil
}

func (x *FileRequest) GetMove() *MovePath {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *FileRequest) GetDelete() *DeletePath {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *FileRequest) GetChangeMode() *ChangeMode {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_ChangeMode); ok {
			return x.ChangeMode
		}
	}
	return nil
}

func (x *FileRequest) GetArchive() *CreateArchive {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Archive); ok {
			return x.Archive
		}
	}
	return nil
}

func (x *FileRequest) GetExtract() *ExtractArchive {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Extract); ok {
			return x.Extract
		}
	}
	return nil
}

func (x *FileRequest) GetMeasure() *MeasureDirectory {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Measure); ok {
			return x.Measure
		}
	}
	return nil
}

func (x *FileRequest) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Op.(*FileRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isFileRequest_Op interface {
	isFileRequest_Op()
}

type FileRequest_List struct {
	List *ListDirectory `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type FileRequest_Stat struct {
	Stat *StatPath `protobuf:"bytes,4,opt,name=stat,proto3,oneof"`
}

type FileRequest_Read struct {
	Read *ReadFile `protobuf:"bytes,5,opt,name=read,proto3,oneof"`
}

type FileRequest_Write struct {
	Write *WriteChunk `protobuf:"bytes,6,opt,name=write,proto3,oneof"`
}

type FileRequest_Resume struct {
	Resume *ResumeUpload `protobuf:"bytes,7,opt,name=resume,proto3,oneof"`
}

type FileRequest_Complete struct {
	Complete *CompleteUpload `protobuf:"bytes,8,opt,name=complete,proto3,oneof"`
}

type FileRequest_Abort struct {
	Abort *AbortUpload `protobuf:"bytes,9,opt,name=abort,proto3,oneof"`
}

type FileRequest_CreateDirectory struct {
	CreateDirectory *CreateDirectory `protobuf:"bytes,10,opt,name=create_directory,json=createDirectory,proto3,oneof"`
}

type FileRequest_Move struct {
	Move *MovePath `protobuf:"bytes,11,opt,name=move,proto3,oneof"`
}

type FileRequest_Delete struct {
	Delete *DeletePath `protobuf:"bytes,12,opt,name=delete,proto3,oneof"`
}

type FileRequest_ChangeMode struct {
	ChangeMode *ChangeMode `protobuf:"bytes,13,opt,name=change_mode,json=changeMode,proto3,oneof"`
}

type FileRequest_Archive struct {
	Archive *CreateArchive `protobuf:"bytes,14,opt,name=archive,proto3,oneof"`
}

type FileRequest_Extract struct {
	Extract *ExtractArchive `protobuf:"bytes,15,opt,name=extract,proto3,oneof"`
}

type FileRequest_Measure struct {
	Measure *MeasureDirectory `protobuf:"bytes,16,opt,name=measure,proto3,oneof"`
}

type FileRequest_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,17,opt,name=cancel,proto3,oneof"`
}

func (*FileRequest_List) isFileRequest_Op() {}

func (*FileRequest_Stat) isFileRequest_Op() {}

func (*FileRequest_Read) isFileRequest_Op() {}

func (*FileRequest_Write) isFileRequest_Op() {}

func (*FileRequest_Resume) isFileRequest_Op() {}

func (*FileRequest_Complete) isFileRequest_Op() {}

func (*FileRequest_Abort) isFileRequest_Op() {}

func (*FileRequest_CreateDirectory) isFileRequest_Op() {}

func (*FileRequest_Move) isFileRequest_Op() {}

func (*FileRequest_Delete) isFileRequest_Op() {}

func (*FileRequest_ChangeMode) isFileRequest_Op() {}

func (*FileRequest_Archive) isFileRequest_Op() {}

func (*FileRequest_Extract) isFileRequest_Op() {}

func (*FileRequest_Measure) isFileRequest_Op() {}

func (*FileRequest_Cancel) isFileRequest_Op() {}

// One answer, travelling from node to panel. Several may answer one request: a download
// is many chunks, a listing is one page.
type FileEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*FileEvent_Listing
	//	*FileEvent_Info
	//	*FileEvent_Chunk
	//	*FileEvent_Ack
	//	*FileEvent_State
	//	*FileEvent_Size
	//	*FileEvent_Done
	//	*FileEvent_Error
	Result        isFileEvent_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	mi := &file_wisper_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *FileEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileEvent) GetResult() isFileEvent_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FileEvent) GetListing() *DirectoryListing {
	if x != nil {
		if x, ok := x.Result.(*FileEvent_Listing); ok {
			return x.Listing
		}
	}
	return nil
}

func (x *FileEvent) GetInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Result.(*FileEvent_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *FileEvent) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Result.(*FileEvent_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *FileEvent) GetAck() *UploadAck {
	if x != nil {
		if x, ok := x.Result.(*FileEvent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *FileEvent) GetState() *UploadState {
	if x != nil {
		if x, ok := x.Result.(*FileEvent_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *FileEvent) GetSize() *DirectorySize {
	if x != nil {
		if x, ok := x.Result.(*FileEvent_Size); ok {
			return x.Size
		}
	}
	return nil
}

func (x *FileEvent) GetDone() *OperationDone {
	if x != nil {
		if x, ok := x.Result.(*FileEvent_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *FileEvent) GetError() *FileError {
	if x != nil {
		if x, ok := x.Result.(*FileEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isFileEvent_Result interface {
	isFileEvent_Result()
}

type FileEvent_Listing struct {
	Listing *DirectoryListing `protobuf:"bytes,2,opt,name=listing,proto3,oneof"`
}

type FileEvent_Info struct {
	Info *FileInfo `protobuf:"bytes,3,opt,name=info,proto3,oneof"`
}

type FileEvent_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,4,opt,name=chunk,proto3,oneof"`
}

type FileEvent_Ack struct {
	Ack *UploadAck `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type FileEvent_State struct {
	State *UploadState `protobuf:"bytes,6,opt,name=state,proto3,oneof"`
}

type FileEvent_Size struct {
	Size *DirectorySize `protobuf:"bytes,7,opt,name=size,proto3,oneof"`
}

type FileEvent_Done struct {
	// Terminates an operation that produces nothing else - a delete, a chmod, a
	// cancel. Without it the panel cannot tell "done" from "still working".
	Done *OperationDone `protobuf:"bytes,8,opt,name=done,proto3,oneof"`
}

type FileEvent_Error struct {
	// Terminates an operation that failed. Always the last event for its request.
	Error *FileError `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

func (*FileEvent_Listing) isFileEvent_Result() {}

func (*FileEvent_Info) isFileEvent_Result() {}

func (*FileEvent_Chunk) isFileEvent_Result() {}

func (*FileEvent_Ack) isFileEvent_Result() {}

func (*FileEvent_State) isFileEvent_Result() {}

func (*FileEvent_Size) isFileEvent_Result() {}

func (*FileEvent_Done) isFileEvent_Result() {}

func (*FileEvent_Error) isFileEvent_Result() {}

// One page of a directory.
//
// Paged because a customer with a node_modules directory has a hundred thousand
// entries, and a phone that is sent all of them renders nothing at all. Entries always
// come back directories first and then by name, so the cursor stays stable between
// pages.
type ListDirectory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Opaque, from the previous page's next_cursor. Empty starts at the beginning.
	Cursor   string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Dotfiles are hidden by default because the customer's own files are what they came
	// to see, and a toggle is one tap.
	IncludeHidden bool `protobuf:"varint,4,opt,name=include_hidden,json=includeHidden,proto3" json:"include_hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectory) Reset() {
	*x = ListDirectory{}
	mi := &file_wisper_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectory) ProtoMessage() {}

func (x *ListDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectory.ProtoReflect.Descriptor instead.
func (*ListDirectory) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *ListDirectory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirectory) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListDirectory) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDirectory) GetIncludeHidden() bool {
	if x != nil {
		return x.IncludeHidden
	}
	return false
}

type DirectoryListing struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Entries []*FileInfo            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// Empty when this was the last page.
	NextCursor string `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	// Total in the directory, so the UI can say "showing 200 of 40,312" rather than
	// implying the list is complete.
	TotalEntries  int32 `protobuf:"varint,4,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryListing) Reset() {
	*x = DirectoryListing{}
	mi := &file_wisper_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryListing) ProtoMessage() {}

func (x *DirectoryListing) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryListing.ProtoReflect.Descriptor instead.
func (*DirectoryListing) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{3}
}

func (x *DirectoryListing) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirectoryListing) GetEntries() []*FileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *DirectoryListing) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *DirectoryListing) GetTotalEntries() int32 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

// One directory entry, or the answer to a stat.
type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entry's own name, without any path.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Relative to the root, so the panel can build the next request without joining
	// strings itself and getting `..` wrong.
	Path      string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Directory bool   `protobuf:"varint,3,opt,name=directory,proto3" json:"directory,omitempty"`
	SizeBytes int64  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// POSIX permission bits only, as an octal value in the low nine bits. The file
	// manager shows and edits these; the type bits are already in `directory`.
	Mode       uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	ModifiedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	// Reported, never followed. A symlink in a customer volume that points outside the
	// root is shown as a symlink and refused as a target - following it is the traversal
	// hole that a path check alone does not close.
	Symlink       bool   `protobuf:"varint,7,opt,name=symlink,proto3" json:"symlink,omitempty"`
	SymlinkTarget string `protobuf:"bytes,8,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	Uid           uint32 `protobuf:"varint,9,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32 `protobuf:"varint,10,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_wisper_v1_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{4}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetDirectory() bool {
	if x != nil {
		return x.Directory
	}
	return false
}

func (x *FileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *FileInfo) GetSymlink() bool {
	if x != nil {
		return x.Symlink
	}
	return false
}

func (x *FileInfo) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

func (x *FileInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FileInfo) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type StatPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatPath) Reset() {
	*x = StatPath{}
	mi := &file_wisper_v1_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatPath) ProtoMessage() {}

func (x *StatPath) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatPath.ProtoReflect.Descriptor instead.
func (*StatPath) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{5}
}

func (x *StatPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Read a file, or part of one.
//
// The range exists for two different reasons: a download that resumes after the
// customer's connection dropped, and the inline editor, which opens the first megabyte
// of a large log rather than refusing to show it.
type ReadFile struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Path   string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// 0 means to the end of the file.
	MaxBytes      int64 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFile) Reset() {
	*x = ReadFile{}
	mi := &file_wisper_v1_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFile) ProtoMessage() {}

func (x *ReadFile) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFile.ProtoReflect.Descriptor instead.
func (*ReadFile) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFile) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFile) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// A run of bytes, used by downloads coming up and uploads going down. One message type
// for both directions because the framing problem is identical and two would drift.
type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Byte offset in the whole file. Authoritative for a download; cross-checked against
	// chunk_index for an upload, because a resumed upload that trusts a client-supplied
	// offset can be made to write anywhere in the file.
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// offset / UploadSession.chunk_size. The identity the resume query answers in, and
	// what makes a retried chunk idempotent instead of a duplicate.
	ChunkIndex int64  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data       []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Last chunk of this transfer. For a download it ends the stream of events; for an
	// upload it is a hint, and CompleteUpload is what actually finishes the file.
	Last bool `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	// Hex SHA-256 of `data`. Mobile networks corrupt more than they are given credit for,
	// and a bad chunk that is silently accepted becomes a corrupt file that the customer
	// discovers weeks later.
	Sha256        string `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_wisper_v1_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{7}
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *FileChunk) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// The upload this chunk belongs to. Repeated on every chunk rather than opened once,
// because the node may have restarted between chunks and has to be able to rebuild the
// session from what is on disk plus this message.
type UploadSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minted by the browser and carried by the panel. Survives a reload, which is what
	// makes "resume" mean anything to a customer who lost signal in a lift.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Destination, relative to the root.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// From the browser's File.size. Lets the node reject an upload that cannot fit in the
	// quota before it writes the first byte, instead of half way through.
	TotalBytes int64 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Hex SHA-256 of the whole file, verified at CompleteUpload. A resumed upload that
	// picked up a different version of the file fails loudly here rather than producing a
	// plausible-looking corrupt result.
	ContentSha256 string `protobuf:"bytes,4,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	// Bytes per chunk, from wisper.files.upload-chunk-size. Echoed so the node can derive
	// an offset from a chunk index without trusting the offset it was sent.
	ChunkSize int64 `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	// Overwrite an existing file. False makes an accidental re-upload an error the
	// customer sees instead of a file they lose.
	Overwrite     bool `protobuf:"varint,6,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSession) Reset() {
	*x = UploadSession{}
	mi := &file_wisper_v1_files_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSession) ProtoMessage() {}

func (x *UploadSession) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSession.ProtoReflect.Descriptor instead.
func (*UploadSession) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{8}
}

func (x *UploadSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadSession) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadSession) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadSession) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *UploadSession) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *UploadSession) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// One chunk of an upload. Saving an edited file from the inline editor is a one-chunk
// session, so there is no second write path that has to stay consistent with this one.
type WriteChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *UploadSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Chunk         *FileChunk             `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunk) Reset() {
	*x = WriteChunk{}
	mi := &file_wisper_v1_files_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunk) ProtoMessage() {}

func (x *WriteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunk.ProtoReflect.Descriptor instead.
func (*WriteChunk) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{9}
}

func (x *WriteChunk) GetSession() *UploadSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *WriteChunk) GetChunk() *FileChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// "What do you already have?" - asked before the first chunk of a resumed upload.
type ResumeUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeUpload) Reset() {
	*x = ResumeUpload{}
	mi := &file_wisper_v1_files_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeUpload) ProtoMessage() {}

func (x *ResumeUpload) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeUpload.ProtoReflect.Descriptor instead.
func (*ResumeUpload) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{10}
}

func (x *ResumeUpload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// What the node has on disk for a session. Ranges rather than a count because chunks
// can be uploaded in parallel and a dropped connection leaves holes, not a clean
// prefix.
type UploadState struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Coalesced and sorted. The browser resumes at the first gap.
	Received   []*ByteRange `protobuf:"bytes,2,rep,name=received,proto3" json:"received,omitempty"`
	TotalBytes int64        `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Sum of the ranges, so a progress bar does not have to add them up.
	ReceivedBytes int64 `protobuf:"varint,4,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	// When the partial upload will be swept (RetentionPolicy.orphan_upload_ttl_seconds).
	// The UI can warn instead of the customer finding the resume gone.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// False when the node has never heard of this session: the sweeper already took it,
	// or it was started against a different node. The browser starts again from zero.
	Known         bool `protobuf:"varint,6,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadState) Reset() {
	*x = UploadState{}
	mi := &file_wisper_v1_files_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadState) ProtoMessage() {}

func (x *UploadState) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadState.ProtoReflect.Descriptor instead.
func (*UploadState) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{11}
}

func (x *UploadState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadState) GetReceived() []*ByteRange {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *UploadState) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadState) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *UploadState) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *UploadState) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

// Half-open, like every other range in this contract: start is included, end is not.
type ByteRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	EndExclusive  int64                  `protobuf:"varint,2,opt,name=end_exclusive,json=endExclusive,proto3" json:"end_exclusive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteRange) Reset() {
	*x = ByteRange{}
	mi := &file_wisper_v1_files_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteRange) ProtoMessage() {}

func (x *ByteRange) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteRange.ProtoReflect.Descriptor instead.
func (*ByteRange) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{12}
}

func (x *ByteRange) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ByteRange) GetEndExclusive() int64 {
	if x != nil {
		return x.EndExclusive
	}
	return 0
}

// Acknowledges one chunk. The browser waits for this before releasing the chunk from
// memory, which is what stops a phone from buffering a 2 GB file it cannot hold.
type UploadAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkIndex    int64                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	ReceivedBytes int64                  `protobuf:"varint,3,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	// Where the node wants the next chunk. Usually the end of this one; different when
	// the node already had a later chunk and is telling the client to skip ahead.
	NextOffset    int64 `protobuf:"varint,4,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAck) Reset() {
	*x = UploadAck{}
	mi := &file_wisper_v1_files_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAck) ProtoMessage() {}

func (x *UploadAck) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAck.ProtoReflect.Descriptor instead.
func (*UploadAck) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{13}
}

func (x *UploadAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadAck) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadAck) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *UploadAck) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

// Assemble the chunks, verify the checksum, move the file into place. Separate from the
// last chunk because assembly can fail - a checksum mismatch, a quota that filled while
// the upload was in flight - and that failure has to be reportable.
type CompleteUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUpload) Reset() {
	*x = CompleteUpload{}
	mi := &file_wisper_v1_files_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUpload) ProtoMessage() {}

func (x *CompleteUpload) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUpload.ProtoReflect.Descriptor instead.
func (*CompleteUpload) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{14}
}

func (x *CompleteUpload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// The customer pressed cancel, or navigated away. Deletes the parts now rather than
// leaving them for the sweeper.
type AbortUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortUpload) Reset() {
	*x = AbortUpload{}
	mi := &file_wisper_v1_files_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortUpload) ProtoMessage() {}

func (x *AbortUpload) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortUpload.ProtoReflect.Descriptor instead.
func (*AbortUpload) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{15}
}

func (x *AbortUpload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateDirectory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Create missing parents. The file manager's "new folder" only ever needs one level;
	// an extract needs all of them.
	Parents       bool `protobuf:"varint,2,opt,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectory) Reset() {
	*x = CreateDirectory{}
	mi := &file_wisper_v1_files_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectory) ProtoMessage() {}

func (x *CreateDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectory.ProtoReflect.Descriptor instead.
func (*CreateDirectory) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{16}
}

func (x *CreateDirectory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateDirectory) GetParents() bool {
	if x != nil {
		return x.Parents
	}
	return false
}

// Rename and move are the same operation, and separating them produces two code paths
// with one bug each.
type MovePath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Overwrite     bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePath) Reset() {
	*x = MovePath{}
	mi := &file_wisper_v1_files_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePath) ProtoMessage() {}

func (x *MovePath) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePath.ProtoReflect.Descriptor instead.
func (*MovePath) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{17}
}

func (x *MovePath) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MovePath) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MovePath) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type DeletePath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Required for a non-empty directory. Deleting a tree by accident because the flag
	// defaulted to true is not recoverable: there is no trash on the node.
	Recursive     bool `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePath) Reset() {
	*x = DeletePath{}
	mi := &file_wisper_v1_files_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePath) ProtoMessage() {}

func (x *DeletePath) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePath.ProtoReflect.Descriptor instead.
func (*DeletePath) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeletePath) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type ChangeMode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Octal permission bits in the low nine, as shown in the UI.
	Mode uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// Apply to everything underneath. Directories usually need different bits from files,
	// so the node applies the execute bit to directories only.
	Recursive     bool `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMode) Reset() {
	*x = ChangeMode{}
	mi := &file_wisper_v1_files_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMode) ProtoMessage() {}

func (x *ChangeMode) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMode.ProtoReflect.Descriptor instead.
func (*ChangeMode) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{19}
}

func (x *ChangeMode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChangeMode) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ChangeMode) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// Compress in place, on the node. Doing it here rather than in the browser is the whole
// point: a customer on a phone can package a directory they could never download first.
type CreateArchive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Paths []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	// Destination archive, relative to the root.
	Destination   string        `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Format        ArchiveFormat `protobuf:"varint,3,opt,name=format,proto3,enum=wisper.v1.ArchiveFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArchive) Reset() {
	*x = CreateArchive{}
	mi := &file_wisper_v1_files_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArchive) ProtoMessage() {}

func (x *CreateArchive) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArchive.ProtoReflect.Descriptor instead.
func (*CreateArchive) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{20}
}

func (x *CreateArchive) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *CreateArchive) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateArchive) GetFormat() ArchiveFormat {
	if x != nil {
		return x.Format
	}
	return ArchiveFormat_ARCHIVE_FORMAT_UNSPECIFIED
}

// Unpack in place. Entry paths are resolved and checked against the root exactly like
// any other path - an archive full of `../../etc` entries is the oldest trick there is.
type ExtractArchive struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ArchivePath          string                 `protobuf:"bytes,1,opt,name=archive_path,json=archivePath,proto3" json:"archive_path,omitempty"`
	DestinationDirectory string                 `protobuf:"bytes,2,opt,name=destination_directory,json=destinationDirectory,proto3" json:"destination_directory,omitempty"`
	Overwrite            bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExtractArchive) Reset() {
	*x = ExtractArchive{}
	mi := &file_wisper_v1_files_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractArchive) ProtoMessage() {}

func (x *ExtractArchive) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractArchive.ProtoReflect.Descriptor instead.
func (*ExtractArchive) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{21}
}

func (x *ExtractArchive) GetArchivePath() string {
	if x != nil {
		return x.ArchivePath
	}
	return ""
}

func (x *ExtractArchive) GetDestinationDirectory() string {
	if x != nil {
		return x.DestinationDirectory
	}
	return ""
}

func (x *ExtractArchive) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// "How big is this folder?" - the question a customer asks when their quota is full.
// A separate operation because it walks the tree, which a listing must not do.
type MeasureDirectory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureDirectory) Reset() {
	*x = MeasureDirectory{}
	mi := &file_wisper_v1_files_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureDirectory) ProtoMessage() {}

func (x *MeasureDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureDirectory.ProtoReflect.Descriptor instead.
func (*MeasureDirectory) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{22}
}

func (x *MeasureDirectory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DirectorySize struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Bytes          int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	FileCount      int64                  `protobuf:"varint,3,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	DirectoryCount int64                  `protobuf:"varint,4,opt,name=directory_count,json=directoryCount,proto3" json:"directory_count,omitempty"`
	// The walk hit its budget and stopped. An answer marked approximate is more useful
	// than a request that never returns.
	Approximate   bool `protobuf:"varint,5,opt,name=approximate,proto3" json:"approximate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectorySize) Reset() {
	*x = DirectorySize{}
	mi := &file_wisper_v1_files_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectorySize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectorySize) ProtoMessage() {}

func (x *DirectorySize) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectorySize.ProtoReflect.Descriptor instead.
func (*DirectorySize) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{23}
}

func (x *DirectorySize) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirectorySize) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *DirectorySize) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *DirectorySize) GetDirectoryCount() int64 {
	if x != nil {
		return x.DirectoryCount
	}
	return 0
}

func (x *DirectorySize) GetApproximate() bool {
	if x != nil {
		return x.Approximate
	}
	return false
}

// Stop an operation that is still running: the customer closed the download, or moved
// away from a directory whose size was being measured. Needed because one stream
// carries every operation for a node, and an abandoned tree walk would otherwise keep
// its disk busy.
type CancelRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CancelledRequestId string                 `protobuf:"bytes,1,opt,name=cancelled_request_id,json=cancelledRequestId,proto3" json:"cancelled_request_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_wisper_v1_files_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{24}
}

func (x *CancelRequest) GetCancelledRequestId() string {
	if x != nil {
		return x.CancelledRequestId
	}
	return ""
}

// Success terminator for an operation with no payload.
type OperationDone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filled where it is cheap and useful: the number of entries deleted, the number of
	// files extracted. Zero otherwise.
	Affected      int64                  `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationDone) Reset() {
	*x = OperationDone{}
	mi := &file_wisper_v1_files_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationDone) ProtoMessage() {}

func (x *OperationDone) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationDone.ProtoReflect.Descriptor instead.
func (*OperationDone) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{25}
}

func (x *OperationDone) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

func (x *OperationDone) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type FileError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  FileErrorCode          `protobuf:"varint,1,opt,name=code,proto3,enum=wisper.v1.FileErrorCode" json:"code,omitempty"`
	// Safe to show the customer. The node writes it for a person, not for a log parser.
	Detail string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	// Which path the operation was on when it failed, relative to the root. An extract
	// that fails on entry 400 of 900 has to say which one.
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileError) Reset() {
	*x = FileError{}
	mi := &file_wisper_v1_files_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileError) ProtoMessage() {}

func (x *FileError) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_files_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileError.ProtoReflect.Descriptor instead.
func (*FileError) Descriptor() ([]byte, []int) {
	return file_wisper_v1_files_proto_rawDescGZIP(), []int{26}
}

func (x *FileError) GetCode() FileErrorCode {
	if x != nil {
		return x.Code
	}
	return FileErrorCode_FILE_ERROR_CODE_UNSPECIFIED
}

func (x *FileError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *FileError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_wisper_v1_files_proto protoreflect.FileDescriptor

const file_wisper_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x15wisper/v1/files.proto\x12\twisper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x06\n" +
	"\vFileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\aroot_id\x18\x02 \x01(\tR\x06rootId\x12.\n" +
	"\x04list\x18\x03 \x01(\v2\x18.wisper.v1.ListDirectoryH\x00R\x04list\x12)\n" +
	"\x04stat\x18\x04 \x01(\v2\x13.wisper.v1.StatPathH\x00R\x04stat\x12)\n" +
	"\x04read\x18\x05 \x01(\v2\x13.wisper.v1.ReadFileH\x00R\x04read\x12-\n" +
	"\x05write\x18\x06 \x01(\v2\x15.wisper.v1.WriteChunkH\x00R\x05write\x121\n" +
	"\x06resume\x18\a \x01(\v2\x17.wisper.v1.ResumeUploadH\x00R\x06resume\x127\n" +
	"\bcomplete\x18\b \x01(\v2\x19.wisper.v1.CompleteUploadH\x00R\bcomplete\x12.\n" +
	"\x05abort\x18\t \x01(\v2\x16.wisper.v1.AbortUploadH\x00R\x05abort\x12G\n" +
	"\x10create_directory\x18\n" +
	" \x01(\v2\x1a.wisper.v1.CreateDirectoryH\x00R\x0fcreateDirectory\x12)\n" +
	"\x04move\x18\v \x01(\v2\x13.wisper.v1.MovePathH\x00R\x04move\x12/\n" +
	"\x06delete\x18\f \x01(\v2\x15.wisper.v1.DeletePathH\x00R\x06delete\x128\n" +
	"\vchange_mode\x18\r \x01(\v2\x15.wisper.v1.ChangeModeH\x00R\n" +
	"changeMode\x124\n" +
	"\aarchive\x18\x0e \x01(\v2\x18.wisper.v1.CreateArchiveH\x00R\aarchive\x125\n" +
	"\aextract\x18\x0f \x01(\v2\x19.wisper.v1.ExtractArchiveH\x00R\aextract\x127\n" +
	"\ameasure\x18\x10 \x01(\v2\x1b.wisper.v1.MeasureDirectoryH\x00R\ameasure\x122\n" +
	"\x06cancel\x18\x11 \x01(\v2\x18.wisper.v1.CancelRequestH\x00R\x06cancelB\x04\n" +
	"\x02op\"\xae\x03\n" +
	"\tFileEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x127\n" +
	"\alisting\x18\x02 \x01(\v2\x1b.wisper.v1.DirectoryListingH\x00R\alisting\x12)\n" +
	"\x04info\x18\x03 \x01(\v2\x13.wisper.v1.FileInfoH\x00R\x04info\x12,\n" +
	"\x05chunk\x18\x04 \x01(\v2\x14.wisper.v1.FileChunkH\x00R\x05chunk\x12(\n" +
	"\x03ack\x18\x05 \x01(\v2\x14.wisper.v1.UploadAckH\x00R\x03ack\x12.\n" +
	"\x05state\x18\x06 \x01(\v2\x16.wisper.v1.UploadStateH\x00R\x05state\x12.\n" +
	"\x04size\x18\a \x01(\v2\x18.wisper.v1.DirectorySizeH\x00R\x04size\x12.\n" +
	"\x04done\x18\b \x01(\v2\x18.wisper.v1.OperationDoneH\x00R\x04done\x12,\n" +
	"\x05error\x18\t \x01(\v2\x14.wisper.v1.FileErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x7f\n" +
	"\rListDirectory\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12%\n" +
	"\x0einclude_hidden\x18\x04 \x01(\bR\rincludeHidden\"\x9b\x01\n" +
	"\x10DirectoryListing\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12-\n" +
	"\aentries\x18\x02 \x03(\v2\x13.wisper.v1.FileInfoR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\x12#\n" +
	"\rtotal_entries\x18\x04 \x01(\x05R\ftotalEntries\"\xa5\x02\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\tdirectory\x18\x03 \x01(\bR\tdirectory\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12;\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x18\n" +
	"\asymlink\x18\a \x01(\bR\asymlink\x12%\n" +
	"\x0esymlink_target\x18\b \x01(\tR\rsymlinkTarget\x12\x10\n" +
	"\x03uid\x18\t \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\n" +
	" \x01(\rR\x03gid\"\x1e\n" +
	"\bStatPath\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"S\n" +
	"\bReadFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\x03R\bmaxBytes\"\x84\x01\n" +
	"\tFileChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x03R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x04 \x01(\bR\x04last\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\"\xc7\x01\n" +
	"\rUploadSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12%\n" +
	"\x0econtent_sha256\x18\x04 \x01(\tR\rcontentSha256\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x03R\tchunkSize\x12\x1c\n" +
	"\toverwrite\x18\x06 \x01(\bR\toverwrite\"l\n" +
	"\n" +
	"WriteChunk\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.wisper.v1.UploadSessionR\asession\x12*\n" +
	"\x05chunk\x18\x02 \x01(\v2\x14.wisper.v1.FileChunkR\x05chunk\"-\n" +
	"\fResumeUpload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xf7\x01\n" +
	"\vUploadState\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\breceived\x18\x02 \x03(\v2\x14.wisper.v1.ByteRangeR\breceived\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12%\n" +
	"\x0ereceived_bytes\x18\x04 \x01(\x03R\rreceivedBytes\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x14\n" +
	"\x05known\x18\x06 \x01(\bR\x05known\"F\n" +
	"\tByteRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12#\n" +
	"\rend_exclusive\x18\x02 \x01(\x03R\fendExclusive\"\x93\x01\n" +
	"\tUploadAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x03R\n" +
	"chunkIndex\x12%\n" +
	"\x0ereceived_bytes\x18\x03 \x01(\x03R\rreceivedBytes\x12\x1f\n" +
	"\vnext_offset\x18\x04 \x01(\x03R\n" +
	"nextOffset\"/\n" +
	"\x0eCompleteUpload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\",\n" +
	"\vAbortUpload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"?\n" +
	"\x0fCreateDirectory\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aparents\x18\x02 \x01(\bR\aparents\"L\n" +
	"\bMovePath\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\">\n" +
	"\n" +
	"DeletePath\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"R\n" +
	"\n" +
	"ChangeMode\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\"y\n" +
	"\rCreateArchive\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x120\n" +
	"\x06format\x18\x03 \x01(\x0e2\x18.wisper.v1.ArchiveFormatR\x06format\"\x86\x01\n" +
	"\x0eExtractArchive\x12!\n" +
	"\farchive_path\x18\x01 \x01(\tR\varchivePath\x123\n" +
	"\x15destination_directory\x18\x02 \x01(\tR\x14destinationDirectory\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\"&\n" +
	"\x10MeasureDirectory\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xa3\x01\n" +
	"\rDirectorySize\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\x12\x1d\n" +
	"\n" +
	"file_count\x18\x03 \x01(\x03R\tfileCount\x12'\n" +
	"\x0fdirectory_count\x18\x04 \x01(\x03R\x0edirectoryCount\x12 \n" +
	"\vapproximate\x18\x05 \x01(\bR\vapproximate\"A\n" +
	"\rCancelRequest\x120\n" +
	"\x14cancelled_request_id\x18\x01 \x01(\tR\x12cancelledRequestId\"h\n" +
	"\rOperationDone\x12\x1a\n" +
	"\baffected\x18\x01 \x01(\x03R\baffected\x12;\n" +
	"\vfinished_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"e\n" +
	"\tFileError\x12,\n" +
	"\x04code\x18\x01 \x01(\x0e2\x18.wisper.v1.FileErrorCodeR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path*b\n" +
	"\rArchiveFormat\x12\x1e\n" +
	"\x1aARCHIVE_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ARCHIVE_FORMAT_ZIP\x10\x01\x12\x19\n" +
	"\x15ARCHIVE_FORMAT_TAR_GZ\x10\x02*\xca\x04\n" +
	"\rFileErrorCode\x12\x1f\n" +
	"\x1bFILE_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FILE_ERROR_CODE_NOT_FOUND\x10\x01\x12\"\n" +
	"\x1eFILE_ERROR_CODE_ALREADY_EXISTS\x10\x02\x12%\n" +
	"!FILE_ERROR_CODE_PERMISSION_DENIED\x10\x03\x12%\n" +
	"!FILE_ERROR_CODE_PATH_ESCAPES_ROOT\x10\x04\x12#\n" +
	"\x1fFILE_ERROR_CODE_NOT_A_DIRECTORY\x10\x05\x12\"\n" +
	"\x1eFILE_ERROR_CODE_IS_A_DIRECTORY\x10\x06\x12'\n" +
	"#FILE_ERROR_CODE_DIRECTORY_NOT_EMPTY\x10\a\x12\"\n" +
	"\x1eFILE_ERROR_CODE_QUOTA_EXCEEDED\x10\b\x12\x1d\n" +
	"\x19FILE_ERROR_CODE_TOO_LARGE\x10\t\x12%\n" +
	"!FILE_ERROR_CODE_CHECKSUM_MISMATCH\x10\n" +
	"\x12#\n" +
	"\x1fFILE_ERROR_CODE_UNKNOWN_SESSION\x10\v\x12'\n" +
	"#FILE_ERROR_CODE_UNSUPPORTED_ARCHIVE\x10\f\x12 \n" +
	"\x1cFILE_ERROR_CODE_UNKNOWN_ROOT\x10\r\x12\x1d\n" +
	"\x19FILE_ERROR_CODE_CANCELLED\x10\x0e\x12\x1c\n" +
	"\x18FILE_ERROR_CODE_IO_ERROR\x10\x0fBk\n" +
	"\x1clhqm.furimeo.wisper.proto.v1B\n" +
	"FilesProtoP\x01Z=github.com/furimeo/wisper/sasayaki/internal/wisperpb;wisperpbb\x06proto3"

var (
	file_wisper_v1_files_proto_rawDescOnce sync.Once
	file_wisper_v1_files_proto_rawDescData []byte
)

func file_wisper_v1_files_proto_rawDescGZIP() []byte {
	file_wisper_v1_files_proto_rawDescOnce.Do(func() {
		file_wisper_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wisper_v1_files_proto_rawDesc), len(file_wisper_v1_files_proto_rawDesc)))
	})
	return file_wisper_v1_files_proto_rawDescData
}

var file_wisper_v1_files_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wisper_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_wisper_v1_files_proto_goTypes = []any{
	(ArchiveFormat)(0),            // 0: wisper.v1.ArchiveFormat
	(FileErrorCode)(0),            // 1: wisper.v1.FileErrorCode
	(*FileRequest)(nil),           // 2: wisper.v1.FileRequest
	(*FileEvent)(nil),             // 3: wisper.v1.FileEvent
	(*ListDirectory)(nil),         // 4: wisper.v1.ListDirectory
	(*DirectoryListing)(nil),      // 5: wisper.v1.DirectoryListing
	(*FileInfo)(nil),              // 6: wisper.v1.FileInfo
	(*StatPath)(nil),              // 7: wisper.v1.StatPath
	(*ReadFile)(nil),              // 8: wisper.v1.ReadFile
	(*FileChunk)(nil),             // 9: wisper.v1.FileChunk
	(*UploadSession)(nil),         // 10: wisper.v1.UploadSession
	(*WriteChunk)(nil),            // 11: wisper.v1.WriteChunk
	(*ResumeUpload)(nil),          // 12: wisper.v1.ResumeUpload
	(*UploadState)(nil),           // 13: wisper.v1.UploadState
	(*ByteRange)(nil),             // 14: wisper.v1.ByteRange
	(*UploadAck)(nil),             // 15: wisper.v1.UploadAck
	(*CompleteUpload)(nil),        // 16: wisper.v1.CompleteUpload
	(*AbortUpload)(nil),           // 17: wisper.v1.AbortUpload
	(*CreateDirectory)(nil),       // 18: wisper.v1.CreateDirectory
	(*MovePath)(nil),              // 19: wisper.v1.MovePath
	(*DeletePath)(nil),            // 20: wisper.v1.DeletePath
	(*ChangeMode)(nil),            // 21: wisper.v1.ChangeMode
	(*CreateArchive)(nil),         // 22: wisper.v1.CreateArchive
	(*ExtractArchive)(nil),        // 23: wisper.v1.ExtractArchive
	(*MeasureDirectory)(nil),      // 24: wisper.v1.MeasureDirectory
	(*DirectorySize)(nil),         // 25: wisper.v1.DirectorySize
	(*CancelRequest)(nil),         // 26: wisper.v1.CancelRequest
	(*OperationDone)(nil),         // 27: wisper.v1.OperationDone
	(*FileError)(nil),             // 28: wisper.v1.FileError
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
}
var file_wisper_v1_files_proto_depIdxs = []int32{
	4,  // 0: wisper.v1.FileRequest.list:type_name -> wisper.v1.ListDirectory
	7,  // 1: wisper.v1.FileRequest.stat:type_name -> wisper.v1.StatPath
	8,  // 2: wisper.v1.FileRequest.read:type_name -> wisper.v1.ReadFile
	11, // 3: wisper.v1.FileRequest.write:type_name -> wisper.v1.WriteChunk
	12, // 4: wisper.v1.FileRequest.resume:type_name -> wisper.v1.ResumeUpload
	16, // 5: wisper.v1.FileRequest.complete:type_name -> wisper.v1.CompleteUpload
	17, // 6: wisper.v1.FileRequest.abort:type_name -> wisper.v1.AbortUpload
	18, // 7: wisper.v1.FileRequest.create_directory:type_name -> wisper.v1.CreateDirectory
	19, // 8: wisper.v1.FileRequest.move:type_name -> wisper.v1.MovePath
	20, // 9: wisper.v1.FileRequest.delete:type_name -> wisper.v1.DeletePath
	21, // 10: wisper.v1.FileRequest.change_mode:type_name -> wisper.v1.ChangeMode
	22, // 11: wisper.v1.FileRequest.archive:type_name -> wisper.v1.CreateArchive
	23, // 12: wisper.v1.FileRequest.extract:type_name -> wisper.v1.ExtractArchive
	24, // 13: wisper.v1.FileRequest.measure:type_name -> wisper.v1.MeasureDirectory
	26, // 14: wisper.v1.FileRequest.cancel:type_name -> wisper.v1.CancelRequest
	5,  // 15: wisper.v1.FileEvent.listing:type_name -> wisper.v1.DirectoryListing
	6,  // 16: wisper.v1.FileEvent.info:type_name -> wisper.v1.FileInfo
	9,  // 17: wisper.v1.FileEvent.chunk:type_name -> wisper.v1.FileChunk
	15, // 18: wisper.v1.FileEvent.ack:type_name -> wisper.v1.UploadAck
	13, // 19: wisper.v1.FileEvent.state:type_name -> wisper.v1.UploadState
	25, // 20: wisper.v1.FileEvent.size:type_name -> wisper.v1.DirectorySize
	27, // 21: wisper.v1.FileEvent.done:type_name -> wisper.v1.OperationDone
	28, // 22: wisper.v1.FileEvent.error:type_name -> wisper.v1.FileError
	6,  // 23: wisper.v1.DirectoryListing.entries:type_name -> wisper.v1.FileInfo
	29, // 24: wisper.v1.FileInfo.modified_at:type_name -> google.protobuf.Timestamp
	10, // 25: wisper.v1.WriteChunk.session:type_name -> wisper.v1.UploadSession
	9,  // 26: wisper.v1.WriteChunk.chunk:type_name -> wisper.v1.FileChunk
	14, // 27: wisper.v1.UploadState.received:type_name -> wisper.v1.ByteRange
	29, // 28: wisper.v1.UploadState.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 29: wisper.v1.CreateArchive.format:type_name -> wisper.v1.ArchiveFormat
	29, // 30: wisper.v1.OperationDone.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 31: wisper.v1.FileError.code:type_name -> wisper.v1.FileErrorCode
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_wisper_v1_files_proto_init() }
func file_wisper_v1_files_proto_init() {
	if File_wisper_v1_files_proto != nil {
		return
	}
	file_wisper_v1_files_proto_msgTypes[0].OneofWrappers = []any{
		(*FileRequest_List)(nil),
		(*FileRequest_Stat)(nil),
		(*FileRequest_Read)(nil),
		(*FileRequest_Write)(nil),
		(*FileRequest_Resume)(nil),
		(*FileRequest_Complete)(nil),
		(*FileRequest_Abort)(nil),
		(*FileRequest_CreateDirectory)(nil),
		(*FileRequest_Move)(nil),
		(*FileRequest_Delete)(nil),
		(*FileRequest_ChangeMode)(nil),
		(*FileRequest_Archive)(nil),
		(*FileRequest_Extract)(nil),
		(*FileRequest_Measure)(nil),
		(*FileRequest_Cancel)(nil),
	}
	file_wisper_v1_files_proto_msgTypes[1].OneofWrappers = []any{
		(*FileEvent_Listing)(nil),
		(*FileEvent_Info)(nil),
		(*FileEvent_Chunk)(nil),
		(*FileEvent_Ack)(nil),
		(*FileEvent_State)(nil),
		(*FileEvent_Size)(nil),
		(*FileEvent_Done)(nil),
		(*FileEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wisper_v1_files_proto_rawDesc), len(file_wisper_v1_files_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wisper_v1_files_proto_goTypes,
		DependencyIndexes: file_wisper_v1_files_proto_depIdxs,
		EnumInfos:         file_wisper_v1_files_proto_enumTypes,
		MessageInfos:      file_wisper_v1_files_proto_msgTypes,
	}.Build()
	File_wisper_v1_files_proto = out.File
	file_wisper_v1_files_proto_goTypes = nil
	file_wisper_v1_files_proto_depIdxs = nil
}
