// NodeService: how a node joins a panel and how the two talk for the rest of its life.
//
// One thing decides the shape of everything here. The panel has no public IP - it sits
// behind a tunnel - so it can never dial a node. The node is always the gRPC client and
// the panel is always the server, and every "the panel tells the node to..." below is a
// message travelling down the response side of a stream the node opened (design
// section 5.2). The second thing is that such a stream drops, routinely: nothing here
// carries a delta, so reconnecting means resending the whole spec and it does not
// matter how long the node was gone.
//
// Authentication is in gRPC metadata, and this is the only place it is written down:
//
//   wisper-node-id       the node id from EnrollResponse
//   wisper-node-token    the long-lived credential from EnrollResponse
//   wisper-protocol      the protocol version in decimal, so the panel can refuse an
//                        incompatible node before it has parsed a frame
//
// Enroll is the one RPC carrying none of them: there is no credential yet, and it
// authenticates with the single-use bootstrap token in its body.
//
// Over 300 lines and not split further because it is one conversation - handshake,
// commands, acknowledgements and status all reference each other. The parts with their
// own vocabulary (the spec, terminals, files, stats, backups, databases, builds) are
// already their own files, and this one only references them.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: wisper/v1/node.proto

package wisperpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Enroll_FullMethodName       = "/wisper.v1.NodeService/Enroll"
	NodeService_Connect_FullMethodName      = "/wisper.v1.NodeService/Connect"
	NodeService_ReportStatus_FullMethodName = "/wisper.v1.NodeService/ReportStatus"
	NodeService_PushStats_FullMethodName    = "/wisper.v1.NodeService/PushStats"
	NodeService_Terminal_FullMethodName     = "/wisper.v1.NodeService/Terminal"
	NodeService_LogStream_FullMethodName    = "/wisper.v1.NodeService/LogStream"
	NodeService_FileOp_FullMethodName       = "/wisper.v1.NodeService/FileOp"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// Join a panel with a single-use bootstrap token and walk away with a permanent
	// credential. Unauthenticated by necessity; the token in the request is the proof.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// The control channel, open for the life of the daemon: negotiates the protocol
	// version in its first frame, then carries heartbeats up and commands down. It is the
	// only stream that must exist - everything else is opened in response to something
	// that arrives on it.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, PanelMessage], error)
	// The result of a reconcile pass. Unary rather than a frame on Connect because it is
	// a discrete, retryable unit: if the panel is restarting, the node retries this with
	// backoff instead of tearing down the control stream and the commands queued on it.
	ReportStatus(ctx context.Context, in *StatusBatch, opts ...grpc.CallOption) (*Ack, error)
	// Metrics, pushed continuously. Its own stream so a burst of samples cannot delay a
	// heartbeat, and so the panel can throttle it with Ack.pause_seconds alone.
	PushStats(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StatSample, Ack], error)
	// One interactive session, opened by the node after a StartTerminal command.
	// Bidirectional and framed - see terminal.proto for why that is not negotiable.
	Terminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalFrame, TerminalFrame], error)
	// Log output for every active subscription. Subscriptions start and stop with
	// LogRequest and StopLogStream on the control channel, so this call stays open for
	// the life of the daemon like PushStats does.
	LogStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogChunk, Ack], error)
	// File operations: the node opens the stream, the panel drives it. FileRequest goes
	// down, FileEvent comes back up - reversed-looking for the same reason as everything
	// else here, that only the node can dial.
	FileOp(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileEvent, FileRequest], error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, NodeService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, PanelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeMessage, PanelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ConnectClient = grpc.BidiStreamingClient[NodeMessage, PanelMessage]

func (c *nodeServiceClient) ReportStatus(ctx context.Context, in *StatusBatch, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodeService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) PushStats(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StatSample, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_PushStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatSample, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_PushStatsClient = grpc.ClientStreamingClient[StatSample, Ack]

func (c *nodeServiceClient) Terminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalFrame, TerminalFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_Terminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalFrame, TerminalFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_TerminalClient = grpc.BidiStreamingClient[TerminalFrame, TerminalFrame]

func (c *nodeServiceClient) LogStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogChunk, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[3], NodeService_LogStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogChunk, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_LogStreamClient = grpc.ClientStreamingClient[LogChunk, Ack]

func (c *nodeServiceClient) FileOp(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileEvent, FileRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[4], NodeService_FileOp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileEvent, FileRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_FileOpClient = grpc.BidiStreamingClient[FileEvent, FileRequest]

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	// Join a panel with a single-use bootstrap token and walk away with a permanent
	// credential. Unauthenticated by necessity; the token in the request is the proof.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// The control channel, open for the life of the daemon: negotiates the protocol
	// version in its first frame, then carries heartbeats up and commands down. It is the
	// only stream that must exist - everything else is opened in response to something
	// that arrives on it.
	Connect(grpc.BidiStreamingServer[NodeMessage, PanelMessage]) error
	// The result of a reconcile pass. Unary rather than a frame on Connect because it is
	// a discrete, retryable unit: if the panel is restarting, the node retries this with
	// backoff instead of tearing down the control stream and the commands queued on it.
	ReportStatus(context.Context, *StatusBatch) (*Ack, error)
	// Metrics, pushed continuously. Its own stream so a burst of samples cannot delay a
	// heartbeat, and so the panel can throttle it with Ack.pause_seconds alone.
	PushStats(grpc.ClientStreamingServer[StatSample, Ack]) error
	// One interactive session, opened by the node after a StartTerminal command.
	// Bidirectional and framed - see terminal.proto for why that is not negotiable.
	Terminal(grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]) error
	// Log output for every active subscription. Subscriptions start and stop with
	// LogRequest and StopLogStream on the control channel, so this call stays open for
	// the life of the daemon like PushStats does.
	LogStream(grpc.ClientStreamingServer[LogChunk, Ack]) error
	// File operations: the node opens the stream, the panel drives it. FileRequest goes
	// down, FileEvent comes back up - reversed-looking for the same reason as everything
	// else here, that only the node can dial.
	FileOp(grpc.BidiStreamingServer[FileEvent, FileRequest]) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedNodeServiceServer) Connect(grpc.BidiStreamingServer[NodeMessage, PanelMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeServiceServer) ReportStatus(context.Context, *StatusBatch) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedNodeServiceServer) PushStats(grpc.ClientStreamingServer[StatSample, Ack]) error {
	return status.Error(codes.Unimplemented, "method PushStats not implemented")
}
func (UnimplementedNodeServiceServer) Terminal(grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]) error {
	return status.Error(codes.Unimplemented, "method Terminal not implemented")
}
func (UnimplementedNodeServiceServer) LogStream(grpc.ClientStreamingServer[LogChunk, Ack]) error {
	return status.Error(codes.Unimplemented, "method LogStream not implemented")
}
func (UnimplementedNodeServiceServer) FileOp(grpc.BidiStreamingServer[FileEvent, FileRequest]) error {
	return status.Error(codes.Unimplemented, "method FileOp not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).Connect(&grpc.GenericServerStream[NodeMessage, PanelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ConnectServer = grpc.BidiStreamingServer[NodeMessage, PanelMessage]

func _NodeService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReportStatus(ctx, req.(*StatusBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_PushStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).PushStats(&grpc.GenericServerStream[StatSample, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_PushStatsServer = grpc.ClientStreamingServer[StatSample, Ack]

func _NodeService_Terminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).Terminal(&grpc.GenericServerStream[TerminalFrame, TerminalFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_TerminalServer = grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]

func _NodeService_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).LogStream(&grpc.GenericServerStream[LogChunk, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_LogStreamServer = grpc.ClientStreamingServer[LogChunk, Ack]

func _NodeService_FileOp_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).FileOp(&grpc.GenericServerStream[FileEvent, FileRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_FileOpServer = grpc.BidiStreamingServer[FileEvent, FileRequest]

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisper.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _NodeService_Enroll_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _NodeService_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NodeService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PushStats",
			Handler:       _NodeService_PushStats_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Terminal",
			Handler:       _NodeService_Terminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LogStream",
			Handler:       _NodeService_LogStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FileOp",
			Handler:       _NodeService_FileOp_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wisper/v1/node.proto",
}
