// Observability: the samples a node pushes so the panel can draw a graph, and the log
// chunks it pushes so a customer can watch their application start.
//
// Both live here because both are the node telling the panel what is happening rather
// than what it has been asked to do, and both are lossy by design - a metric that is
// dropped under load is a gap in a chart, while a metric that blocks the reconcile loop
// is an outage.
//
// Counters, not rates, and integers, not floats. The node sends the cumulative CPU
// nanoseconds and the length of the interval; the panel divides. Sampling twice into the
// same rollup bucket then adds up exactly, which a pre-computed percentage does not.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wisper/v1/stats.proto

package wisperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Where a log line came from. One log path for four sources, because a second one would
// need its own backpressure, its own retention and its own bug.
type LogSource int32

const (
	LogSource_LOG_SOURCE_UNSPECIFIED LogSource = 0
	// A workload's container output.
	LogSource_LOG_SOURCE_CONTAINER LogSource = 1
	// A build: git clone, install, compile, publish (design section 5.5).
	LogSource_LOG_SOURCE_BUILD LogSource = 2
	// One run of a cron entry.
	LogSource_LOG_SOURCE_CRON LogSource = 3
	// The daemon itself, when an operator asks for it from the admin screens.
	LogSource_LOG_SOURCE_SYSTEM LogSource = 4
)

// Enum value maps for LogSource.
var (
	LogSource_name = map[int32]string{
		0: "LOG_SOURCE_UNSPECIFIED",
		1: "LOG_SOURCE_CONTAINER",
		2: "LOG_SOURCE_BUILD",
		3: "LOG_SOURCE_CRON",
		4: "LOG_SOURCE_SYSTEM",
	}
	LogSource_value = map[string]int32{
		"LOG_SOURCE_UNSPECIFIED": 0,
		"LOG_SOURCE_CONTAINER":   1,
		"LOG_SOURCE_BUILD":       2,
		"LOG_SOURCE_CRON":        3,
		"LOG_SOURCE_SYSTEM":      4,
	}
)

func (x LogSource) Enum() *LogSource {
	p := new(LogSource)
	*p = x
	return p
}

func (x LogSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSource) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_stats_proto_enumTypes[0].Descriptor()
}

func (LogSource) Type() protoreflect.EnumType {
	return &file_wisper_v1_stats_proto_enumTypes[0]
}

func (x LogSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSource.Descriptor instead.
func (LogSource) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_stats_proto_rawDescGZIP(), []int{0}
}

type LogStreamKind int32

const (
	LogStreamKind_LOG_STREAM_KIND_UNSPECIFIED LogStreamKind = 0
	LogStreamKind_LOG_STREAM_KIND_STDOUT      LogStreamKind = 1
	LogStreamKind_LOG_STREAM_KIND_STDERR      LogStreamKind = 2
)

// Enum value maps for LogStreamKind.
var (
	LogStreamKind_name = map[int32]string{
		0: "LOG_STREAM_KIND_UNSPECIFIED",
		1: "LOG_STREAM_KIND_STDOUT",
		2: "LOG_STREAM_KIND_STDERR",
	}
	LogStreamKind_value = map[string]int32{
		"LOG_STREAM_KIND_UNSPECIFIED": 0,
		"LOG_STREAM_KIND_STDOUT":      1,
		"LOG_STREAM_KIND_STDERR":      2,
	}
)

func (x LogStreamKind) Enum() *LogStreamKind {
	p := new(LogStreamKind)
	*p = x
	return p
}

func (x LogStreamKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStreamKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_stats_proto_enumTypes[1].Descriptor()
}

func (LogStreamKind) Type() protoreflect.EnumType {
	return &file_wisper_v1_stats_proto_enumTypes[1]
}

func (x LogStreamKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStreamKind.Descriptor instead.
func (LogStreamKind) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_stats_proto_rawDescGZIP(), []int{1}
}

// One measurement, of either the machine or one workload on it.
//
// A single stream carries both so there is one place where sampling stops when the
// panel is unreachable, and one place where it is throttled when the panel says slow
// down.
type StatSample struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// When the node took the reading, not when the panel received it. A sample that
	// arrives after a reconnect is still worth storing at the time it describes.
	TakenAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	// How long this sample covers. The denominator for every counter below; without it a
	// gap in the stream turns into a spike in the chart.
	IntervalNanos int64 `protobuf:"varint,3,opt,name=interval_nanos,json=intervalNanos,proto3" json:"interval_nanos,omitempty"`
	// Types that are valid to be assigned to Subject:
	//
	//	*StatSample_Node
	//	*StatSample_Workload
	Subject       isStatSample_Subject `protobuf_oneof:"subject"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatSample) Reset() {
	*x = StatSample{}
	mi := &file_wisper_v1_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatSample) ProtoMessage() {}

func (x *StatSample) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatSample.ProtoReflect.Descriptor instead.
func (*StatSample) Descriptor() ([]byte, []int) {
	return file_wisper_v1_stats_proto_rawDescGZIP(), []int{0}
}

func (x *StatSample) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatSample) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *StatSample) GetIntervalNanos() int64 {
	if x != nil {
		return x.IntervalNanos
	}
	return 0
}

func (x *StatSample) GetSubject() isStatSample_Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *StatSample) GetNode() *NodeSample {
	if x != nil {
		if x, ok := x.Subject.(*StatSample_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *StatSample) GetWorkload() *WorkloadSample {
	if x != nil {
		if x, ok := x.Subject.(*StatSample_Workload); ok {
			return x.Workload
		}
	}
	return nil
}

type isStatSample_Subject interface {
	isStatSample_Subject()
}

type StatSample_Node struct {
	Node *NodeSample `protobuf:"bytes,4,opt,name=node,proto3,oneof"`
}

type StatSample_Workload struct {
	Workload *WorkloadSample `protobuf:"bytes,5,opt,name=workload,proto3,oneof"`
}

func (*StatSample_Node) isStatSample_Subject() {}

func (*StatSample_Workload) isStatSample_Subject() {}

// The machine as a whole. Placement reads the latest of these to decide whether a node
// has room, so the fields are the ones headroom is computed from (design section 7.6).
type NodeSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cumulative CPU nanoseconds burned by everything on the machine.
	CpuNanos int64 `protobuf:"varint,1,opt,name=cpu_nanos,json=cpuNanos,proto3" json:"cpu_nanos,omitempty"`
	// What the machine has to burn: cores * interval_nanos. The pair gives a utilisation
	// the panel can compute without knowing the core count from somewhere else.
	CpuCapacityNanos int64 `protobuf:"varint,2,opt,name=cpu_capacity_nanos,json=cpuCapacityNanos,proto3" json:"cpu_capacity_nanos,omitempty"`
	MemoryUsedBytes  int64 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	// Excludes reclaimable cache. "Used" including cache makes every healthy Linux box
	// look like it is about to die.
	MemoryAvailableBytes int64 `protobuf:"varint,5,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"`
	DiskUsedBytes        int64 `protobuf:"varint,6,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes       int64 `protobuf:"varint,7,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	// Cumulative, from the node's primary interface.
	NetworkRxBytes int64 `protobuf:"varint,8,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes int64 `protobuf:"varint,9,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	// The one genuinely fractional quantity here, and one that is never summed across
	// samples, so it is the one float in this file.
	LoadAverage_1M    float64 `protobuf:"fixed64,10,opt,name=load_average_1m,json=loadAverage1m,proto3" json:"load_average_1m,omitempty"`
	RunningContainers int32   `protobuf:"varint,11,opt,name=running_containers,json=runningContainers,proto3" json:"running_containers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeSample) Reset() {
	*x = NodeSample{}
	mi := &file_wisper_v1_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSample) ProtoMessage() {}

func (x *NodeSample) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSample.ProtoReflect.Descriptor instead.
func (*NodeSample) Descriptor() ([]byte, []int) {
	return file_wisper_v1_stats_proto_rawDescGZIP(), []int{1}
}

func (x *NodeSample) GetCpuNanos() int64 {
	if x != nil {
		return x.CpuNanos
	}
	return 0
}

func (x *NodeSample) GetCpuCapacityNanos() int64 {
	if x != nil {
		return x.CpuCapacityNanos
	}
	return 0
}

func (x *NodeSample) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeSample) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeSample) GetMemoryAvailableBytes() int64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

func (x *NodeSample) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *NodeSample) GetDiskTotalBytes() int64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *NodeSample) GetNetworkRxBytes() int64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *NodeSample) GetNetworkTxBytes() int64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *NodeSample) GetLoadAverage_1M() float64 {
	if x != nil {
		return x.LoadAverage_1M
	}
	return 0
}

func (x *NodeSample) GetRunningContainers() int32 {
	if x != nil {
		return x.RunningContainers
	}
	return 0
}

// One workload's resource use, read from the container's cgroup.
type WorkloadSample struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	// Cumulative CPU nanoseconds. Divided by interval_nanos this is cores used; divided
	// by the limit it is the number the customer sees.
	CpuNanos int64 `protobuf:"varint,2,opt,name=cpu_nanos,json=cpuNanos,proto3" json:"cpu_nanos,omitempty"`
	// The ceiling in effect, echoed so a chart can draw the limit line without joining
	// against the spec - and so a limit that changed mid-window is visible.
	CpuLimitNanoCpus int64 `protobuf:"varint,3,opt,name=cpu_limit_nano_cpus,json=cpuLimitNanoCpus,proto3" json:"cpu_limit_nano_cpus,omitempty"`
	MemoryUsedBytes  int64 `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryLimitBytes int64 `protobuf:"varint,5,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	// Peak since the container started. The number that explains an OOM kill after the
	// fact, which the current reading never does.
	MemoryPeakBytes int64 `protobuf:"varint,6,opt,name=memory_peak_bytes,json=memoryPeakBytes,proto3" json:"memory_peak_bytes,omitempty"`
	NetworkRxBytes  int64 `protobuf:"varint,7,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes  int64 `protobuf:"varint,8,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	BlockReadBytes  int64 `protobuf:"varint,9,opt,name=block_read_bytes,json=blockReadBytes,proto3" json:"block_read_bytes,omitempty"`
	BlockWriteBytes int64 `protobuf:"varint,10,opt,name=block_write_bytes,json=blockWriteBytes,proto3" json:"block_write_bytes,omitempty"`
	Pids            int32 `protobuf:"varint,11,opt,name=pids,proto3" json:"pids,omitempty"`
	// Bytes on this workload's volumes, measured against the quota. Sampled rather than
	// computed on demand because walking a customer's tree is expensive and a quota bar
	// is on every page.
	DiskUsedBytes  int64 `protobuf:"varint,12,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskQuotaBytes int64 `protobuf:"varint,13,opt,name=disk_quota_bytes,json=diskQuotaBytes,proto3" json:"disk_quota_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkloadSample) Reset() {
	*x = WorkloadSample{}
	mi := &file_wisper_v1_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSample) ProtoMessage() {}

func (x *WorkloadSample) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSample.ProtoReflect.Descriptor instead.
func (*WorkloadSample) Descriptor() ([]byte, []int) {
	return file_wisper_v1_stats_proto_rawDescGZIP(), []int{2}
}

func (x *WorkloadSample) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadSample) GetCpuNanos() int64 {
	if x != nil {
		return x.CpuNanos
	}
	return 0
}

func (x *WorkloadSample) GetCpuLimitNanoCpus() int64 {
	if x != nil {
		return x.CpuLimitNanoCpus
	}
	return 0
}

func (x *WorkloadSample) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *WorkloadSample) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *WorkloadSample) GetMemoryPeakBytes() int64 {
	if x != nil {
		return x.MemoryPeakBytes
	}
	return 0
}

func (x *WorkloadSample) GetNetworkRxBytes() int64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *WorkloadSample) GetNetworkTxBytes() int64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *WorkloadSample) GetBlockReadBytes() int64 {
	if x != nil {
		return x.BlockReadBytes
	}
	return 0
}

func (x *WorkloadSample) GetBlockWriteBytes() int64 {
	if x != nil {
		return x.BlockWriteBytes
	}
	return 0
}

func (x *WorkloadSample) GetPids() int32 {
	if x != nil {
		return x.Pids
	}
	return 0
}

func (x *WorkloadSample) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *WorkloadSample) GetDiskQuotaBytes() int64 {
	if x != nil {
		return x.DiskQuotaBytes
	}
	return 0
}

// The panel asking a node to start sending logs, pushed down the control stream.
//
// A command rather than an RPC the panel calls, because the panel cannot call a node.
// The node answers by pushing LogChunks carrying this stream_id up the LogStream call it
// already has open.
type LogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The panel's handle for this subscription. Every chunk carries it back, so one
	// LogStream call can serve a customer watching a deployment and an operator tailing a
	// container at the same time.
	StreamId string    `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Source   LogSource `protobuf:"varint,2,opt,name=source,proto3,enum=wisper.v1.LogSource" json:"source,omitempty"`
	// Workload id, build id or cron run id, depending on the source. Ignored for
	// LOG_SOURCE_SYSTEM.
	SubjectId string `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// History to send before following. A customer who opens a log page wants the last
	// screen immediately, not to wait for the next line.
	TailLines int32 `protobuf:"varint,4,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	// Keep sending until told to stop. False is a one-shot fetch for a build that has
	// already finished.
	Follow bool `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	// Only lines after this. Set when the browser reconnects, so the customer does not
	// get the last hundred lines twice.
	Since         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_wisper_v1_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_wisper_v1_stats_proto_rawDescGZIP(), []int{3}
}

func (x *LogRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LogRequest) GetSource() LogSource {
	if x != nil {
		return x.Source
	}
	return LogSource_LOG_SOURCE_UNSPECIFIED
}

func (x *LogRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *LogRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

// Stop one subscription. Sent when the last browser watching it goes away, because a
// node tailing a chatty container nobody is reading is bandwidth spent on nothing.
type StopLogStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLogStream) Reset() {
	*x = StopLogStream{}
	mi := &file_wisper_v1_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLogStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLogStream) ProtoMessage() {}

func (x *StopLogStream) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLogStream.ProtoReflect.Descriptor instead.
func (*StopLogStream) Descriptor() ([]byte, []int) {
	return file_wisper_v1_stats_proto_rawDescGZIP(), []int{4}
}

func (x *StopLogStream) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StopLogStream) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// A run of log output.
//
// Chunks, not lines: a container writes a partial line and then thinks for ten seconds,
// and buffering until a newline arrives makes a build look hung. The panel reassembles
// lines for storage; the browser renders whatever has arrived.
type LogChunk struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StreamId  string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Source    LogSource              `protobuf:"varint,2,opt,name=source,proto3,enum=wisper.v1.LogSource" json:"source,omitempty"`
	SubjectId string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Kind      LogStreamKind          `protobuf:"varint,4,opt,name=kind,proto3,enum=wisper.v1.LogStreamKind" json:"kind,omitempty"`
	// Bytes rather than a string, for the same reason terminal data is: a log line can be
	// invalid UTF-8, and a chunk boundary can fall inside a multi-byte character.
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// The node's timestamp for the first byte in this chunk.
	At *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=at,proto3" json:"at,omitempty"`
	// The node dropped output rather than block the container writing it. A customer told
	// that lines are missing can act; a customer shown a gap cannot (design section 7.6).
	DroppedBytes int64 `protobuf:"varint,7,opt,name=dropped_bytes,json=droppedBytes,proto3" json:"dropped_bytes,omitempty"`
	// The source ended: the container exited, the build finished, the cron run returned.
	// The subscription is over and the panel can release it without a stop command.
	End           bool `protobuf:"varint,8,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_wisper_v1_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_wisper_v1_stats_proto_rawDescGZIP(), []int{5}
}

func (x *LogChunk) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LogChunk) GetSource() LogSource {
	if x != nil {
		return x.Source
	}
	return LogSource_LOG_SOURCE_UNSPECIFIED
}

func (x *LogChunk) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *LogChunk) GetKind() LogStreamKind {
	if x != nil {
		return x.Kind
	}
	return LogStreamKind_LOG_STREAM_KIND_UNSPECIFIED
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *LogChunk) GetDroppedBytes() int64 {
	if x != nil {
		return x.DroppedBytes
	}
	return 0
}

func (x *LogChunk) GetEnd() bool {
	if x != nil {
		return x.End
	}
	return false
}

var File_wisper_v1_stats_proto protoreflect.FileDescriptor

const file_wisper_v1_stats_proto_rawDesc = "" +
	"\n" +
	"\x15wisper/v1/stats.proto\x12\twisper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n" +
	"\n" +
	"StatSample\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x125\n" +
	"\btaken_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12%\n" +
	"\x0einterval_nanos\x18\x03 \x01(\x03R\rintervalNanos\x12+\n" +
	"\x04node\x18\x04 \x01(\v2\x15.wisper.v1.NodeSampleH\x00R\x04node\x127\n" +
	"\bworkload\x18\x05 \x01(\v2\x19.wisper.v1.WorkloadSampleH\x00R\bworkloadB\t\n" +
	"\asubject\"\xe4\x03\n" +
	"\n" +
	"NodeSample\x12\x1b\n" +
	"\tcpu_nanos\x18\x01 \x01(\x03R\bcpuNanos\x12,\n" +
	"\x12cpu_capacity_nanos\x18\x02 \x01(\x03R\x10cpuCapacityNanos\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x03R\x10memoryTotalBytes\x124\n" +
	"\x16memory_available_bytes\x18\x05 \x01(\x03R\x14memoryAvailableBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x06 \x01(\x03R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\a \x01(\x03R\x0ediskTotalBytes\x12(\n" +
	"\x10network_rx_bytes\x18\b \x01(\x03R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\t \x01(\x03R\x0enetworkTxBytes\x12&\n" +
	"\x0fload_average_1m\x18\n" +
	" \x01(\x01R\rloadAverage1m\x12-\n" +
	"\x12running_containers\x18\v \x01(\x05R\x11runningContainers\"\x93\x04\n" +
	"\x0eWorkloadSample\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x1b\n" +
	"\tcpu_nanos\x18\x02 \x01(\x03R\bcpuNanos\x12-\n" +
	"\x13cpu_limit_nano_cpus\x18\x03 \x01(\x03R\x10cpuLimitNanoCpus\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x05 \x01(\x03R\x10memoryLimitBytes\x12*\n" +
	"\x11memory_peak_bytes\x18\x06 \x01(\x03R\x0fmemoryPeakBytes\x12(\n" +
	"\x10network_rx_bytes\x18\a \x01(\x03R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\b \x01(\x03R\x0enetworkTxBytes\x12(\n" +
	"\x10block_read_bytes\x18\t \x01(\x03R\x0eblockReadBytes\x12*\n" +
	"\x11block_write_bytes\x18\n" +
	" \x01(\x03R\x0fblockWriteBytes\x12\x12\n" +
	"\x04pids\x18\v \x01(\x05R\x04pids\x12&\n" +
	"\x0fdisk_used_bytes\x18\f \x01(\x03R\rdiskUsedBytes\x12(\n" +
	"\x10disk_quota_bytes\x18\r \x01(\x03R\x0ediskQuotaBytes\"\xdf\x01\n" +
	"\n" +
	"LogRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12,\n" +
	"\x06source\x18\x02 \x01(\x0e2\x14.wisper.v1.LogSourceR\x06source\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x04 \x01(\x05R\ttailLines\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\x120\n" +
	"\x05since\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"D\n" +
	"\rStopLogStream\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x99\x02\n" +
	"\bLogChunk\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12,\n" +
	"\x06source\x18\x02 \x01(\x0e2\x14.wisper.v1.LogSourceR\x06source\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12,\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x18.wisper.v1.LogStreamKindR\x04kind\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12*\n" +
	"\x02at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12#\n" +
	"\rdropped_bytes\x18\a \x01(\x03R\fdroppedBytes\x12\x10\n" +
	"\x03end\x18\b \x01(\bR\x03end*\x83\x01\n" +
	"\tLogSource\x12\x1a\n" +
	"\x16LOG_SOURCE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LOG_SOURCE_CONTAINER\x10\x01\x12\x14\n" +
	"\x10LOG_SOURCE_BUILD\x10\x02\x12\x13\n" +
	"\x0fLOG_SOURCE_CRON\x10\x03\x12\x15\n" +
	"\x11LOG_SOURCE_SYSTEM\x10\x04*h\n" +
	"\rLogStreamKind\x12\x1f\n" +
	"\x1bLOG_STREAM_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LOG_STREAM_KIND_STDOUT\x10\x01\x12\x1a\n" +
	"\x16LOG_STREAM_KIND_STDERR\x10\x02Bk\n" +
	"\x1clhqm.furimeo.wisper.proto.v1B\n" +
	"StatsProtoP\x01Z=github.com/furimeo/wisper/sasayaki/internal/wisperpb;wisperpbb\x06proto3"

var (
	file_wisper_v1_stats_proto_rawDescOnce sync.Once
	file_wisper_v1_stats_proto_rawDescData []byte
)

func file_wisper_v1_stats_proto_rawDescGZIP() []byte {
	file_wisper_v1_stats_proto_rawDescOnce.Do(func() {
		file_wisper_v1_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wisper_v1_stats_proto_rawDesc), len(file_wisper_v1_stats_proto_rawDesc)))
	})
	return file_wisper_v1_stats_proto_rawDescData
}

var file_wisper_v1_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wisper_v1_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wisper_v1_stats_proto_goTypes = []any{
	(LogSource)(0),                // 0: wisper.v1.LogSource
	(LogStreamKind)(0),            // 1: wisper.v1.LogStreamKind
	(*StatSample)(nil),            // 2: wisper.v1.StatSample
	(*NodeSample)(nil),            // 3: wisper.v1.NodeSample
	(*WorkloadSample)(nil),        // 4: wisper.v1.WorkloadSample
	(*LogRequest)(nil),            // 5: wisper.v1.LogRequest
	(*StopLogStream)(nil),         // 6: wisper.v1.StopLogStream
	(*LogChunk)(nil),              // 7: wisper.v1.LogChunk
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_wisper_v1_stats_proto_depIdxs = []int32{
	8, // 0: wisper.v1.StatSample.taken_at:type_name -> google.protobuf.Timestamp
	3, // 1: wisper.v1.StatSample.node:type_name -> wisper.v1.NodeSample
	4, // 2: wisper.v1.StatSample.workload:type_name -> wisper.v1.WorkloadSample
	0, // 3: wisper.v1.LogRequest.source:type_name -> wisper.v1.LogSource
	8, // 4: wisper.v1.LogRequest.since:type_name -> google.protobuf.Timestamp
	0, // 5: wisper.v1.LogChunk.source:type_name -> wisper.v1.LogSource
	1, // 6: wisper.v1.LogChunk.kind:type_name -> wisper.v1.LogStreamKind
	8, // 7: wisper.v1.LogChunk.at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_wisper_v1_stats_proto_init() }
func file_wisper_v1_stats_proto_init() {
	if File_wisper_v1_stats_proto != nil {
		return
	}
	file_wisper_v1_stats_proto_msgTypes[0].OneofWrappers = []any{
		(*StatSample_Node)(nil),
		(*StatSample_Workload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wisper_v1_stats_proto_rawDesc), len(file_wisper_v1_stats_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wisper_v1_stats_proto_goTypes,
		DependencyIndexes: file_wisper_v1_stats_proto_depIdxs,
		EnumInfos:         file_wisper_v1_stats_proto_enumTypes,
		MessageInfos:      file_wisper_v1_stats_proto_msgTypes,
	}.Build()
	File_wisper_v1_stats_proto = out.File
	file_wisper_v1_stats_proto_goTypes = nil
	file_wisper_v1_stats_proto_depIdxs = nil
}
