// The web terminal: one framed, bidirectional stream between the browser's xterm.js,
// the panel and a PTY inside a customer's container.
//
// This file exists as its own contract because of exactly one bug. The predecessor
// pumped a PTY through a WebSocket with io.Copy and no framing, so a resize was
// indistinguishable from keystrokes, a chunk boundary could split an escape sequence,
// and the exit code was lost - the terminal simply stopped. Every frame here therefore
// says what it is, and nothing on this stream is ever a bare byte slice with an implied
// meaning (design section 3, section 11.5).
//
// There is no SSH and no SFTP anywhere in wisper. This is the only shell a customer
// gets, and most of them are holding a phone while they use it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wisper/v1/terminal.proto

package wisperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The panel telling a node to open a PTY, pushed down the control stream.
//
// It is a command rather than a request on the terminal stream itself because the node
// is the only side that can open a connection: the panel decides a terminal should
// exist, and the node dials back with the stream that carries it.
type StartTerminal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minted by the panel when the customer opens the page. It ties the browser's SSE or
	// WebSocket connection, the gRPC stream and the audit record together, and every
	// frame carries it so a stray frame from an abandoned session is dropped rather than
	// typed into somebody else's shell.
	SessionId  string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkloadId string `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	// argv for the process to run. Empty means the image's shell; the panel resolves that
	// rather than the node guessing, so the customer sees the same shell twice running.
	Command    []string `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	WorkingDir string   `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// uid[:gid]. A terminal that is root inside the container when the workload is not
	// lets a customer create files their own application cannot read.
	User string `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	// Extra variables for this session only - TERM, COLUMNS, LANG. The workload's own
	// environment is already there; this is what the terminal adds on top.
	Env map[string]string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The browser's size at open time, so the first prompt is not drawn at 80x24 and then
	// immediately redrawn.
	InitialCols uint32 `protobuf:"varint,7,opt,name=initial_cols,json=initialCols,proto3" json:"initial_cols,omitempty"`
	InitialRows uint32 `protobuf:"varint,8,opt,name=initial_rows,json=initialRows,proto3" json:"initial_rows,omitempty"`
	// The PTY is killed after this long with no input. A forgotten tab is otherwise a
	// shell running as the customer's application, for weeks.
	IdleTimeoutSeconds int64 `protobuf:"varint,9,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	// Hard ceiling on the whole session regardless of activity, so a wedged `top` cannot
	// hold a slot forever.
	MaxDurationSeconds int64 `protobuf:"varint,10,opt,name=max_duration_seconds,json=maxDurationSeconds,proto3" json:"max_duration_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartTerminal) Reset() {
	*x = StartTerminal{}
	mi := &file_wisper_v1_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTerminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTerminal) ProtoMessage() {}

func (x *StartTerminal) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTerminal.ProtoReflect.Descriptor instead.
func (*StartTerminal) Descriptor() ([]byte, []int) {
	return file_wisper_v1_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *StartTerminal) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartTerminal) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *StartTerminal) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartTerminal) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *StartTerminal) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StartTerminal) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartTerminal) GetInitialCols() uint32 {
	if x != nil {
		return x.InitialCols
	}
	return 0
}

func (x *StartTerminal) GetInitialRows() uint32 {
	if x != nil {
		return x.InitialRows
	}
	return 0
}

func (x *StartTerminal) GetIdleTimeoutSeconds() int64 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *StartTerminal) GetMaxDurationSeconds() int64 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

// One frame in either direction on the Terminal stream.
//
// One stream carries one session. Multiplexing several would share one HTTP/2 flow
// control window between them, so a customer running `yes` in one tab would stall the
// other - and gRPC already gives a stream per call for free.
type TerminalFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Present on every frame, including the ones where the stream identity is already
	// implied. It costs a few bytes and it turns a routing mistake into a dropped frame
	// instead of input delivered to the wrong container.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TerminalFrame_Attached
	//	*TerminalFrame_Data
	//	*TerminalFrame_Resize
	//	*TerminalFrame_Exit
	Payload       isTerminalFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalFrame) Reset() {
	*x = TerminalFrame{}
	mi := &file_wisper_v1_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalFrame) ProtoMessage() {}

func (x *TerminalFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalFrame.ProtoReflect.Descriptor instead.
func (*TerminalFrame) Descriptor() ([]byte, []int) {
	return file_wisper_v1_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *TerminalFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalFrame) GetPayload() isTerminalFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TerminalFrame) GetAttached() *TerminalAttached {
	if x != nil {
		if x, ok := x.Payload.(*TerminalFrame_Attached); ok {
			return x.Attached
		}
	}
	return nil
}

func (x *TerminalFrame) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TerminalFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TerminalFrame) GetResize() *TerminalResize {
	if x != nil {
		if x, ok := x.Payload.(*TerminalFrame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *TerminalFrame) GetExit() *TerminalExit {
	if x != nil {
		if x, ok := x.Payload.(*TerminalFrame_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isTerminalFrame_Payload interface {
	isTerminalFrame_Payload()
}

type TerminalFrame_Attached struct {
	// Node to panel, first frame only. The terminal stream is opened by the node in
	// response to StartTerminal, so the panel has to be told which session just arrived
	// before it can join it to the waiting browser.
	Attached *TerminalAttached `protobuf:"bytes,2,opt,name=attached,proto3,oneof"`
}

type TerminalFrame_Data struct {
	// Both directions. Keystrokes going down, PTY output coming up.
	//
	// Bytes, never a string: a PTY emits whatever the program writes, which is
	// routinely an escape sequence split across a read boundary and occasionally not
	// valid UTF-8 at all. Decoding is the browser's job, once, at the end.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type TerminalFrame_Resize struct {
	// Panel to node. The browser rotated, the on-screen keyboard opened, the window
	// changed. Without this frame type, curses applications draw over themselves and a
	// phone user sees a broken screen (design section 11.5).
	Resize *TerminalResize `protobuf:"bytes,4,opt,name=resize,proto3,oneof"`
}

type TerminalFrame_Exit struct {
	// Node to panel, last frame. The shell exited and this says why, so the UI can show
	// "exited 130" instead of a terminal that just stopped responding.
	Exit *TerminalExit `protobuf:"bytes,5,opt,name=exit,proto3,oneof"`
}

func (*TerminalFrame_Attached) isTerminalFrame_Payload() {}

func (*TerminalFrame_Data) isTerminalFrame_Payload() {}

func (*TerminalFrame_Resize) isTerminalFrame_Payload() {}

func (*TerminalFrame_Exit) isTerminalFrame_Payload() {}

// The node's acknowledgement that the PTY is open and bytes are about to flow.
type TerminalAttached struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	// The container the PTY lives in, so an operator can correlate a session in the audit
	// log with what Docker saw.
	ContainerId string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Echoed back after being clamped: a browser can ask for a size the PTY will not
	// accept, and the client needs to know what it actually got.
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	AttachedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=attached_at,json=attachedAt,proto3" json:"attached_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalAttached) Reset() {
	*x = TerminalAttached{}
	mi := &file_wisper_v1_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalAttached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalAttached) ProtoMessage() {}

func (x *TerminalAttached) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalAttached.ProtoReflect.Descriptor instead.
func (*TerminalAttached) Descriptor() ([]byte, []int) {
	return file_wisper_v1_terminal_proto_rawDescGZIP(), []int{2}
}

func (x *TerminalAttached) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *TerminalAttached) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *TerminalAttached) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalAttached) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalAttached) GetAttachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttachedAt
	}
	return nil
}

// A window size change. Sent whenever the browser's terminal element resizes, which on
// a phone is every time the keyboard opens.
type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_wisper_v1_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_wisper_v1_terminal_proto_rawDescGZIP(), []int{3}
}

func (x *TerminalResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Why the session ended.
type TerminalExit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The process's exit status, or 128+signal when it was killed - the shell convention,
	// so 130 reads as Ctrl-C to anybody who has used one.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Set when the session was ended by the platform rather than by the process: the idle
	// timeout fired, the workload was stopped, the container went away.
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalExit) Reset() {
	*x = TerminalExit{}
	mi := &file_wisper_v1_terminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalExit) ProtoMessage() {}

func (x *TerminalExit) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_terminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalExit.ProtoReflect.Descriptor instead.
func (*TerminalExit) Descriptor() ([]byte, []int) {
	return file_wisper_v1_terminal_proto_rawDescGZIP(), []int{4}
}

func (x *TerminalExit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TerminalExit) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TerminalExit) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

var File_wisper_v1_terminal_proto protoreflect.FileDescriptor

const file_wisper_v1_terminal_proto_rawDesc = "" +
	"\n" +
	"\x18wisper/v1/terminal.proto\x12\twisper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x03\n" +
	"\rStartTerminal\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x123\n" +
	"\x03env\x18\x06 \x03(\v2!.wisper.v1.StartTerminal.EnvEntryR\x03env\x12!\n" +
	"\finitial_cols\x18\a \x01(\rR\vinitialCols\x12!\n" +
	"\finitial_rows\x18\b \x01(\rR\vinitialRows\x120\n" +
	"\x14idle_timeout_seconds\x18\t \x01(\x03R\x12idleTimeoutSeconds\x120\n" +
	"\x14max_duration_seconds\x18\n" +
	" \x01(\x03R\x12maxDurationSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x01\n" +
	"\rTerminalFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\battached\x18\x02 \x01(\v2\x1b.wisper.v1.TerminalAttachedH\x00R\battached\x12\x14\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04data\x123\n" +
	"\x06resize\x18\x04 \x01(\v2\x19.wisper.v1.TerminalResizeH\x00R\x06resize\x12-\n" +
	"\x04exit\x18\x05 \x01(\v2\x17.wisper.v1.TerminalExitH\x00R\x04exitB\t\n" +
	"\apayload\"\xbb\x01\n" +
	"\x10TerminalAttached\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\x12;\n" +
	"\vattached_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"attachedAt\"8\n" +
	"\x0eTerminalResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"q\n" +
	"\fTerminalExit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x125\n" +
	"\bended_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAtBn\n" +
	"\x1clhqm.furimeo.wisper.proto.v1B\rTerminalProtoP\x01Z=github.com/furimeo/wisper/sasayaki/internal/wisperpb;wisperpbb\x06proto3"

var (
	file_wisper_v1_terminal_proto_rawDescOnce sync.Once
	file_wisper_v1_terminal_proto_rawDescData []byte
)

func file_wisper_v1_terminal_proto_rawDescGZIP() []byte {
	file_wisper_v1_terminal_proto_rawDescOnce.Do(func() {
		file_wisper_v1_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wisper_v1_terminal_proto_rawDesc), len(file_wisper_v1_terminal_proto_rawDesc)))
	})
	return file_wisper_v1_terminal_proto_rawDescData
}

var file_wisper_v1_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wisper_v1_terminal_proto_goTypes = []any{
	(*StartTerminal)(nil),         // 0: wisper.v1.StartTerminal
	(*TerminalFrame)(nil),         // 1: wisper.v1.TerminalFrame
	(*TerminalAttached)(nil),      // 2: wisper.v1.TerminalAttached
	(*TerminalResize)(nil),        // 3: wisper.v1.TerminalResize
	(*TerminalExit)(nil),          // 4: wisper.v1.TerminalExit
	nil,                           // 5: wisper.v1.StartTerminal.EnvEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_wisper_v1_terminal_proto_depIdxs = []int32{
	5, // 0: wisper.v1.StartTerminal.env:type_name -> wisper.v1.StartTerminal.EnvEntry
	2, // 1: wisper.v1.TerminalFrame.attached:type_name -> wisper.v1.TerminalAttached
	3, // 2: wisper.v1.TerminalFrame.resize:type_name -> wisper.v1.TerminalResize
	4, // 3: wisper.v1.TerminalFrame.exit:type_name -> wisper.v1.TerminalExit
	6, // 4: wisper.v1.TerminalAttached.attached_at:type_name -> google.protobuf.Timestamp
	6, // 5: wisper.v1.TerminalExit.ended_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_wisper_v1_terminal_proto_init() }
func file_wisper_v1_terminal_proto_init() {
	if File_wisper_v1_terminal_proto != nil {
		return
	}
	file_wisper_v1_terminal_proto_msgTypes[1].OneofWrappers = []any{
		(*TerminalFrame_Attached)(nil),
		(*TerminalFrame_Data)(nil),
		(*TerminalFrame_Resize)(nil),
		(*TerminalFrame_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wisper_v1_terminal_proto_rawDesc), len(file_wisper_v1_terminal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wisper_v1_terminal_proto_goTypes,
		DependencyIndexes: file_wisper_v1_terminal_proto_depIdxs,
		MessageInfos:      file_wisper_v1_terminal_proto_msgTypes,
	}.Build()
	File_wisper_v1_terminal_proto = out.File
	file_wisper_v1_terminal_proto_goTypes = nil
	file_wisper_v1_terminal_proto_depIdxs = nil
}
