// The NodeSpec: everything a node must be running, and the status it reports back.
//
// This is the whole of "desired state, not imperative RPC" (design section 5.1). The
// panel never says "start container X"; it says "at generation 47 this node holds these
// workloads, routes, engines, grants and cron entries", writes that to the node, and
// the reconcile loop closes the gap every fifteen seconds whether or not anything
// happened. A daemon that lost its memory reads the last spec off its own disk and
// converges again.
//
// Over 300 lines, and split further only at a cost: the spec is one document that is
// written, hashed, stored and diffed as a unit, and separating the shape of a workload
// from the shape of the spec that contains it would put two halves of one edit in two
// files. The statuses live here for the same reason - a status is the observed form of
// exactly one of the things declared above it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wisper/v1/workload.proto

package wisperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// app runs a container; site is a directory of files served by the embedded Caddy with
// no process at all, which is what makes an idle static site cost nothing (design
// section 5.5).
type WorkloadKind int32

const (
	WorkloadKind_WORKLOAD_KIND_UNSPECIFIED WorkloadKind = 0
	WorkloadKind_WORKLOAD_KIND_APP         WorkloadKind = 1
	WorkloadKind_WORKLOAD_KIND_SITE        WorkloadKind = 2
)

// Enum value maps for WorkloadKind.
var (
	WorkloadKind_name = map[int32]string{
		0: "WORKLOAD_KIND_UNSPECIFIED",
		1: "WORKLOAD_KIND_APP",
		2: "WORKLOAD_KIND_SITE",
	}
	WorkloadKind_value = map[string]int32{
		"WORKLOAD_KIND_UNSPECIFIED": 0,
		"WORKLOAD_KIND_APP":         1,
		"WORKLOAD_KIND_SITE":        2,
	}
)

func (x WorkloadKind) Enum() *WorkloadKind {
	p := new(WorkloadKind)
	*p = x
	return p
}

func (x WorkloadKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[0].Descriptor()
}

func (WorkloadKind) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[0]
}

func (x WorkloadKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadKind.Descriptor instead.
func (WorkloadKind) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{0}
}

// Whether the workload should be up. Removing a workload is done by leaving it out of
// the spec; stopping one keeps its container, volumes and logs, which is what a
// customer expects from a pause button.
type DesiredState int32

const (
	DesiredState_DESIRED_STATE_UNSPECIFIED DesiredState = 0
	DesiredState_DESIRED_STATE_RUNNING     DesiredState = 1
	DesiredState_DESIRED_STATE_STOPPED     DesiredState = 2
)

// Enum value maps for DesiredState.
var (
	DesiredState_name = map[int32]string{
		0: "DESIRED_STATE_UNSPECIFIED",
		1: "DESIRED_STATE_RUNNING",
		2: "DESIRED_STATE_STOPPED",
	}
	DesiredState_value = map[string]int32{
		"DESIRED_STATE_UNSPECIFIED": 0,
		"DESIRED_STATE_RUNNING":     1,
		"DESIRED_STATE_STOPPED":     2,
	}
)

func (x DesiredState) Enum() *DesiredState {
	p := new(DesiredState)
	*p = x
	return p
}

func (x DesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[1].Descriptor()
}

func (DesiredState) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[1]
}

func (x DesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesiredState.Descriptor instead.
func (DesiredState) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{1}
}

// gVisor by default. runc exists per workload because io_uring and some older binaries
// do not work under runsc, and a platform with no escape hatch turns that into "your
// app is broken" (design section 11.6). The panel shows which one is really in use.
type ContainerRuntime int32

const (
	ContainerRuntime_CONTAINER_RUNTIME_UNSPECIFIED ContainerRuntime = 0
	ContainerRuntime_CONTAINER_RUNTIME_RUNSC       ContainerRuntime = 1
	ContainerRuntime_CONTAINER_RUNTIME_RUNC        ContainerRuntime = 2
)

// Enum value maps for ContainerRuntime.
var (
	ContainerRuntime_name = map[int32]string{
		0: "CONTAINER_RUNTIME_UNSPECIFIED",
		1: "CONTAINER_RUNTIME_RUNSC",
		2: "CONTAINER_RUNTIME_RUNC",
	}
	ContainerRuntime_value = map[string]int32{
		"CONTAINER_RUNTIME_UNSPECIFIED": 0,
		"CONTAINER_RUNTIME_RUNSC":       1,
		"CONTAINER_RUNTIME_RUNC":        2,
	}
)

func (x ContainerRuntime) Enum() *ContainerRuntime {
	p := new(ContainerRuntime)
	*p = x
	return p
}

func (x ContainerRuntime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerRuntime) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[2].Descriptor()
}

func (ContainerRuntime) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[2]
}

func (x ContainerRuntime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerRuntime.Descriptor instead.
func (ContainerRuntime) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{2}
}

type MountKind int32

const (
	MountKind_MOUNT_KIND_UNSPECIFIED MountKind = 0
	// A persistent directory under the node's state root, quota-managed and backed up.
	MountKind_MOUNT_KIND_VOLUME MountKind = 1
	// The site's current release, read-only. Lets an app container serve or post-process
	// the files a build produced without a second copy of them.
	MountKind_MOUNT_KIND_SITE_RELEASE MountKind = 2
	// RAM-backed scratch. Cheap way to give a read-only rootfs somewhere to write.
	MountKind_MOUNT_KIND_TMPFS MountKind = 3
)

// Enum value maps for MountKind.
var (
	MountKind_name = map[int32]string{
		0: "MOUNT_KIND_UNSPECIFIED",
		1: "MOUNT_KIND_VOLUME",
		2: "MOUNT_KIND_SITE_RELEASE",
		3: "MOUNT_KIND_TMPFS",
	}
	MountKind_value = map[string]int32{
		"MOUNT_KIND_UNSPECIFIED":  0,
		"MOUNT_KIND_VOLUME":       1,
		"MOUNT_KIND_SITE_RELEASE": 2,
		"MOUNT_KIND_TMPFS":        3,
	}
)

func (x MountKind) Enum() *MountKind {
	p := new(MountKind)
	*p = x
	return p
}

func (x MountKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[3].Descriptor()
}

func (MountKind) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[3]
}

func (x MountKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MountKind.Descriptor instead.
func (MountKind) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{3}
}

type PortProtocol int32

const (
	PortProtocol_PORT_PROTOCOL_UNSPECIFIED PortProtocol = 0
	PortProtocol_PORT_PROTOCOL_TCP         PortProtocol = 1
	PortProtocol_PORT_PROTOCOL_UDP         PortProtocol = 2
)

// Enum value maps for PortProtocol.
var (
	PortProtocol_name = map[int32]string{
		0: "PORT_PROTOCOL_UNSPECIFIED",
		1: "PORT_PROTOCOL_TCP",
		2: "PORT_PROTOCOL_UDP",
	}
	PortProtocol_value = map[string]int32{
		"PORT_PROTOCOL_UNSPECIFIED": 0,
		"PORT_PROTOCOL_TCP":         1,
		"PORT_PROTOCOL_UDP":         2,
	}
)

func (x PortProtocol) Enum() *PortProtocol {
	p := new(PortProtocol)
	*p = x
	return p
}

func (x PortProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[4].Descriptor()
}

func (PortProtocol) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[4]
}

func (x PortProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortProtocol.Descriptor instead.
func (PortProtocol) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{4}
}

type RestartPolicyMode int32

const (
	RestartPolicyMode_RESTART_POLICY_MODE_UNSPECIFIED RestartPolicyMode = 0
	RestartPolicyMode_RESTART_POLICY_MODE_NEVER       RestartPolicyMode = 1
	RestartPolicyMode_RESTART_POLICY_MODE_ON_FAILURE  RestartPolicyMode = 2
	RestartPolicyMode_RESTART_POLICY_MODE_ALWAYS      RestartPolicyMode = 3
	// Survives a daemon restart but not an explicit stop, which is what a customer who
	// pressed "stop" means.
	RestartPolicyMode_RESTART_POLICY_MODE_UNLESS_STOPPED RestartPolicyMode = 4
)

// Enum value maps for RestartPolicyMode.
var (
	RestartPolicyMode_name = map[int32]string{
		0: "RESTART_POLICY_MODE_UNSPECIFIED",
		1: "RESTART_POLICY_MODE_NEVER",
		2: "RESTART_POLICY_MODE_ON_FAILURE",
		3: "RESTART_POLICY_MODE_ALWAYS",
		4: "RESTART_POLICY_MODE_UNLESS_STOPPED",
	}
	RestartPolicyMode_value = map[string]int32{
		"RESTART_POLICY_MODE_UNSPECIFIED":    0,
		"RESTART_POLICY_MODE_NEVER":          1,
		"RESTART_POLICY_MODE_ON_FAILURE":     2,
		"RESTART_POLICY_MODE_ALWAYS":         3,
		"RESTART_POLICY_MODE_UNLESS_STOPPED": 4,
	}
)

func (x RestartPolicyMode) Enum() *RestartPolicyMode {
	p := new(RestartPolicyMode)
	*p = x
	return p
}

func (x RestartPolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartPolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[5].Descriptor()
}

func (RestartPolicyMode) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[5]
}

func (x RestartPolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartPolicyMode.Descriptor instead.
func (RestartPolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{5}
}

// On-demand issuance is the normal case: the certificate is fetched the first time a
// visitor arrives for a domain the in-process route table already knows, so it works
// while the panel is down (design section 5.4).
type TlsMode int32

const (
	TlsMode_TLS_MODE_UNSPECIFIED TlsMode = 0
	TlsMode_TLS_MODE_ON_DEMAND   TlsMode = 1
	// Plain HTTP. For a domain whose DNS still points somewhere else, so the customer can
	// verify the site before cutting over and before ACME starts failing at them.
	TlsMode_TLS_MODE_DISABLED TlsMode = 2
)

// Enum value maps for TlsMode.
var (
	TlsMode_name = map[int32]string{
		0: "TLS_MODE_UNSPECIFIED",
		1: "TLS_MODE_ON_DEMAND",
		2: "TLS_MODE_DISABLED",
	}
	TlsMode_value = map[string]int32{
		"TLS_MODE_UNSPECIFIED": 0,
		"TLS_MODE_ON_DEMAND":   1,
		"TLS_MODE_DISABLED":    2,
	}
)

func (x TlsMode) Enum() *TlsMode {
	p := new(TlsMode)
	*p = x
	return p
}

func (x TlsMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TlsMode) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[6].Descriptor()
}

func (TlsMode) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[6]
}

func (x TlsMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TlsMode.Descriptor instead.
func (TlsMode) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{6}
}

type FileRootKind int32

const (
	FileRootKind_FILE_ROOT_KIND_UNSPECIFIED FileRootKind = 0
	// A workload volume: what the customer thinks of as their disk.
	FileRootKind_FILE_ROOT_KIND_VOLUME FileRootKind = 1
	// The site's releases tree, so a customer can look at what a build actually produced.
	FileRootKind_FILE_ROOT_KIND_SITE FileRootKind = 2
	// Where the panel pushes archives before it asks for a build. Not shown to customers;
	// it exists because a node can reach the panel's gRPC endpoint and nothing else, so
	// an uploaded zip travels the same resumable path as any other upload.
	FileRootKind_FILE_ROOT_KIND_UPLOAD_STAGING FileRootKind = 3
)

// Enum value maps for FileRootKind.
var (
	FileRootKind_name = map[int32]string{
		0: "FILE_ROOT_KIND_UNSPECIFIED",
		1: "FILE_ROOT_KIND_VOLUME",
		2: "FILE_ROOT_KIND_SITE",
		3: "FILE_ROOT_KIND_UPLOAD_STAGING",
	}
	FileRootKind_value = map[string]int32{
		"FILE_ROOT_KIND_UNSPECIFIED":    0,
		"FILE_ROOT_KIND_VOLUME":         1,
		"FILE_ROOT_KIND_SITE":           2,
		"FILE_ROOT_KIND_UPLOAD_STAGING": 3,
	}
)

func (x FileRootKind) Enum() *FileRootKind {
	p := new(FileRootKind)
	*p = x
	return p
}

func (x FileRootKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileRootKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[7].Descriptor()
}

func (FileRootKind) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[7]
}

func (x FileRootKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileRootKind.Descriptor instead.
func (FileRootKind) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{7}
}

// Where a workload actually is. Phases the node can observe, not a mirror of Docker's
// own states, because "pulling" is what a customer is waiting on and Docker calls that
// "created".
type WorkloadPhase int32

const (
	WorkloadPhase_WORKLOAD_PHASE_UNSPECIFIED   WorkloadPhase = 0
	WorkloadPhase_WORKLOAD_PHASE_PENDING       WorkloadPhase = 1
	WorkloadPhase_WORKLOAD_PHASE_PULLING       WorkloadPhase = 2
	WorkloadPhase_WORKLOAD_PHASE_STARTING      WorkloadPhase = 3
	WorkloadPhase_WORKLOAD_PHASE_RUNNING       WorkloadPhase = 4
	WorkloadPhase_WORKLOAD_PHASE_UNHEALTHY     WorkloadPhase = 5
	WorkloadPhase_WORKLOAD_PHASE_STOPPED       WorkloadPhase = 6
	WorkloadPhase_WORKLOAD_PHASE_FAILED        WorkloadPhase = 7
	WorkloadPhase_WORKLOAD_PHASE_CRASH_LOOPING WorkloadPhase = 8
	// Docker did not answer. The container is probably fine and must not be touched:
	// mistaking "cannot see it" for "does not exist" is the fastest way to delete a
	// customer's data (AGENTS.md section 4.5).
	WorkloadPhase_WORKLOAD_PHASE_UNKNOWN WorkloadPhase = 9
)

// Enum value maps for WorkloadPhase.
var (
	WorkloadPhase_name = map[int32]string{
		0: "WORKLOAD_PHASE_UNSPECIFIED",
		1: "WORKLOAD_PHASE_PENDING",
		2: "WORKLOAD_PHASE_PULLING",
		3: "WORKLOAD_PHASE_STARTING",
		4: "WORKLOAD_PHASE_RUNNING",
		5: "WORKLOAD_PHASE_UNHEALTHY",
		6: "WORKLOAD_PHASE_STOPPED",
		7: "WORKLOAD_PHASE_FAILED",
		8: "WORKLOAD_PHASE_CRASH_LOOPING",
		9: "WORKLOAD_PHASE_UNKNOWN",
	}
	WorkloadPhase_value = map[string]int32{
		"WORKLOAD_PHASE_UNSPECIFIED":   0,
		"WORKLOAD_PHASE_PENDING":       1,
		"WORKLOAD_PHASE_PULLING":       2,
		"WORKLOAD_PHASE_STARTING":      3,
		"WORKLOAD_PHASE_RUNNING":       4,
		"WORKLOAD_PHASE_UNHEALTHY":     5,
		"WORKLOAD_PHASE_STOPPED":       6,
		"WORKLOAD_PHASE_FAILED":        7,
		"WORKLOAD_PHASE_CRASH_LOOPING": 8,
		"WORKLOAD_PHASE_UNKNOWN":       9,
	}
)

func (x WorkloadPhase) Enum() *WorkloadPhase {
	p := new(WorkloadPhase)
	*p = x
	return p
}

func (x WorkloadPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[8].Descriptor()
}

func (WorkloadPhase) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[8]
}

func (x WorkloadPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadPhase.Descriptor instead.
func (WorkloadPhase) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{8}
}

type CertificateState int32

const (
	CertificateState_CERTIFICATE_STATE_UNSPECIFIED CertificateState = 0
	CertificateState_CERTIFICATE_STATE_NONE        CertificateState = 1
	CertificateState_CERTIFICATE_STATE_ISSUING     CertificateState = 2
	CertificateState_CERTIFICATE_STATE_VALID       CertificateState = 3
	CertificateState_CERTIFICATE_STATE_FAILED      CertificateState = 4
)

// Enum value maps for CertificateState.
var (
	CertificateState_name = map[int32]string{
		0: "CERTIFICATE_STATE_UNSPECIFIED",
		1: "CERTIFICATE_STATE_NONE",
		2: "CERTIFICATE_STATE_ISSUING",
		3: "CERTIFICATE_STATE_VALID",
		4: "CERTIFICATE_STATE_FAILED",
	}
	CertificateState_value = map[string]int32{
		"CERTIFICATE_STATE_UNSPECIFIED": 0,
		"CERTIFICATE_STATE_NONE":        1,
		"CERTIFICATE_STATE_ISSUING":     2,
		"CERTIFICATE_STATE_VALID":       3,
		"CERTIFICATE_STATE_FAILED":      4,
	}
)

func (x CertificateState) Enum() *CertificateState {
	p := new(CertificateState)
	*p = x
	return p
}

func (x CertificateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateState) Descriptor() protoreflect.EnumDescriptor {
	return file_wisper_v1_workload_proto_enumTypes[9].Descriptor()
}

func (CertificateState) Type() protoreflect.EnumType {
	return &file_wisper_v1_workload_proto_enumTypes[9]
}

func (x CertificateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateState.Descriptor instead.
func (CertificateState) EnumDescriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{9}
}

// The full desired state of one node. Always sent whole, never as a delta: a stream
// through a tunnel drops, and a delta applied to an unknown base is how a node ends up
// in a state nobody can name (design section 5.2).
type NodeSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Strictly increasing per node, never reused. The node refuses anything below its
	// applied generation, because a retried frame arriving late must not roll a machine
	// backwards; an equal generation is accepted and reconciled again, because the disk
	// may have drifted since it was applied.
	Generation uint64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// When the panel built this spec. Compared against the node's clock in the status it
	// sends back: clock skew breaks ACME and TLS in ways that are very hard to read
	// backwards from the symptom (design section 7.2).
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// Anything running on this node that is not in this list is removed. That is the
	// garbage-collection half of reconciliation, and the reason omission is deletion.
	Workloads []*Workload `protobuf:"bytes,3,rep,name=workloads,proto3" json:"workloads,omitempty"`
	Routes    []*Route    `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	// The shared database engines this node hosts, at most one per engine.
	Engines []*DatabaseEngineSpec `protobuf:"bytes,5,rep,name=engines,proto3" json:"engines,omitempty"`
	// Customer databases carved out of those engines. Here rather than created once by a
	// command so a node that lost its disk rebuilds the accounts instead of leaving
	// applications unable to log in.
	Databases []*DatabaseGrant `protobuf:"bytes,6,rep,name=databases,proto3" json:"databases,omitempty"`
	Cron      []*CronEntry     `protobuf:"bytes,7,rep,name=cron,proto3" json:"cron,omitempty"`
	// The directories the web file manager is allowed to touch. There is no SSH and no
	// SFTP, so this list is the entire surface a customer has on the node's filesystem
	// (design section 8.2).
	FileRoots []*FileRoot      `protobuf:"bytes,8,rep,name=file_roots,json=fileRoots,proto3" json:"file_roots,omitempty"`
	Retention *RetentionPolicy `protobuf:"bytes,9,opt,name=retention,proto3" json:"retention,omitempty"`
	// How often to reconcile, in seconds, event or no event. Sent with the spec rather
	// than compiled into the daemon so the interval can be tuned without an upgrade.
	ReconcileIntervalSeconds int64 `protobuf:"varint,10,opt,name=reconcile_interval_seconds,json=reconcileIntervalSeconds,proto3" json:"reconcile_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *NodeSpec) Reset() {
	*x = NodeSpec{}
	mi := &file_wisper_v1_workload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSpec) ProtoMessage() {}

func (x *NodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSpec.ProtoReflect.Descriptor instead.
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{0}
}

func (x *NodeSpec) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *NodeSpec) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *NodeSpec) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *NodeSpec) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NodeSpec) GetEngines() []*DatabaseEngineSpec {
	if x != nil {
		return x.Engines
	}
	return nil
}

func (x *NodeSpec) GetDatabases() []*DatabaseGrant {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *NodeSpec) GetCron() []*CronEntry {
	if x != nil {
		return x.Cron
	}
	return nil
}

func (x *NodeSpec) GetFileRoots() []*FileRoot {
	if x != nil {
		return x.FileRoots
	}
	return nil
}

func (x *NodeSpec) GetRetention() *RetentionPolicy {
	if x != nil {
		return x.Retention
	}
	return nil
}

func (x *NodeSpec) GetReconcileIntervalSeconds() int64 {
	if x != nil {
		return x.ReconcileIntervalSeconds
	}
	return 0
}

// One deployable unit a customer owns.
type Workload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable for the life of the service. Container names, volume directories and log
	// streams are all derived from it, so it never changes once a workload exists.
	Id   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind WorkloadKind `protobuf:"varint,2,opt,name=kind,proto3,enum=wisper.v1.WorkloadKind" json:"kind,omitempty"`
	// What the customer called it. Used for the container name and in log lines, because
	// an operator reading `docker ps` should not have to resolve ids by hand.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// APP only. Ignored for a site, which has no image.
	Image string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	// The digest the panel resolved for `image`, when it resolved one. Pinning here means
	// two nodes told to run the same tag run the same bytes, and a restart does not
	// silently pick up a moved tag.
	ImageDigest string `protobuf:"bytes,5,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// Docker's ENTRYPOINT and CMD, as argument vectors. Never a shell string: the panel
	// builds argv and the node passes argv, so a service name with a semicolon in it
	// cannot become a second command (AGENTS.md section 5).
	Entrypoint []string `protobuf:"bytes,6,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Command    []string `protobuf:"bytes,7,rep,name=command,proto3" json:"command,omitempty"`
	WorkingDir string   `protobuf:"bytes,8,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// A repeated list rather than a map because the node hashes the spec to detect drift
	// and protobuf map ordering is not deterministic, and because a value that must not
	// be logged has to be marked as such.
	Env          []*EnvVar        `protobuf:"bytes,9,rep,name=env,proto3" json:"env,omitempty"`
	Limits       *ResourceLimits  `protobuf:"bytes,10,opt,name=limits,proto3" json:"limits,omitempty"`
	Mounts       []*Mount         `protobuf:"bytes,11,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Ports        []*PortBinding   `protobuf:"bytes,12,rep,name=ports,proto3" json:"ports,omitempty"`
	Restart      *RestartPolicy   `protobuf:"bytes,13,opt,name=restart,proto3" json:"restart,omitempty"`
	Runtime      ContainerRuntime `protobuf:"varint,14,opt,name=runtime,proto3,enum=wisper.v1.ContainerRuntime" json:"runtime,omitempty"`
	DesiredState DesiredState     `protobuf:"varint,15,opt,name=desired_state,json=desiredState,proto3,enum=wisper.v1.DesiredState" json:"desired_state,omitempty"`
	HealthCheck  *HealthCheck     `protobuf:"bytes,16,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	// The Docker network this workload joins, one per tenant. Two customers on the same
	// node must not be able to reach each other's containers by address.
	TenantNetwork string `protobuf:"bytes,17,opt,name=tenant_network,json=tenantNetwork,proto3" json:"tenant_network,omitempty"`
	// Set wherever the workload tolerates it. Writable paths then have to be mounts,
	// which is also where quotas and backups can see them.
	ReadOnlyRootfs bool `protobuf:"varint,18,opt,name=read_only_rootfs,json=readOnlyRootfs,proto3" json:"read_only_rootfs,omitempty"`
	// uid[:gid] inside the container. Combined with user-namespace remapping on the
	// daemon, root in the container is nobody on the host.
	User string `protobuf:"bytes,19,opt,name=user,proto3" json:"user,omitempty"`
	// How long SIGTERM gets before SIGKILL. A database-backed app that is killed at two
	// seconds loses whatever it had in flight.
	StopGraceSeconds int64 `protobuf:"varint,20,opt,name=stop_grace_seconds,json=stopGraceSeconds,proto3" json:"stop_grace_seconds,omitempty"`
	// SITE only: which directory under releases/ the `current` symlink must point at.
	// Publishing and rolling back are both just a new generation naming a different
	// release, so there is no publish command and no rollback command to disagree with
	// the spec (design section 5.5).
	ReleaseId     string       `protobuf:"bytes,21,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Site          *SiteOptions `protobuf:"bytes,22,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_wisper_v1_workload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{1}
}

func (x *Workload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workload) GetKind() WorkloadKind {
	if x != nil {
		return x.Kind
	}
	return WorkloadKind_WORKLOAD_KIND_UNSPECIFIED
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Workload) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *Workload) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *Workload) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Workload) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *Workload) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Workload) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Workload) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *Workload) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Workload) GetRestart() *RestartPolicy {
	if x != nil {
		return x.Restart
	}
	return nil
}

func (x *Workload) GetRuntime() ContainerRuntime {
	if x != nil {
		return x.Runtime
	}
	return ContainerRuntime_CONTAINER_RUNTIME_UNSPECIFIED
}

func (x *Workload) GetDesiredState() DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredState_DESIRED_STATE_UNSPECIFIED
}

func (x *Workload) GetHealthCheck() *HealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *Workload) GetTenantNetwork() string {
	if x != nil {
		return x.TenantNetwork
	}
	return ""
}

func (x *Workload) GetReadOnlyRootfs() bool {
	if x != nil {
		return x.ReadOnlyRootfs
	}
	return false
}

func (x *Workload) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Workload) GetStopGraceSeconds() int64 {
	if x != nil {
		return x.StopGraceSeconds
	}
	return 0
}

func (x *Workload) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *Workload) GetSite() *SiteOptions {
	if x != nil {
		return x.Site
	}
	return nil
}

// One environment variable.
type EnvVar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// The node must not put this value in a log line, an error message or any status it
	// sends back. Marking it on the wire means neither side has to guess from the name.
	Secret        bool `protobuf:"varint,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_wisper_v1_workload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{2}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvVar) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

// Hard ceilings, applied through cgroups v2 by way of the Docker Engine API.
type ResourceLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Docker's NanoCPUs. 1000000000 is one full core, 500000000 is half of one.
	//
	// This is NOT CPUShares multiplied by a thousand. The predecessor conflated the two
	// and every container got a relative scheduling weight where a hard ceiling was
	// intended, so a single busy workload could take the whole machine while the panel
	// showed it politely limited (design section 9).
	NanoCpus    int64 `protobuf:"varint,1,opt,name=nano_cpus,json=nanoCpus,proto3" json:"nano_cpus,omitempty"`
	MemoryBytes int64 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// Docker's memory+swap total, so it is always >= memory_bytes. Equal to memory_bytes
	// disables swap; -1 is unlimited. Swapping a container is worse than killing it -
	// the machine grinds instead of one workload failing - so the default is equal.
	MemorySwapBytes int64 `protobuf:"varint,3,opt,name=memory_swap_bytes,json=memorySwapBytes,proto3" json:"memory_swap_bytes,omitempty"`
	// A fork bomb inside gVisor is still a fork bomb for the node's process table.
	PidsLimit int64 `protobuf:"varint,4,opt,name=pids_limit,json=pidsLimit,proto3" json:"pids_limit,omitempty"`
	// XFS project quota on this workload's volumes, in bytes. Enforced by the filesystem,
	// not by polling, which is why the storage layout had to be decided before any code
	// was written (design section 11.1).
	DiskBytes int64 `protobuf:"varint,5,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	// RLIMIT_NOFILE. Node and Go servers open a lot of sockets; the default is low enough
	// that the failure looks like a networking bug.
	NofileLimit   int64 `protobuf:"varint,6,opt,name=nofile_limit,json=nofileLimit,proto3" json:"nofile_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_wisper_v1_workload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceLimits) GetNanoCpus() int64 {
	if x != nil {
		return x.NanoCpus
	}
	return 0
}

func (x *ResourceLimits) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetMemorySwapBytes() int64 {
	if x != nil {
		return x.MemorySwapBytes
	}
	return 0
}

func (x *ResourceLimits) GetPidsLimit() int64 {
	if x != nil {
		return x.PidsLimit
	}
	return 0
}

func (x *ResourceLimits) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *ResourceLimits) GetNofileLimit() int64 {
	if x != nil {
		return x.NofileLimit
	}
	return 0
}

type Mount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the directory to the node, which resolves it under its own state root.
	// The panel never sends a filesystem path: a path from the network that reaches a
	// filesystem call is the bug class this whole platform has to avoid.
	VolumeId string    `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Kind     MountKind `protobuf:"varint,2,opt,name=kind,proto3,enum=wisper.v1.MountKind" json:"kind,omitempty"`
	// Absolute path inside the container.
	Target   string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	ReadOnly bool   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Per-volume ceiling, separate from ResourceLimits.disk_bytes so one workload can
	// have a large data volume and a small log volume.
	QuotaBytes int64 `protobuf:"varint,5,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	// MOUNT_KIND_TMPFS only. Unbounded tmpfs is memory exhaustion with extra steps.
	TmpfsBytes    int64 `protobuf:"varint,6,opt,name=tmpfs_bytes,json=tmpfsBytes,proto3" json:"tmpfs_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_wisper_v1_workload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{4}
}

func (x *Mount) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *Mount) GetKind() MountKind {
	if x != nil {
		return x.Kind
	}
	return MountKind_MOUNT_KIND_UNSPECIFIED
}

func (x *Mount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Mount) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *Mount) GetTmpfsBytes() int64 {
	if x != nil {
		return x.TmpfsBytes
	}
	return 0
}

// Publishing a port on the host is the exception, not the rule: HTTP traffic arrives
// through the embedded Caddy, which reaches containers over the tenant network. This
// exists for the workload that genuinely needs a raw port, such as a game server.
type PortBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort uint32                 `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	// 0 means "do not publish". Routes still work: the edge does not need a host port.
	HostPort uint32       `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	Protocol PortProtocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=wisper.v1.PortProtocol" json:"protocol,omitempty"`
	// Bind address on the host. "127.0.0.1" keeps a published port off the public
	// interface, which is what a database or an admin port wants.
	HostIp        string `protobuf:"bytes,4,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_wisper_v1_workload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBinding.ProtoReflect.Descriptor instead.
func (*PortBinding) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{5}
}

func (x *PortBinding) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortBinding) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortBinding) GetProtocol() PortProtocol {
	if x != nil {
		return x.Protocol
	}
	return PortProtocol_PORT_PROTOCOL_UNSPECIFIED
}

func (x *PortBinding) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type RestartPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  RestartPolicyMode      `protobuf:"varint,1,opt,name=mode,proto3,enum=wisper.v1.RestartPolicyMode" json:"mode,omitempty"`
	// ON_FAILURE only. Beyond this the workload is reported as crash-looping instead of
	// being restarted forever, so the customer is told rather than left wondering.
	MaxRetries    int32 `protobuf:"varint,2,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartPolicy) Reset() {
	*x = RestartPolicy{}
	mi := &file_wisper_v1_workload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartPolicy) ProtoMessage() {}

func (x *RestartPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartPolicy.ProtoReflect.Descriptor instead.
func (*RestartPolicy) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{6}
}

func (x *RestartPolicy) GetMode() RestartPolicyMode {
	if x != nil {
		return x.Mode
	}
	return RestartPolicyMode_RESTART_POLICY_MODE_UNSPECIFIED
}

func (x *RestartPolicy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

// Docker's own health check, configured by the panel rather than baked into an image
// the customer may not control. An unhealthy container is reported, not killed: the
// panel decides, because a failing check during a slow migration is not a reason to
// restart a database-backed app in a loop.
type HealthCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// argv run inside the container. Empty disables the check.
	Test            []string `protobuf:"bytes,1,rep,name=test,proto3" json:"test,omitempty"`
	IntervalSeconds int64    `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutSeconds  int64    `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Retries         int32    `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`
	// Grace period after start during which failures do not count. Without it, anything
	// that takes ten seconds to boot is permanently unhealthy.
	StartPeriodSeconds int64 `protobuf:"varint,5,opt,name=start_period_seconds,json=startPeriodSeconds,proto3" json:"start_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_wisper_v1_workload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheck) GetTest() []string {
	if x != nil {
		return x.Test
	}
	return nil
}

func (x *HealthCheck) GetIntervalSeconds() int64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheck) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheck) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HealthCheck) GetStartPeriodSeconds() int64 {
	if x != nil {
		return x.StartPeriodSeconds
	}
	return 0
}

// How a static site is served. These are Caddy file_server settings, in the spec
// because they are per-site decisions the customer makes, not defaults the node picks.
type SiteOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serve index_file for any path that does not exist, instead of a 404. Every
	// client-side-routed site needs this and no server-rendered one does.
	SpaFallback bool `protobuf:"varint,1,opt,name=spa_fallback,json=spaFallback,proto3" json:"spa_fallback,omitempty"`
	// Defaults to index.html when empty.
	IndexFile string `protobuf:"bytes,2,opt,name=index_file,json=indexFile,proto3" json:"index_file,omitempty"`
	// Served with a 404 status when there is no spa_fallback.
	NotFoundFile string `protobuf:"bytes,3,opt,name=not_found_file,json=notFoundFile,proto3" json:"not_found_file,omitempty"`
	// Off unless the customer asks: an accidental directory listing is a data leak.
	DirectoryListing bool `protobuf:"varint,4,opt,name=directory_listing,json=directoryListing,proto3" json:"directory_listing,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SiteOptions) Reset() {
	*x = SiteOptions{}
	mi := &file_wisper_v1_workload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteOptions) ProtoMessage() {}

func (x *SiteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteOptions.ProtoReflect.Descriptor instead.
func (*SiteOptions) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{8}
}

func (x *SiteOptions) GetSpaFallback() bool {
	if x != nil {
		return x.SpaFallback
	}
	return false
}

func (x *SiteOptions) GetIndexFile() string {
	if x != nil {
		return x.IndexFile
	}
	return ""
}

func (x *SiteOptions) GetNotFoundFile() string {
	if x != nil {
		return x.NotFoundFile
	}
	return ""
}

func (x *SiteOptions) GetDirectoryListing() bool {
	if x != nil {
		return x.DirectoryListing
	}
	return false
}

// One hostname pointing at one workload. In v1 a domain belongs to exactly one node, so
// no certificate ever has to be shared between machines (design section 5.4).
type Route struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Domain     string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	WorkloadId string                 `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	// The container port to proxy to. Ignored when the workload is a site: there is no
	// process, and the edge serves the release directory directly.
	Port    uint32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	TlsMode TlsMode `protobuf:"varint,4,opt,name=tls_mode,json=tlsMode,proto3,enum=wisper.v1.TlsMode" json:"tls_mode,omitempty"`
	// Empty means the whole host. Lets one domain serve an API from one workload and a
	// site from another, which is otherwise a reason to buy a second domain.
	PathPrefix string `protobuf:"bytes,5,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// Redirect plain HTTP to HTTPS. Off for TLS_MODE_DISABLED, and off for the domain
	// that is still being validated.
	ForceHttps    bool `protobuf:"varint,6,opt,name=force_https,json=forceHttps,proto3" json:"force_https,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_wisper_v1_workload_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{9}
}

func (x *Route) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Route) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *Route) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Route) GetTlsMode() TlsMode {
	if x != nil {
		return x.TlsMode
	}
	return TlsMode_TLS_MODE_UNSPECIFIED
}

func (x *Route) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Route) GetForceHttps() bool {
	if x != nil {
		return x.ForceHttps
	}
	return false
}

// A scheduled command inside a workload's container.
//
// Cron lives in the spec, unlike backups, because it is the customer's schedule and it
// has to keep firing while the panel is unreachable. Backups are the platform's and are
// coordinated centrally, where the retention policy and the destination credentials are.
type CronEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The container the command runs in. It must be a workload in the same spec.
	WorkloadId string `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	// Five-field cron.
	Schedule string `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// IANA zone name. Empty is UTC. A customer who asked for "3am" means their 3am, and
	// a daily job that moves twice a year is a support ticket nobody enjoys.
	Timezone string `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// argv. Never a shell string, for the same reason as Workload.command.
	Command []string `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	// Killed after this long and reported as failed. A cron job with no timeout is how a
	// node ends up with two hundred copies of the same stuck script.
	TimeoutSeconds int64 `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// False means a run that starts while the previous one is still going is skipped.
	// Overlap is opt-in because the common case - a backup script, an importer - corrupts
	// itself when two copies run at once.
	AllowOverlap  bool `protobuf:"varint,7,opt,name=allow_overlap,json=allowOverlap,proto3" json:"allow_overlap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronEntry) Reset() {
	*x = CronEntry{}
	mi := &file_wisper_v1_workload_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronEntry) ProtoMessage() {}

func (x *CronEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronEntry.ProtoReflect.Descriptor instead.
func (*CronEntry) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{10}
}

func (x *CronEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronEntry) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *CronEntry) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronEntry) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CronEntry) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CronEntry) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CronEntry) GetAllowOverlap() bool {
	if x != nil {
		return x.AllowOverlap
	}
	return false
}

// A directory the file manager may operate in.
//
// Every file operation names a root by id and a path relative to it. The panel never
// learns, and never sends, an absolute path on the node: the node resolves the root
// itself and rejects anything that escapes it. Path traversal is the largest attack
// surface in v1 and this is the shape that makes it checkable in one place.
type FileRoot struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind       FileRootKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=wisper.v1.FileRootKind" json:"kind,omitempty"`
	WorkloadId string                 `protobuf:"bytes,3,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	// Which mount of that workload this exposes. Empty for a site or staging root.
	VolumeId string `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// What the file manager shows in its breadcrumb.
	Label string `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	// False for the releases of a static site: a customer editing a built artifact in
	// place would have it silently reverted by the next deployment.
	Writable      bool  `protobuf:"varint,6,opt,name=writable,proto3" json:"writable,omitempty"`
	QuotaBytes    int64 `protobuf:"varint,7,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRoot) Reset() {
	*x = FileRoot{}
	mi := &file_wisper_v1_workload_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRoot) ProtoMessage() {}

func (x *FileRoot) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRoot.ProtoReflect.Descriptor instead.
func (*FileRoot) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{11}
}

func (x *FileRoot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileRoot) GetKind() FileRootKind {
	if x != nil {
		return x.Kind
	}
	return FileRootKind_FILE_ROOT_KIND_UNSPECIFIED
}

func (x *FileRoot) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *FileRoot) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *FileRoot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FileRoot) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *FileRoot) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

// What the node keeps and what it sweeps. On the node rather than the panel because the
// node is the only side that knows how much disk is actually left.
type RetentionPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Static site releases kept for instant rollback. Rollback is pointing the symlink at
	// an older one, so this number is literally how far back a customer can go.
	KeepReleases int32 `protobuf:"varint,1,opt,name=keep_releases,json=keepReleases,proto3" json:"keep_releases,omitempty"`
	// Build workspaces (checkout, node_modules, cache) kept after a build finishes. Zero
	// deletes them immediately; a few make the next build much faster.
	KeepBuildWorkspaces int32 `protobuf:"varint,2,opt,name=keep_build_workspaces,json=keepBuildWorkspaces,proto3" json:"keep_build_workspaces,omitempty"`
	// Docker json-file log rotation. Unrotated container logs are the classic way a node
	// fills its disk overnight.
	ContainerLogMaxBytes int64 `protobuf:"varint,3,opt,name=container_log_max_bytes,json=containerLogMaxBytes,proto3" json:"container_log_max_bytes,omitempty"`
	ContainerLogMaxFiles int32 `protobuf:"varint,4,opt,name=container_log_max_files,json=containerLogMaxFiles,proto3" json:"container_log_max_files,omitempty"`
	// Half-finished chunked uploads are swept after this. A phone that lost signal
	// mid-upload leaves parts behind and nobody comes back for them.
	OrphanUploadTtlSeconds int64 `protobuf:"varint,5,opt,name=orphan_upload_ttl_seconds,json=orphanUploadTtlSeconds,proto3" json:"orphan_upload_ttl_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RetentionPolicy) Reset() {
	*x = RetentionPolicy{}
	mi := &file_wisper_v1_workload_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionPolicy) ProtoMessage() {}

func (x *RetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionPolicy.ProtoReflect.Descriptor instead.
func (*RetentionPolicy) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{12}
}

func (x *RetentionPolicy) GetKeepReleases() int32 {
	if x != nil {
		return x.KeepReleases
	}
	return 0
}

func (x *RetentionPolicy) GetKeepBuildWorkspaces() int32 {
	if x != nil {
		return x.KeepBuildWorkspaces
	}
	return 0
}

func (x *RetentionPolicy) GetContainerLogMaxBytes() int64 {
	if x != nil {
		return x.ContainerLogMaxBytes
	}
	return 0
}

func (x *RetentionPolicy) GetContainerLogMaxFiles() int32 {
	if x != nil {
		return x.ContainerLogMaxFiles
	}
	return 0
}

func (x *RetentionPolicy) GetOrphanUploadTtlSeconds() int64 {
	if x != nil {
		return x.OrphanUploadTtlSeconds
	}
	return 0
}

// The observed half of a Workload. The panel owns intent, the node owns fact; nothing
// here is ever written back into the spec.
type WorkloadStatus struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId  string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Phase       WorkloadPhase          `protobuf:"varint,2,opt,name=phase,proto3,enum=wisper.v1.WorkloadPhase" json:"phase,omitempty"`
	ContainerId string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// What is really running, which is how a moved tag becomes visible instead of being a
	// mystery restart.
	ImageDigest  string `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	RestartCount int32  `protobuf:"varint,5,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// Of the last exit. Meaningless while running, and the phase says which it is.
	ExitCode int32 `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Human-readable reason for the current phase: the pull error, the OOM kill, the
	// health check output.
	Message          string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastTransitionAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_transition_at,json=lastTransitionAt,proto3" json:"last_transition_at,omitempty"`
	// The runtime in effect, not the one requested. A node without runsc falls back to
	// runc and the panel has to say so out loud rather than imply isolation it does not
	// have (design section 7.2).
	Runtime ContainerRuntime `protobuf:"varint,10,opt,name=runtime,proto3,enum=wisper.v1.ContainerRuntime" json:"runtime,omitempty"`
	// SITE only: which release the symlink currently resolves to. The panel compares it
	// with the spec to show a deployment as live.
	ReleaseId     string `protobuf:"bytes,11,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_wisper_v1_workload_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{13}
}

func (x *WorkloadStatus) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadStatus) GetPhase() WorkloadPhase {
	if x != nil {
		return x.Phase
	}
	return WorkloadPhase_WORKLOAD_PHASE_UNSPECIFIED
}

func (x *WorkloadStatus) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WorkloadStatus) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *WorkloadStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *WorkloadStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WorkloadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *WorkloadStatus) GetLastTransitionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionAt
	}
	return nil
}

func (x *WorkloadStatus) GetRuntime() ContainerRuntime {
	if x != nil {
		return x.Runtime
	}
	return ContainerRuntime_CONTAINER_RUNTIME_UNSPECIFIED
}

func (x *WorkloadStatus) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

// Whether a route is actually serving. The customer pointed DNS at this node and wants
// to know why nothing happens; this is the answer.
type RouteStatus struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Domain string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// The edge has the route loaded and a backend to send it to.
	Serving     bool             `protobuf:"varint,2,opt,name=serving,proto3" json:"serving,omitempty"`
	Certificate CertificateState `protobuf:"varint,3,opt,name=certificate,proto3,enum=wisper.v1.CertificateState" json:"certificate,omitempty"`
	// So the panel can warn before a renewal that has been failing quietly runs out.
	CertificateNotAfter *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=certificate_not_after,json=certificateNotAfter,proto3" json:"certificate_not_after,omitempty"`
	// The ACME failure, verbatim. "DNS does not point here yet" and "rate limited" need
	// completely different actions from the customer.
	LastError     string `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteStatus) Reset() {
	*x = RouteStatus{}
	mi := &file_wisper_v1_workload_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStatus) ProtoMessage() {}

func (x *RouteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStatus.ProtoReflect.Descriptor instead.
func (*RouteStatus) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{14}
}

func (x *RouteStatus) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RouteStatus) GetServing() bool {
	if x != nil {
		return x.Serving
	}
	return false
}

func (x *RouteStatus) GetCertificate() CertificateState {
	if x != nil {
		return x.Certificate
	}
	return CertificateState_CERTIFICATE_STATE_UNSPECIFIED
}

func (x *RouteStatus) GetCertificateNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CertificateNotAfter
	}
	return nil
}

func (x *RouteStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// The observed half of a CronEntry.
type CronStatus struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CronId       string                 `protobuf:"bytes,1,opt,name=cron_id,json=cronId,proto3" json:"cron_id,omitempty"`
	LastRunAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	NextRunAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	LastExitCode int32                  `protobuf:"varint,4,opt,name=last_exit_code,json=lastExitCode,proto3" json:"last_exit_code,omitempty"`
	// True while a run is in flight, so the panel does not show "never ran" for a job
	// that is running right now.
	Running bool `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	// Set when the last run was skipped because the previous one had not finished and
	// allow_overlap is false. Otherwise the schedule looks broken.
	LastRunSkipped bool   `protobuf:"varint,6,opt,name=last_run_skipped,json=lastRunSkipped,proto3" json:"last_run_skipped,omitempty"`
	LastError      string `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CronStatus) Reset() {
	*x = CronStatus{}
	mi := &file_wisper_v1_workload_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronStatus) ProtoMessage() {}

func (x *CronStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wisper_v1_workload_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronStatus.ProtoReflect.Descriptor instead.
func (*CronStatus) Descriptor() ([]byte, []int) {
	return file_wisper_v1_workload_proto_rawDescGZIP(), []int{15}
}

func (x *CronStatus) GetCronId() string {
	if x != nil {
		return x.CronId
	}
	return ""
}

func (x *CronStatus) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *CronStatus) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *CronStatus) GetLastExitCode() int32 {
	if x != nil {
		return x.LastExitCode
	}
	return 0
}

func (x *CronStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *CronStatus) GetLastRunSkipped() bool {
	if x != nil {
		return x.LastRunSkipped
	}
	return false
}

func (x *CronStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_wisper_v1_workload_proto protoreflect.FileDescriptor

const file_wisper_v1_workload_proto_rawDesc = "" +
	"\n" +
	"\x18wisper/v1/workload.proto\x12\twisper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18wisper/v1/database.proto\"\x87\x04\n" +
	"\bNodeSpec\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x127\n" +
	"\tissued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x121\n" +
	"\tworkloads\x18\x03 \x03(\v2\x13.wisper.v1.WorkloadR\tworkloads\x12(\n" +
	"\x06routes\x18\x04 \x03(\v2\x10.wisper.v1.RouteR\x06routes\x127\n" +
	"\aengines\x18\x05 \x03(\v2\x1d.wisper.v1.DatabaseEngineSpecR\aengines\x126\n" +
	"\tdatabases\x18\x06 \x03(\v2\x18.wisper.v1.DatabaseGrantR\tdatabases\x12(\n" +
	"\x04cron\x18\a \x03(\v2\x14.wisper.v1.CronEntryR\x04cron\x122\n" +
	"\n" +
	"file_roots\x18\b \x03(\v2\x13.wisper.v1.FileRootR\tfileRoots\x128\n" +
	"\tretention\x18\t \x01(\v2\x1a.wisper.v1.RetentionPolicyR\tretention\x12<\n" +
	"\x1areconcile_interval_seconds\x18\n" +
	" \x01(\x03R\x18reconcileIntervalSeconds\"\xe1\x06\n" +
	"\bWorkload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x17.wisper.v1.WorkloadKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x05 \x01(\tR\vimageDigest\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x06 \x03(\tR\n" +
	"entrypoint\x12\x18\n" +
	"\acommand\x18\a \x03(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\b \x01(\tR\n" +
	"workingDir\x12#\n" +
	"\x03env\x18\t \x03(\v2\x11.wisper.v1.EnvVarR\x03env\x121\n" +
	"\x06limits\x18\n" +
	" \x01(\v2\x19.wisper.v1.ResourceLimitsR\x06limits\x12(\n" +
	"\x06mounts\x18\v \x03(\v2\x10.wisper.v1.MountR\x06mounts\x12,\n" +
	"\x05ports\x18\f \x03(\v2\x16.wisper.v1.PortBindingR\x05ports\x122\n" +
	"\arestart\x18\r \x01(\v2\x18.wisper.v1.RestartPolicyR\arestart\x125\n" +
	"\aruntime\x18\x0e \x01(\x0e2\x1b.wisper.v1.ContainerRuntimeR\aruntime\x12<\n" +
	"\rdesired_state\x18\x0f \x01(\x0e2\x17.wisper.v1.DesiredStateR\fdesiredState\x129\n" +
	"\fhealth_check\x18\x10 \x01(\v2\x16.wisper.v1.HealthCheckR\vhealthCheck\x12%\n" +
	"\x0etenant_network\x18\x11 \x01(\tR\rtenantNetwork\x12(\n" +
	"\x10read_only_rootfs\x18\x12 \x01(\bR\x0ereadOnlyRootfs\x12\x12\n" +
	"\x04user\x18\x13 \x01(\tR\x04user\x12,\n" +
	"\x12stop_grace_seconds\x18\x14 \x01(\x03R\x10stopGraceSeconds\x12\x1d\n" +
	"\n" +
	"release_id\x18\x15 \x01(\tR\treleaseId\x12*\n" +
	"\x04site\x18\x16 \x01(\v2\x16.wisper.v1.SiteOptionsR\x04site\"J\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\bR\x06secret\"\xdd\x01\n" +
	"\x0eResourceLimits\x12\x1b\n" +
	"\tnano_cpus\x18\x01 \x01(\x03R\bnanoCpus\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12*\n" +
	"\x11memory_swap_bytes\x18\x03 \x01(\x03R\x0fmemorySwapBytes\x12\x1d\n" +
	"\n" +
	"pids_limit\x18\x04 \x01(\x03R\tpidsLimit\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x05 \x01(\x03R\tdiskBytes\x12!\n" +
	"\fnofile_limit\x18\x06 \x01(\x03R\vnofileLimit\"\xc5\x01\n" +
	"\x05Mount\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12(\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x14.wisper.v1.MountKindR\x04kind\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12\x1f\n" +
	"\vquota_bytes\x18\x05 \x01(\x03R\n" +
	"quotaBytes\x12\x1f\n" +
	"\vtmpfs_bytes\x18\x06 \x01(\x03R\n" +
	"tmpfsBytes\"\x9f\x01\n" +
	"\vPortBinding\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\rR\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\x123\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x17.wisper.v1.PortProtocolR\bprotocol\x12\x17\n" +
	"\ahost_ip\x18\x04 \x01(\tR\x06hostIp\"b\n" +
	"\rRestartPolicy\x120\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1c.wisper.v1.RestartPolicyModeR\x04mode\x12\x1f\n" +
	"\vmax_retries\x18\x02 \x01(\x05R\n" +
	"maxRetries\"\xc1\x01\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04test\x18\x01 \x03(\tR\x04test\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x03R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\x12\x18\n" +
	"\aretries\x18\x04 \x01(\x05R\aretries\x120\n" +
	"\x14start_period_seconds\x18\x05 \x01(\x03R\x12startPeriodSeconds\"\xa2\x01\n" +
	"\vSiteOptions\x12!\n" +
	"\fspa_fallback\x18\x01 \x01(\bR\vspaFallback\x12\x1d\n" +
	"\n" +
	"index_file\x18\x02 \x01(\tR\tindexFile\x12$\n" +
	"\x0enot_found_file\x18\x03 \x01(\tR\fnotFoundFile\x12+\n" +
	"\x11directory_listing\x18\x04 \x01(\bR\x10directoryListing\"\xc5\x01\n" +
	"\x05Route\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12-\n" +
	"\btls_mode\x18\x04 \x01(\x0e2\x12.wisper.v1.TlsModeR\atlsMode\x12\x1f\n" +
	"\vpath_prefix\x18\x05 \x01(\tR\n" +
	"pathPrefix\x12\x1f\n" +
	"\vforce_https\x18\x06 \x01(\bR\n" +
	"forceHttps\"\xdc\x01\n" +
	"\tCronEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x03R\x0etimeoutSeconds\x12#\n" +
	"\rallow_overlap\x18\a \x01(\bR\fallowOverlap\"\xd8\x01\n" +
	"\bFileRoot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x17.wisper.v1.FileRootKindR\x04kind\x12\x1f\n" +
	"\vworkload_id\x18\x03 \x01(\tR\n" +
	"workloadId\x12\x1b\n" +
	"\tvolume_id\x18\x04 \x01(\tR\bvolumeId\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x1a\n" +
	"\bwritable\x18\x06 \x01(\bR\bwritable\x12\x1f\n" +
	"\vquota_bytes\x18\a \x01(\x03R\n" +
	"quotaBytes\"\x93\x02\n" +
	"\x0fRetentionPolicy\x12#\n" +
	"\rkeep_releases\x18\x01 \x01(\x05R\fkeepReleases\x122\n" +
	"\x15keep_build_workspaces\x18\x02 \x01(\x05R\x13keepBuildWorkspaces\x125\n" +
	"\x17container_log_max_bytes\x18\x03 \x01(\x03R\x14containerLogMaxBytes\x125\n" +
	"\x17container_log_max_files\x18\x04 \x01(\x05R\x14containerLogMaxFiles\x129\n" +
	"\x19orphan_upload_ttl_seconds\x18\x05 \x01(\x03R\x16orphanUploadTtlSeconds\"\xde\x03\n" +
	"\x0eWorkloadStatus\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12.\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x18.wisper.v1.WorkloadPhaseR\x05phase\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x12#\n" +
	"\rrestart_count\x18\x05 \x01(\x05R\frestartCount\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12H\n" +
	"\x12last_transition_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10lastTransitionAt\x125\n" +
	"\aruntime\x18\n" +
	" \x01(\x0e2\x1b.wisper.v1.ContainerRuntimeR\aruntime\x12\x1d\n" +
	"\n" +
	"release_id\x18\v \x01(\tR\treleaseId\"\xed\x01\n" +
	"\vRouteStatus\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x18\n" +
	"\aserving\x18\x02 \x01(\bR\aserving\x12=\n" +
	"\vcertificate\x18\x03 \x01(\x0e2\x1b.wisper.v1.CertificateStateR\vcertificate\x12N\n" +
	"\x15certificate_not_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x13certificateNotAfter\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\"\xa6\x02\n" +
	"\n" +
	"CronStatus\x12\x17\n" +
	"\acron_id\x18\x01 \x01(\tR\x06cronId\x12:\n" +
	"\vlast_run_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12:\n" +
	"\vnext_run_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x12$\n" +
	"\x0elast_exit_code\x18\x04 \x01(\x05R\flastExitCode\x12\x18\n" +
	"\arunning\x18\x05 \x01(\bR\arunning\x12(\n" +
	"\x10last_run_skipped\x18\x06 \x01(\bR\x0elastRunSkipped\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError*\\\n" +
	"\fWorkloadKind\x12\x1d\n" +
	"\x19WORKLOAD_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WORKLOAD_KIND_APP\x10\x01\x12\x16\n" +
	"\x12WORKLOAD_KIND_SITE\x10\x02*c\n" +
	"\fDesiredState\x12\x1d\n" +
	"\x19DESIRED_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DESIRED_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15DESIRED_STATE_STOPPED\x10\x02*n\n" +
	"\x10ContainerRuntime\x12!\n" +
	"\x1dCONTAINER_RUNTIME_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONTAINER_RUNTIME_RUNSC\x10\x01\x12\x1a\n" +
	"\x16CONTAINER_RUNTIME_RUNC\x10\x02*q\n" +
	"\tMountKind\x12\x1a\n" +
	"\x16MOUNT_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MOUNT_KIND_VOLUME\x10\x01\x12\x1b\n" +
	"\x17MOUNT_KIND_SITE_RELEASE\x10\x02\x12\x14\n" +
	"\x10MOUNT_KIND_TMPFS\x10\x03*[\n" +
	"\fPortProtocol\x12\x1d\n" +
	"\x19PORT_PROTOCOL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PORT_PROTOCOL_TCP\x10\x01\x12\x15\n" +
	"\x11PORT_PROTOCOL_UDP\x10\x02*\xc3\x01\n" +
	"\x11RestartPolicyMode\x12#\n" +
	"\x1fRESTART_POLICY_MODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RESTART_POLICY_MODE_NEVER\x10\x01\x12\"\n" +
	"\x1eRESTART_POLICY_MODE_ON_FAILURE\x10\x02\x12\x1e\n" +
	"\x1aRESTART_POLICY_MODE_ALWAYS\x10\x03\x12&\n" +
	"\"RESTART_POLICY_MODE_UNLESS_STOPPED\x10\x04*R\n" +
	"\aTlsMode\x12\x18\n" +
	"\x14TLS_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TLS_MODE_ON_DEMAND\x10\x01\x12\x15\n" +
	"\x11TLS_MODE_DISABLED\x10\x02*\x85\x01\n" +
	"\fFileRootKind\x12\x1e\n" +
	"\x1aFILE_ROOT_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FILE_ROOT_KIND_VOLUME\x10\x01\x12\x17\n" +
	"\x13FILE_ROOT_KIND_SITE\x10\x02\x12!\n" +
	"\x1dFILE_ROOT_KIND_UPLOAD_STAGING\x10\x03*\xb3\x02\n" +
	"\rWorkloadPhase\x12\x1e\n" +
	"\x1aWORKLOAD_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_PENDING\x10\x01\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_PULLING\x10\x02\x12\x1b\n" +
	"\x17WORKLOAD_PHASE_STARTING\x10\x03\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_RUNNING\x10\x04\x12\x1c\n" +
	"\x18WORKLOAD_PHASE_UNHEALTHY\x10\x05\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_STOPPED\x10\x06\x12\x19\n" +
	"\x15WORKLOAD_PHASE_FAILED\x10\a\x12 \n" +
	"\x1cWORKLOAD_PHASE_CRASH_LOOPING\x10\b\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_UNKNOWN\x10\t*\xab\x01\n" +
	"\x10CertificateState\x12!\n" +
	"\x1dCERTIFICATE_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CERTIFICATE_STATE_NONE\x10\x01\x12\x1d\n" +
	"\x19CERTIFICATE_STATE_ISSUING\x10\x02\x12\x1b\n" +
	"\x17CERTIFICATE_STATE_VALID\x10\x03\x12\x1c\n" +
	"\x18CERTIFICATE_STATE_FAILED\x10\x04Bn\n" +
	"\x1clhqm.furimeo.wisper.proto.v1B\rWorkloadProtoP\x01Z=github.com/furimeo/wisper/sasayaki/internal/wisperpb;wisperpbb\x06proto3"

var (
	file_wisper_v1_workload_proto_rawDescOnce sync.Once
	file_wisper_v1_workload_proto_rawDescData []byte
)

func file_wisper_v1_workload_proto_rawDescGZIP() []byte {
	file_wisper_v1_workload_proto_rawDescOnce.Do(func() {
		file_wisper_v1_workload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wisper_v1_workload_proto_rawDesc), len(file_wisper_v1_workload_proto_rawDesc)))
	})
	return file_wisper_v1_workload_proto_rawDescData
}

var file_wisper_v1_workload_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_wisper_v1_workload_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_wisper_v1_workload_proto_goTypes = []any{
	(WorkloadKind)(0),             // 0: wisper.v1.WorkloadKind
	(DesiredState)(0),             // 1: wisper.v1.DesiredState
	(ContainerRuntime)(0),         // 2: wisper.v1.ContainerRuntime
	(MountKind)(0),                // 3: wisper.v1.MountKind
	(PortProtocol)(0),             // 4: wisper.v1.PortProtocol
	(RestartPolicyMode)(0),        // 5: wisper.v1.RestartPolicyMode
	(TlsMode)(0),                  // 6: wisper.v1.TlsMode
	(FileRootKind)(0),             // 7: wisper.v1.FileRootKind
	(WorkloadPhase)(0),            // 8: wisper.v1.WorkloadPhase
	(CertificateState)(0),         // 9: wisper.v1.CertificateState
	(*NodeSpec)(nil),              // 10: wisper.v1.NodeSpec
	(*Workload)(nil),              // 11: wisper.v1.Workload
	(*EnvVar)(nil),                // 12: wisper.v1.EnvVar
	(*ResourceLimits)(nil),        // 13: wisper.v1.ResourceLimits
	(*Mount)(nil),                 // 14: wisper.v1.Mount
	(*PortBinding)(nil),           // 15: wisper.v1.PortBinding
	(*RestartPolicy)(nil),         // 16: wisper.v1.RestartPolicy
	(*HealthCheck)(nil),           // 17: wisper.v1.HealthCheck
	(*SiteOptions)(nil),           // 18: wisper.v1.SiteOptions
	(*Route)(nil),                 // 19: wisper.v1.Route
	(*CronEntry)(nil),             // 20: wisper.v1.CronEntry
	(*FileRoot)(nil),              // 21: wisper.v1.FileRoot
	(*RetentionPolicy)(nil),       // 22: wisper.v1.RetentionPolicy
	(*WorkloadStatus)(nil),        // 23: wisper.v1.WorkloadStatus
	(*RouteStatus)(nil),           // 24: wisper.v1.RouteStatus
	(*CronStatus)(nil),            // 25: wisper.v1.CronStatus
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
	(*DatabaseEngineSpec)(nil),    // 27: wisper.v1.DatabaseEngineSpec
	(*DatabaseGrant)(nil),         // 28: wisper.v1.DatabaseGrant
}
var file_wisper_v1_workload_proto_depIdxs = []int32{
	26, // 0: wisper.v1.NodeSpec.issued_at:type_name -> google.protobuf.Timestamp
	11, // 1: wisper.v1.NodeSpec.workloads:type_name -> wisper.v1.Workload
	19, // 2: wisper.v1.NodeSpec.routes:type_name -> wisper.v1.Route
	27, // 3: wisper.v1.NodeSpec.engines:type_name -> wisper.v1.DatabaseEngineSpec
	28, // 4: wisper.v1.NodeSpec.databases:type_name -> wisper.v1.DatabaseGrant
	20, // 5: wisper.v1.NodeSpec.cron:type_name -> wisper.v1.CronEntry
	21, // 6: wisper.v1.NodeSpec.file_roots:type_name -> wisper.v1.FileRoot
	22, // 7: wisper.v1.NodeSpec.retention:type_name -> wisper.v1.RetentionPolicy
	0,  // 8: wisper.v1.Workload.kind:type_name -> wisper.v1.WorkloadKind
	12, // 9: wisper.v1.Workload.env:type_name -> wisper.v1.EnvVar
	13, // 10: wisper.v1.Workload.limits:type_name -> wisper.v1.ResourceLimits
	14, // 11: wisper.v1.Workload.mounts:type_name -> wisper.v1.Mount
	15, // 12: wisper.v1.Workload.ports:type_name -> wisper.v1.PortBinding
	16, // 13: wisper.v1.Workload.restart:type_name -> wisper.v1.RestartPolicy
	2,  // 14: wisper.v1.Workload.runtime:type_name -> wisper.v1.ContainerRuntime
	1,  // 15: wisper.v1.Workload.desired_state:type_name -> wisper.v1.DesiredState
	17, // 16: wisper.v1.Workload.health_check:type_name -> wisper.v1.HealthCheck
	18, // 17: wisper.v1.Workload.site:type_name -> wisper.v1.SiteOptions
	3,  // 18: wisper.v1.Mount.kind:type_name -> wisper.v1.MountKind
	4,  // 19: wisper.v1.PortBinding.protocol:type_name -> wisper.v1.PortProtocol
	5,  // 20: wisper.v1.RestartPolicy.mode:type_name -> wisper.v1.RestartPolicyMode
	6,  // 21: wisper.v1.Route.tls_mode:type_name -> wisper.v1.TlsMode
	7,  // 22: wisper.v1.FileRoot.kind:type_name -> wisper.v1.FileRootKind
	8,  // 23: wisper.v1.WorkloadStatus.phase:type_name -> wisper.v1.WorkloadPhase
	26, // 24: wisper.v1.WorkloadStatus.started_at:type_name -> google.protobuf.Timestamp
	26, // 25: wisper.v1.WorkloadStatus.last_transition_at:type_name -> google.protobuf.Timestamp
	2,  // 26: wisper.v1.WorkloadStatus.runtime:type_name -> wisper.v1.ContainerRuntime
	9,  // 27: wisper.v1.RouteStatus.certificate:type_name -> wisper.v1.CertificateState
	26, // 28: wisper.v1.RouteStatus.certificate_not_after:type_name -> google.protobuf.Timestamp
	26, // 29: wisper.v1.CronStatus.last_run_at:type_name -> google.protobuf.Timestamp
	26, // 30: wisper.v1.CronStatus.next_run_at:type_name -> google.protobuf.Timestamp
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_wisper_v1_workload_proto_init() }
func file_wisper_v1_workload_proto_init() {
	if File_wisper_v1_workload_proto != nil {
		return
	}
	file_wisper_v1_database_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wisper_v1_workload_proto_rawDesc), len(file_wisper_v1_workload_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wisper_v1_workload_proto_goTypes,
		DependencyIndexes: file_wisper_v1_workload_proto_depIdxs,
		EnumInfos:         file_wisper_v1_workload_proto_enumTypes,
		MessageInfos:      file_wisper_v1_workload_proto_msgTypes,
	}.Build()
	File_wisper_v1_workload_proto = out.File
	file_wisper_v1_workload_proto_goTypes = nil
	file_wisper_v1_workload_proto_depIdxs = nil
}
