-- A person who can sign in to the panel. Named `account` rather than `user` because
-- `user` is reserved in PostgreSQL and Spring Data JDBC will not quote it for you.
--
-- Identity conventions used by every table in this schema (see docs/contracts/schema.md):
--   * the primary key is a uuid generated by the panel, never by the database;
--   * `version` is what tells Spring Data JDBC an assigned id is a new row, so every
--     aggregate record carries @Version Long version;
--   * created_at / updated_at are written from Java by @CreatedDate / @LastModifiedDate.
--     The DEFAULT now() is only for rows a migration inserts.

CREATE TABLE account (
    id                  uuid        PRIMARY KEY,
    -- Stored lower-cased so a plain unique constraint is a case-insensitive one and
    -- findByEmail needs no functional index.
    email               text        NOT NULL,
    display_name        text        NOT NULL,
    -- BCrypt. Never a reversible encoding: the panel must not be able to read it back.
    password_hash       text        NOT NULL,
    password_changed_at timestamptz,
    -- ADMIN is the platform operator (ROLE_ADMIN, /admin/**). CUSTOMER is everyone else;
    -- what a customer may do inside an organization comes from `member.role`.
    platform_role       text        NOT NULL DEFAULT 'CUSTOMER',
    status              text        NOT NULL DEFAULT 'ACTIVE',
    -- TOTP shared secret, encrypted at rest with the panel key. Null until the second
    -- factor is set up; totp_confirmed_at stays null until one code has been verified,
    -- so a half-finished enrolment never locks anybody out.
    totp_secret         text,
    totp_confirmed_at   timestamptz,
    last_login_at       timestamptz,
    last_login_address  text,
    failed_login_count  int         NOT NULL DEFAULT 0,
    -- Set by the login throttle. A row is not deleted to lock an account out.
    locked_until        timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    version             bigint      NOT NULL DEFAULT 0,

    CONSTRAINT account_email_lowercase CHECK (email = lower(email)),
    CONSTRAINT account_email_shape CHECK (email LIKE '%_@_%'),
    CONSTRAINT account_platform_role_known CHECK (platform_role IN ('ADMIN', 'CUSTOMER')),
    CONSTRAINT account_status_known CHECK (status IN ('ACTIVE', 'SUSPENDED')),
    CONSTRAINT account_failed_login_count_positive CHECK (failed_login_count >= 0),
    -- A confirmed second factor without a secret would silently stop challenging.
    CONSTRAINT account_totp_confirmed_needs_secret
        CHECK (totp_confirmed_at IS NULL OR totp_secret IS NOT NULL)
);

CREATE UNIQUE INDEX account_email_key ON account (email);

-- The admin list, and the "is there any admin left" check before demoting one.
CREATE INDEX account_platform_role_idx ON account (platform_role);
