package lhqm.furimeo.wisper.node;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.List;
import java.util.StringJoiner;

/**
 * Renders {@code /install.sh} with this panel's URL, dial endpoint and published binary
 * checksums baked into it.
 *
 * <p>The script is generated rather than served from a file because the two things that
 * make it safe are facts the panel knows and a file on disk does not: the checksum of
 * every binary currently published, and the endpoint a node should dial. A static script
 * that fetched a checksum at run time would be verifying a download against a value from
 * the same server - which is not verification, it is a formality.
 *
 * <p>Four properties, from design §7.1, and where each one lives:
 *
 * <ul>
 * <li><strong>The token never appears in {@code argv}.</strong> Only
 *     {@code --token-file} and stdin, because {@code ps} is readable by every user on the
 *     machine. Enforced here, in the argument parser below, and again by
 *     {@code sasayaki enroll}.</li>
 * <li><strong>The binary is verified.</strong> {@code sha256sum -c} against the value
 *     baked in for the detected architecture, before anything is placed.</li>
 * <li><strong>The script itself is verifiable.</strong> {@link #sha256()} is shown on the
 *     panel next to the command, so an operator can check what they downloaded before
 *     running it as root.</li>
 * <li><strong>Nothing is written until {@code doctor} passes.</strong> The binary is
 *     downloaded to a temporary directory and run from there; only a passing preflight
 *     gets it installed (design §7.2).</li>
 * </ul>
 *
 * <p>Re-running it is an upgrade, not a failure. That is a property of
 * {@code sasayaki install}, which the script defers to for everything after the binary is
 * in place.
 */
public record InstallScript(String text) {

    /** Where the binary goes; the systemd unit sasayaki writes points at this path. */
    private static final String BINARY_PATH = "/usr/local/bin/sasayaki";

    /**
     * Builds the script.
     *
     * @param panelBaseUrl  the panel as the operator's browser reached it - the panel is
     *                      behind a tunnel and has no way to work its own URL out
     * @param dialEndpoint  {@code host:port} the node is told to dial for gRPC
     * @param releases      what is published. An empty list produces a script that
     *                      refuses to run and says so, which is the honest answer to "no
     *                      binary has been published yet".
     */
    public static InstallScript render(String panelBaseUrl, String dialEndpoint,
                                       List<AgentRelease> releases) {
        return render(panelBaseUrl, panelBaseUrl + "/dist", dialEndpoint, releases);
    }

    public static InstallScript render(String panelBaseUrl, String downloadBaseUrl,
                                       String dialEndpoint, List<AgentRelease> releases) {
        StringBuilder script = new StringBuilder(header(panelBaseUrl, downloadBaseUrl, dialEndpoint));
        script.append(architectureTable(releases));
        script.append(BODY);
        return new InstallScript(script.toString());
    }

    /** Lower-case hex SHA-256 of the script, for the line an operator checks it with. */
    public String sha256() {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                    .digest(text.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException impossible) {
            throw new IllegalStateException("SHA-256 is missing from this JDK", impossible);
        }
    }

    /** How many bytes to declare, so a client can show a progress bar honestly. */
    public int byteLength() {
        return text.getBytes(StandardCharsets.UTF_8).length;
    }

    private static String header(String panelBaseUrl, String downloadBaseUrl, String dialEndpoint) {
        return """
                #!/bin/sh
                # wisper node installer. Generated by the panel, with this panel's URL and the
                # checksum of every sasayaki binary it is currently publishing baked in.
                #
                #   curl -fsSL %1$s/install.sh -o install.sh
                #   sha256sum -c <<< "<the hash shown on the panel>  install.sh"
                #   sudo ./install.sh --token-file token.txt
                #
                # The token is never accepted as an argument: argv is readable by every user on
                # this machine through ps. Use --token-file, or - to read it from stdin.
                set -eu

                PANEL_URL="%1$s"
                DOWNLOAD_URL="%2$s"
                DIAL_ENDPOINT="%3$s"
                BINARY_PATH="%4$s"

                """.formatted(panelBaseUrl, downloadBaseUrl, dialEndpoint, BINARY_PATH);
    }

    /**
     * The published checksums, as a shell {@code case} on {@code uname -m}.
     *
     * <p>Baked in, one line per architecture. An architecture that is not published leaves
     * the checksum empty and the script stops before it downloads anything - rather than
     * fetching a binary it has nothing to check against.
     */
    private static String architectureTable(List<AgentRelease> releases) {
        StringJoiner cases = new StringJoiner("\n");
        cases.add("resolve_release() {");
        cases.add("  case \"$1\" in");
        for (AgentRelease release : releases) {
            for (String machine : unameFor(release.architecture())) {
                cases.add("    " + machine + ") RELEASE_FILE=\"" + release.fileName() + "\"; "
                        + "RELEASE_ARCH=\"" + release.architecture() + "\"; "
                        + "RELEASE_SHA256=\"" + release.sha256() + "\"; "
                        + "RELEASE_VERSION=\"" + release.version() + "\" ;;");
            }
        }
        cases.add("    *) RELEASE_FILE=\"\"; RELEASE_ARCH=\"\"; RELEASE_SHA256=\"\"; RELEASE_VERSION=\"\" ;;");
        cases.add("  esac");
        cases.add("}");
        cases.add("");
        return cases.toString();
    }

    /** What {@code uname -m} prints for a GOARCH, which is not the same word. */
    private static List<String> unameFor(String goarch) {
        return switch (goarch) {
            case "amd64" -> List.of("x86_64", "amd64");
            case "arm64" -> List.of("aarch64", "arm64");
            case "arm" -> List.of("armv7l", "armv6l");
            case "riscv64" -> List.of("riscv64");
            default -> List.of(goarch);
        };
    }

    /**
     * Everything after the generated table. POSIX {@code sh}, because a node that has just
     * been provisioned may not have bash, and this is the first thing that runs on it.
     */
    private static final String BODY = """
            usage() {
              cat >&2 <<'USAGE'
            Usage: install.sh --token-file <path>   (or - to read the token from stdin)
                              [--panel <host:port>] [--skip-doctor]

            The bootstrap token is single-use and lives for fifteen minutes. Issue one from the
            node's page in the panel.
            USAGE
              exit 2
            }

            TOKEN_FILE=""
            SKIP_DOCTOR=""

            while [ $# -gt 0 ]; do
              case "$1" in
                --token-file) [ $# -ge 2 ] || usage; TOKEN_FILE="$2"; shift 2 ;;
                --panel)      [ $# -ge 2 ] || usage; DIAL_ENDPOINT="$2"; shift 2 ;;
                --skip-doctor) SKIP_DOCTOR="yes"; shift ;;
                --token|--token=*)
                  echo "install.sh: refusing --token. argv is world-readable through ps;" >&2
                  echo "            use --token-file, or - for stdin." >&2
                  exit 2 ;;
                -h|--help) usage ;;
                *) echo "install.sh: unknown argument $1" >&2; usage ;;
              esac
            done

            [ -n "$TOKEN_FILE" ] || usage
            [ "$(id -u)" = "0" ] || { echo "install.sh: run this as root." >&2; exit 1; }

            command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || {
              echo "install.sh: neither curl nor wget is installed." >&2; exit 1; }
            command -v sha256sum >/dev/null 2>&1 || {
              echo "install.sh: sha256sum is not installed; the binary cannot be verified." >&2
              exit 1; }

            resolve_release "$(uname -m)"
            [ -n "$RELEASE_FILE" ] || {
              echo "install.sh: this panel publishes no sasayaki build for $(uname -m)." >&2
              exit 1; }

            WORK="$(mktemp -d)"
            trap 'rm -rf "$WORK"' EXIT INT TERM

            echo "Fetching sasayaki $RELEASE_VERSION for $(uname -m)"
            FETCH_URL="$DOWNLOAD_URL/$RELEASE_FILE"
            if command -v curl >/dev/null 2>&1; then
              if ! curl -fsSL "$FETCH_URL" -o "$WORK/sasayaki"; then
                # Fall back to unversioned release asset name (e.g. GitHub Releases latest asset)
                FALLBACK_URL="$DOWNLOAD_URL/sasayaki-linux-$RELEASE_ARCH"
                curl -fsSL "$FALLBACK_URL" -o "$WORK/sasayaki"
              fi
            else
              if ! wget -q -O "$WORK/sasayaki" "$FETCH_URL"; then
                FALLBACK_URL="$DOWNLOAD_URL/sasayaki-linux-$RELEASE_ARCH"
                wget -q -O "$WORK/sasayaki" "$FALLBACK_URL"
              fi
            fi

            echo "$RELEASE_SHA256  $WORK/sasayaki" | sha256sum -c - >/dev/null || {
              echo "install.sh: checksum mismatch. Nothing has been installed." >&2
              exit 1; }
            chmod 0755 "$WORK/sasayaki"

            # Preflight before anything is written, so "doctor failed, nothing was installed"
            # is literally true. A missing runsc is a warning and does not stop this.
            if [ -z "$SKIP_DOCTOR" ]; then
              "$WORK/sasayaki" doctor || {
                echo "install.sh: a required preflight check failed. Nothing was installed." >&2
                exit 1; }
            fi

            # The token file is read by sasayaki and deleted by it. Copying it into the work
            # directory first means a token passed on stdin never lands anywhere permanent.
            if [ "$TOKEN_FILE" = "-" ]; then
              umask 077
              cat > "$WORK/token"
              TOKEN_FILE="$WORK/token"
            fi

            install -m 0755 "$WORK/sasayaki" "$BINARY_PATH"

            # --skip-doctor unconditionally: the preflight above already ran, from the same
            # binary, and running it twice on a slow machine is thirty seconds of nothing.
            "$BINARY_PATH" install \\
              --token-file "$TOKEN_FILE" \\
              --panel "$DIAL_ENDPOINT" \\
              --config /etc/wisper/node.json \\
              --skip-doctor

            echo "sasayaki $RELEASE_VERSION installed. It is dialling $DIAL_ENDPOINT."
            """;
}
