package dbengine

import (
	"fmt"
	"strings"
)

// The one place where something the panel sent becomes part of a SQL string.
//
// Neither engine has a bind parameter for an identifier: `CREATE DATABASE $1` is not a
// statement either of them will run, so a database name and a username have to be
// interpolated. That makes this file the entire attack surface of the package, and it is
// written to make the dangerous version impossible rather than unlikely.
//
// Two independent defences, in this order:
//
//  1. The value is checked against exactly the shape the panel's own schema constrains it
//     to - managed_database.name is `^[a-z][a-z0-9_]{2,62}$` and db_username is
//     `^[a-z][a-z0-9_]{2,30}$` (V25__managed_database.sql). Anything else is refused, not
//     sanitised: sanitising maps two different names onto one database, which is worse than
//     a rejection somebody has to act on. After this check there is no quote, no backslash,
//     no semicolon and no space left to escape.
//  2. It is quoted anyway, the way the engine quotes identifiers. The check is what makes
//     the code safe; the quoting is what keeps it safe if the panel's constraint is ever
//     relaxed without this file being revisited.
//
// Passwords are different: they are values, not identifiers, and they are generated by the
// panel with whatever alphabet it likes. They are escaped rather than validated, apart from
// the three bytes that cannot survive the trip in either engine's client.

const (
	// maxDatabaseName is PostgreSQL's NAMEDATALEN - 1 and MySQL's identifier ceiling
	// rounded down to it, which is also what the panel's CHECK constraint allows.
	maxDatabaseName = 63
	// maxUsername is the panel's constraint. Shorter than a database name because MySQL
	// truncates a user beyond 32 characters, and a login that silently becomes a different
	// login is a customer who cannot connect and an operator who cannot see why.
	maxUsername = 31
	// maxEncoding bounds a character-set name. UTF8, utf8mb4, LATIN1 and everything else
	// either engine knows fits easily.
	maxEncoding = 32
)

// checkDatabaseName refuses anything that could not have come from the panel.
func checkDatabaseName(name string) error {
	return checkIdentifier("database name", name, maxDatabaseName)
}

// checkUsername refuses anything that could not have come from the panel.
func checkUsername(name string) error {
	return checkIdentifier("username", name, maxUsername)
}

// checkIdentifier is the shared shape: lower-case, starts with a letter, then letters,
// digits and underscores, at least three characters and at most the ceiling given.
func checkIdentifier(kind, value string, ceiling int) error {
	if value == "" {
		return fmt.Errorf("dbengine: the %s is empty", kind)
	}
	if len(value) < 3 {
		return fmt.Errorf("dbengine: the %s %q is shorter than three characters", kind, value)
	}
	if len(value) > ceiling {
		return fmt.Errorf("dbengine: the %s %q is longer than %d characters", kind, value, ceiling)
	}
	if value[0] < 'a' || value[0] > 'z' {
		return fmt.Errorf("dbengine: the %s %q does not start with a lower-case letter, and an "+
			"identifier that needs quoting to be legal is one every client library gets wrong "+
			"in a different way", kind, value)
	}
	for index := 0; index < len(value); index++ {
		character := value[index]
		switch {
		case character >= 'a' && character <= 'z',
			character >= '0' && character <= '9',
			character == '_':
		default:
			return fmt.Errorf("dbengine: the %s %q contains %q, and only lower-case letters, "+
				"digits and '_' may reach a SQL statement", kind, value, string(character))
		}
	}
	return nil
}

// checkEncoding refuses a character set that is not one word.
//
// The value is a string literal rather than an identifier in both dialects, so this is
// belt-and-braces on top of the escaping - but a character set is chosen once and can never
// be changed without dumping and reloading the customer's data, so a typo that reaches the
// server is expensive in a way a rejected one is not.
func checkEncoding(value string) error {
	if value == "" {
		return nil
	}
	if len(value) > maxEncoding {
		return fmt.Errorf("dbengine: the character set %q is longer than %d characters", value, maxEncoding)
	}
	for index := 0; index < len(value); index++ {
		character := value[index]
		switch {
		case character >= 'a' && character <= 'z',
			character >= 'A' && character <= 'Z',
			character >= '0' && character <= '9',
			character == '_', character == '-':
		default:
			return fmt.Errorf("dbengine: the character set %q contains %q, which no encoding "+
				"either engine knows has in its name", value, string(character))
		}
	}
	return nil
}

// checkPassword refuses the three bytes that cannot survive the trip.
//
// A NUL terminates the string inside the C client before the statement does. A newline or a
// carriage return ends the line the statement is on, which in `psql` is also the point where
// a backslash command would be read - so a password containing one is not merely mangled,
// it is a second instruction. Everything else, including quotes and backslashes, is escaped
// by the dialect and is fine.
func checkPassword(password string) error {
	if password == "" {
		return fmt.Errorf("dbengine: the password is empty, and an account with no password on a " +
			"shared server is an account anybody on it can use")
	}
	if strings.ContainsAny(password, "\x00\n\r") {
		return fmt.Errorf("dbengine: the password contains a null byte or a line break, which " +
			"neither engine's client can carry inside a statement")
	}
	return nil
}

// quotePostgres renders an identifier the way PostgreSQL reads one: double quotes, with an
// embedded double quote doubled.
func quotePostgres(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

// quoteMySQL renders an identifier the way MySQL reads one: backticks, with an embedded
// backtick doubled.
func quoteMySQL(value string) string {
	return "`" + strings.ReplaceAll(value, "`", "``") + "`"
}

// literalPostgres renders a string constant.
//
// Single quotes doubled, and nothing else - which is correct only while
// standard_conforming_strings is on, so every script that uses this sets it explicitly on
// its first line rather than trusting a server-side default that a customer's own
// `ALTER DATABASE ... SET` could have moved.
func literalPostgres(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

// literalMySQL renders a string constant.
//
// Only the quote is doubled, and that is correct only because every script this package
// sends MySQL begins with mysqlPrologue, which adds NO_BACKSLASH_ESCAPES to the session's
// sql_mode. Without it a backslash would be an escape character and there would be no single
// encoding of a password that is right under both settings - sql_mode is a server variable a
// customer's own connection can change, so it cannot be assumed either way. Fixing it for
// the length of the script is cheaper than guessing.
func literalMySQL(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
